with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475.00px; height:318.20px;\" coordsize=\"475.00,318.20\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:475.00px;height:318.20px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/1107_3.0_jpn_9509470_3.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475.00px;height:318.20px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401.950368px;top:204.893109px;font-weight:normal;font-size:23.2pt;color:black;\" prt_font_size=\"24.6pt\" disp_font_size=\"23.2pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:31.0px;\" src=\"../img/symbol/SymbolGaiji00007.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45.430391px;top:198.772701px;font-weight:normal;font-size:23.2pt;color:black;\" prt_font_size=\"24.6pt\" disp_font_size=\"23.2pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:31.0px;\" src=\"../img/symbol/SymbolGaiji00007.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:49.989506px;top:252.867223px;font-weight:normal;font-size:15.7pt;color:black;\" prt_font_size=\"16.9pt\" disp_font_size=\"15.7pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:21.0px;\" src=\"../img/symbol/SymbolGaiji00014.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408.061819px;top:258.439535px;font-weight:normal;font-size:15.7pt;color:black;\" prt_font_size=\"16.9pt\" disp_font_size=\"15.7pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:21.0px;\" src=\"../img/symbol/SymbolGaiji00014.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:162.023458px;top:278.549675px;font-weight:normal;font-size:11.2pt;color:black;\" prt_font_size=\"12.3pt\" disp_font_size=\"11.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">メス端子のコード側</font></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167.086033px;top:70.410256px;font-weight:normal;font-size:11.2pt;color:black;\" prt_font_size=\"12.3pt\" disp_font_size=\"11.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79.358607px;top:32.650789px;font-weight:normal;font-size:11.2pt;color:black;\" prt_font_size=\"12.3pt\" disp_font_size=\"11.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">オートA/Cコントロール ユニット36Pカプラ</font></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92.867561px;top:68.446246px;font-weight:normal;font-size:11.2pt;color:black;\" prt_font_size=\"12.3pt\" disp_font_size=\"11.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("</v:group>");
}