with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:1092.14px;\" coordsize=\"950.00,1092.14\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:1092.14px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/1160_2.0_jpn_9508552_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:1092.14px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666.140745px;top:604.563824px;font-weight:normal;font-size:13.5pt;color:black;\" prt_font_size=\"14.5pt\" disp_font_size=\"13.5pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:18px;\" src=\"../img/symbol/Gaiji00080.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:867.019753px;top:606.094211px;font-weight:normal;font-size:13.5pt;color:black;\" prt_font_size=\"14.5pt\" disp_font_size=\"13.5pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:18px;\" src=\"../img/symbol/Gaiji00081.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:371.170670px;top:901.250242px;font-weight:normal;font-size:13.5pt;color:black;\" prt_font_size=\"14.5pt\" disp_font_size=\"13.5pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:18px;\" src=\"../img/symbol/Gaiji00080.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:587.869158px;top:901.215460px;font-weight:normal;font-size:13.5pt;color:black;\" prt_font_size=\"14.5pt\" disp_font_size=\"13.5pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:18px;\" src=\"../img/symbol/Gaiji00081.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364.512553px;top:955.683330px;font-weight:normal;font-size:13.5pt;color:black;\" prt_font_size=\"14.5pt\" disp_font_size=\"13.5pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:18px;\" src=\"../img/symbol/Gaiji00080.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:561.185076px;top:955.718112px;font-weight:normal;font-size:13.5pt;color:black;\" prt_font_size=\"14.5pt\" disp_font_size=\"13.5pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:18px;\" src=\"../img/symbol/Gaiji00081.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66.626326px;top:981.247752px;font-weight:normal;font-size:13.5pt;color:black;\" prt_font_size=\"14.5pt\" disp_font_size=\"13.5pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:18px;\" src=\"../img/symbol/Gaiji00080.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265.518221px;top:981.247752px;font-weight:normal;font-size:13.5pt;color:black;\" prt_font_size=\"14.5pt\" disp_font_size=\"13.5pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:18px;\" src=\"../img/symbol/Gaiji00081.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:640.050216px;top:954.570321px;font-weight:normal;font-size:13.5pt;color:black;\" prt_font_size=\"14.5pt\" disp_font_size=\"13.5pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:18px;\" src=\"../img/symbol/Gaiji00080.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:853.393839px;top:956.761558px;font-weight:normal;font-size:13.5pt;color:black;\" prt_font_size=\"14.5pt\" disp_font_size=\"13.5pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:18px;\" src=\"../img/symbol/Gaiji00081.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636.746964px;top:111.953068px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">PGM-FI ECU</font></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:200.149962px;top:189.202838px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ABSまたはVSAモジュレータ<br>コントロール ユニット</font></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:760.335038px;top:673.118212px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">サブ リレー ボックス2</font></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:683.921530px;top:574.547367px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">熱線入りフロント ウインド リレー<br>(熱線入りフロント ウインド装備車)<br><font style=\"font-weight:normal;\"> コード色:茶、青、空、茶</font></font></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:353.338271px;top:1018.081388px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">サブ リレー ボックス1</font></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84.381305px;top:968.135117px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">コンデンサ ファン リレー<br><font style=\"font-weight:normal;\"> コード色:青、赤、緑、茶</font></font></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381.080426px;top:942.466350px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ラジエータ ファン リレー<br><font style=\"font-weight:normal;\"> コード色:黄、空、緑、茶</font></font></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388.874036px;top:886.920253px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A/Cコンプレッサ クラッチ リレー<br><font style=\"font-weight:normal;\"> コード色:若葉、白、桃、茶</font></font></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:650.089005px;top:925.910344px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ホーン リレー<br>（セキュリティ アラーム システム装備車）<br><font style=\"font-weight:normal;\"> コード色:紫、白、若葉、白</font></font></nobr>");
write("</p>");
write("</v:group>");
}