with(document) {
write("<v:group id=\"group14\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:495.14px;\" coordsize=\"950.00,495.14\">");
write("<v:rect id=\"rect14\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:495.14px;\">");
write("<img id=\"img14\" name=\"PrtImgId\" src=\"../img/1607_2.0_jpn_9507965_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:495.14px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p14_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:587.939653px;top:22.040296px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C</font></nobr>");
write("</p>");
write("<p id=\"p14_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132.826185px;top:22.040296px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A</font></nobr>");
write("</p>");
write("<p id=\"p14_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360.383257px;top:22.040296px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B</font></nobr>");
write("</p>");
write("<p id=\"p14_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815.497401px;top:22.040296px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">D</font></nobr>");
write("</p>");
write("<p id=\"p14_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:782.336697px;top:174.826869px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p14_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:782.336697px;top:197.953073px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p14_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:806.054107px;top:174.826869px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p14_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820.497905px;top:174.826869px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p14_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:836.424885px;top:174.826869px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p14_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:755.573826px;top:174.826869px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p14_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:739.646170px;top:174.826869px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p14_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723.716485px;top:174.826869px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p14_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:707.787477px;top:174.826869px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p14_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:691.857792px;top:174.826869px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p14_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:871.181667px;top:214.893899px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p14_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:855.253334px;top:214.893899px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p14_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:591.050686px;top:174.826869px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p14_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629.305861px;top:174.826869px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p14_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564.665710px;top:174.826869px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p14_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:655.689485px;top:174.826869px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p14_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538.282761px;top:174.826869px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p14_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511.899813px;top:174.826869px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p14_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:485.516188px;top:174.826869px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p14_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459.128508px;top:174.826869px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p14_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:236.661850px;top:174.826869px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p14_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:206.898136px;top:174.826869px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p14_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177.135098px;top:174.826869px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p14_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:147.371385px;top:174.826869px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p14_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242.295783px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p14_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228.642250px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p14_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214.988042px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p14_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201.334509px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p14_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:174.027444px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p14_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:160.373236px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p14_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:146.719703px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p14_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133.066171px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p14_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:119.412638px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p14_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105.758430px;top:286.171806px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p14_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92.104897px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p14_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255.949315px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p14_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269.603523px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p14_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283.257056px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p14_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296.910589px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p14_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310.564121px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p14_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324.218330px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p14_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337.871862px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p14_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:351.525395px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p14_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:449.531082px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p14_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:463.185290px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p14_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:476.842879px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p14_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:495.048040px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p14_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513.250496px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p14_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:531.456333px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p14_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:547.385342px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p14_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:565.589826px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p14_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:583.793635px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p14_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:601.998796px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p14_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629.305861px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p14_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642.958717px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p14_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:885.473360px;top:174.826869px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p14_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:663.440030px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p14_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:684.252591px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p14_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:702.455724px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p14_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720.660885px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p14_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738.866045px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p14_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754.795730px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p14_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:772.999538px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p14_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:791.203347px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p14_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809.407832px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p14_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:833.267882px;top:294.852163px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p14_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238.746013px;top:312.850480px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G301</font></nobr>");
write("</p>");
write("<p id=\"p14_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:88.555127px;top:357.699888px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G452</font></nobr>");
write("</p>");
write("<p id=\"p14_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:445.981312px;top:357.699888px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G203</font></nobr>");
write("</p>");
write("<p id=\"p14_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625.755415px;top:357.699888px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G203</font></nobr>");
write("</p>");
write("<p id=\"p14_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:881.924266px;top:206.359590px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G502</font></nobr>");
write("</p>");
write("<p id=\"p14_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:853.688353px;top:245.031733px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">112</font></nobr>");
write("</p>");
write("<p id=\"p14_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:869.618713px;top:245.031733px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">111</font></nobr>");
write("</p>");
write("<p id=\"p14_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235.096869px;top:148.340220px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">165</font></nobr>");
write("</p>");
write("<p id=\"p14_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536.716428px;top:148.340220px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">165</font></nobr>");
write("</p>");
write("<p id=\"p14_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824.570912px;top:205.321707px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">38</font></nobr>");
write("</p>");
write("<p id=\"p14_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:840.457332px;top:205.321707px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">39</font></nobr>");
write("</p>");
write("<p id=\"p14_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:881.647099px;top:110.382088px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(VSA装備車)</font></nobr>");
write("</p>");
write("<p id=\"p14_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551.968067px;top:316.917495px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p14_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570.174579px;top:316.917495px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p14_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:517.492509px;top:316.917495px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p14_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535.696317px;top:316.917495px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p14_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:480.986193px;top:316.917495px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p14_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:499.191353px;top:316.917495px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p14_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:763.859777px;top:327.300386px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">IC</font></nobr>");
write("</p>");
write("<p id=\"p14_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:800.267395px;top:327.188146px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">IC</font></nobr>");
write("</p>");
write("<p id=\"p14_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:688.473647px;top:316.991195px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p14_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706.678132px;top:316.991195px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p14_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724.883292px;top:316.991195px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p14_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:743.088453px;top:316.991195px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p14_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:759.015433px;top:316.991195px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p14_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:777.220594px;top:316.991195px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p14_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:795.763763px;top:316.991195px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p14_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:813.968248px;top:316.991195px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p14_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:626.572721px;top:262.719023px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MR-<br>GND</font></nobr>");
write("</p>");
write("<p id=\"p14_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:780.812277px;top:212.604470px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">IG1</font></nobr>");
write("</p>");
write("<p id=\"p14_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:830.390750px;top:266.773868px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">WEN</font></nobr>");
write("</p>");
write("<p id=\"p14_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:837.399703px;top:273.601585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">25</font></nobr>");
write("</p>");
write("<p id=\"p14_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:658.903274px;top:266.773868px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">K-LINE</font></nobr>");
write("</p>");
write("<p id=\"p14_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:667.571175px;top:273.601585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">15</font></nobr>");
write("</p>");
write("<p id=\"p14_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715.677957px;top:138.406967px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">舵角センサ</font></nobr>");
write("</p>");
write("<p id=\"p14_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:829.106316px;top:138.957349px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ヨーレート/横Gセンサ</font></nobr>");
write("</p>");
write("<p id=\"p14_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:759.704296px;top:152.973169px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p14_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:743.775963px;top:152.973169px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p14_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:727.846954px;top:152.973169px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p14_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711.918622px;top:152.973169px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p14_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:695.989613px;top:152.973169px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p14_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:810.459040px;top:152.973169px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p14_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:889.604505px;top:152.973169px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p14_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824.627697px;top:152.973169px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p14_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:840.557382px;top:152.973169px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p14_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:695.989613px;top:205.321707px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">32</font></nobr>");
write("</p>");
write("<p id=\"p14_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:687.628624px;top:212.604470px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ST-A</font></nobr>");
write("</p>");
write("<p id=\"p14_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:703.556957px;top:212.604470px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ST-B</font></nobr>");
write("</p>");
write("<p id=\"p14_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711.918622px;top:205.321707px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p14_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:633.436330px;top:205.321707px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">45</font></nobr>");
write("</p>");
write("<p id=\"p14_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:696.695376px;top:238.550878px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">VSAモジュレータ コントロール ユニット</font></nobr>");
write("</p>");
write("<p id=\"p14_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:633.436330px;top:273.601585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">46</font></nobr>");
write("</p>");
write("<p id=\"p14_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:623.723981px;top:212.604470px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MR ＋B</font></nobr>");
write("</p>");
write("<p id=\"p14_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:640.306023px;top:266.773868px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">GND</font></nobr>");
write("</p>");
write("<p id=\"p14_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647.089862px;top:273.601585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">43</font></nobr>");
write("</p>");
write("<p id=\"p14_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:688.382384px;top:273.601585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">10</font></nobr>");
write("</p>");
write("<p id=\"p14_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679.386615px;top:266.773868px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">RL-GND</font></nobr>");
write("</p>");
write("<p id=\"p14_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706.587545px;top:273.601585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">11</font></nobr>");
write("</p>");
write("<p id=\"p14_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:698.655827px;top:266.773868px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">RL＋B</font></nobr>");
write("</p>");
write("<p id=\"p14_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734.656482px;top:266.773868px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">RR＋B</font></nobr>");
write("</p>");
write("<p id=\"p14_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742.995838px;top:273.601585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">30</font></nobr>");
write("</p>");
write("<p id=\"p14_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714.813330px;top:266.773868px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">RR-GND</font></nobr>");
write("</p>");
write("<p id=\"p14_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724.790678px;top:273.601585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">8</font></nobr>");
write("</p>");
write("<p id=\"p14_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:795.335844px;top:273.601585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">28</font></nobr>");
write("</p>");
write("<p id=\"p14_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:785.622144px;top:266.773868px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FR-GND</font></nobr>");
write("</p>");
write("<p id=\"p14_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:813.539653px;top:273.601585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">29</font></nobr>");
write("</p>");
write("<p id=\"p14_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805.177988px;top:266.773868px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FR＋B</font></nobr>");
write("</p>");
write("<p id=\"p14_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769.445036px;top:266.773868px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FL＋B</font></nobr>");
write("</p>");
write("<p id=\"p14_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:777.130684px;top:273.601585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">34</font></nobr>");
write("</p>");
write("<p id=\"p14_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:749.316605px;top:266.773868px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FL-GND</font></nobr>");
write("</p>");
write("<p id=\"p14_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:758.926199px;top:273.601585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">13</font></nobr>");
write("</p>");
write("<p id=\"p14_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649.432264px;top:212.604470px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FSR ＋B</font></nobr>");
write("</p>");
write("<p id=\"p14_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:659.819954px;top:205.321707px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">44</font></nobr>");
write("</p>");
write("<p id=\"p14_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:786.469194px;top:205.321707px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">40</font></nobr>");
write("</p>");
write("<p id=\"p14_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:751.344659px;top:212.604470px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">SGND</font></nobr>");
write("</p>");
write("<p id=\"p14_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:759.704296px;top:205.321707px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">35</font></nobr>");
write("</p>");
write("<p id=\"p14_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:743.775963px;top:205.321707px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">33</font></nobr>");
write("</p>");
write("<p id=\"p14_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:735.417002px;top:212.604470px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">SVCC</font></nobr>");
write("</p>");
write("<p id=\"p14_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719.487317px;top:212.604470px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ST-Z</font></nobr>");
write("</p>");
write("<p id=\"p14_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:727.846954px;top:205.321707px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">17</font></nobr>");
write("</p>");
write("<p id=\"p14_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689.137496px;top:337.327624px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L. リヤ</font></nobr>");
write("</p>");
write("<p id=\"p14_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:725.547818px;top:337.327624px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R. リヤ</font></nobr>");
write("</p>");
write("<p id=\"p14_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:753.835784px;top:337.327624px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L. フロント</font></nobr>");
write("</p>");
write("<p id=\"p14_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:790.243402px;top:337.327624px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R. フロント</font></nobr>");
write("</p>");
write("<p id=\"p14_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734.980295px;top:346.319683px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ホイール センサ</font></nobr>");
write("</p>");
write("<p id=\"p14_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527.570583px;top:346.433951px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ホイール センサ</font></nobr>");
write("</p>");
write("<p id=\"p14_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:582.833690px;top:337.327624px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R. フロント</font></nobr>");
write("</p>");
write("<p id=\"p14_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:546.425397px;top:337.327624px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L. フロント</font></nobr>");
write("</p>");
write("<p id=\"p14_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518.136753px;top:337.327624px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R. リヤ</font></nobr>");
write("</p>");
write("<p id=\"p14_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481.728460px;top:337.327624px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L. リヤ</font></nobr>");
write("</p>");
write("<p id=\"p14_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:542.413907px;top:205.321707px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p14_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:533.376224px;top:212.604470px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">K-LINE</font></nobr>");
write("</p>");
write("<p id=\"p14_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:559.792298px;top:212.604470px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">CAN L</font></nobr>");
write("</p>");
write("<p id=\"p14_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568.796855px;top:205.321707px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p14_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:595.180480px;top:205.321707px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">12</font></nobr>");
write("</p>");
write("<p id=\"p14_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:586.932386px;top:212.604470px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">CAN H</font></nobr>");
write("</p>");
write("<p id=\"p14_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510.542369px;top:212.604470px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">IG1</font></nobr>");
write("</p>");
write("<p id=\"p14_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516.030282px;top:205.321707px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">20</font></nobr>");
write("</p>");
write("<p id=\"p14_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:489.646657px;top:205.321707px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">24</font></nobr>");
write("</p>");
write("<p id=\"p14_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:479.492869px;top:212.604470px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FSR ＋B</font></nobr>");
write("</p>");
write("<p id=\"p14_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551.516487px;top:273.601585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">11</font></nobr>");
write("</p>");
write("<p id=\"p14_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:541.892697px;top:266.773868px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FL-GND</font></nobr>");
write("</p>");
write("<p id=\"p14_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:569.720295px;top:273.601585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">22</font></nobr>");
write("</p>");
write("<p id=\"p14_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:561.359983px;top:266.773868px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FL＋B</font></nobr>");
write("</p>");
write("<p id=\"p14_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:597.768952px;top:266.773868px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FR＋B</font></nobr>");
write("</p>");
write("<p id=\"p14_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:606.128589px;top:273.601585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p14_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:577.536414px;top:266.773868px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FR-GND</font></nobr>");
write("</p>");
write("<p id=\"p14_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:587.924780px;top:273.601585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p14_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:517.382993px;top:273.601585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">19</font></nobr>");
write("</p>");
write("<p id=\"p14_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506.993275px;top:266.773868px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">RR-GND</font></nobr>");
write("</p>");
write("<p id=\"p14_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535.588154px;top:273.601585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">8</font></nobr>");
write("</p>");
write("<p id=\"p14_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527.225813px;top:266.773868px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">RR＋B</font></nobr>");
write("</p>");
write("<p id=\"p14_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490.817520px;top:266.773868px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">RL＋B</font></nobr>");
write("</p>");
write("<p id=\"p14_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:499.177833px;top:273.601585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">10</font></nobr>");
write("</p>");
write("<p id=\"p14_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472.848966px;top:266.773868px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">RL-GND</font></nobr>");
write("</p>");
write("<p id=\"p14_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446.812138px;top:262.671693px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MR-<br>GND</font></nobr>");
write("</p>");
write("<p id=\"p14_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:480.972672px;top:273.601585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">21</font></nobr>");
write("</p>");
write("<p id=\"p14_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467.319816px;top:273.601585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">23</font></nobr>");
write("</p>");
write("<p id=\"p14_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460.710390px;top:266.773868px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">GND</font></nobr>");
write("</p>");
write("<p id=\"p14_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:454.058374px;top:212.604470px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MR ＋B</font></nobr>");
write("</p>");
write("<p id=\"p14_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453.665607px;top:273.601585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">26</font></nobr>");
write("</p>");
write("<p id=\"p14_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:489.145728px;top:238.550878px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ABSモジュレータ コントロール ユニット</font></nobr>");
write("</p>");
write("<p id=\"p14_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:463.263033px;top:205.321707px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">25</font></nobr>");
write("</p>");
write("<p id=\"p14_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240.800431px;top:205.321707px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A7</font></nobr>");
write("</p>");
write("<p id=\"p14_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231.403783px;top:212.604470px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">K-LINE</font></nobr>");
write("</p>");
write("<p id=\"p14_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204.344141px;top:212.604470px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">NEP</font></nobr>");
write("</p>");
write("<p id=\"p14_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:211.037394px;top:205.321707px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A9</font></nobr>");
write("</p>");
write("<p id=\"p14_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:181.273004px;top:205.321707px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A11</font></nobr>");
write("</p>");
write("<p id=\"p14_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:175.323370px;top:212.604470px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">＋B</font></nobr>");
write("</p>");
write("<p id=\"p14_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145.663764px;top:212.604470px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">IG1</font></nobr>");
write("</p>");
write("<p id=\"p14_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:151.509966px;top:205.321707px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A1</font></nobr>");
write("</p>");
write("<p id=\"p14_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:848.501268px;top:253.238111px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">コンビネーション<br>メータ(6-B)</font></nobr>");
write("</p>");
write("<p id=\"p14_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693.316639px;top:327.300386px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">IC</font></nobr>");
write("</p>");
write("<p id=\"p14_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:729.724932px;top:327.300386px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">IC</font></nobr>");
write("</p>");
write("<p id=\"p14_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:556.449389px;top:327.437643px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">IC</font></nobr>");
write("</p>");
write("<p id=\"p14_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:522.314544px;top:327.437643px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">IC</font></nobr>");
write("</p>");
write("<p id=\"p14_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:592.859035px;top:327.437643px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">IC</font></nobr>");
write("</p>");
write("<p id=\"p14_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:485.905575px;top:327.437643px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">IC</font></nobr>");
write("</p>");
write("<p id=\"p14_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588.473030px;top:316.917495px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p14_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:606.678191px;top:316.917495px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p14_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588.078236px;top:110.916919px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(VSA非装備車)</font></nobr>");
write("</p>");
write("<p id=\"p14_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815.616380px;top:213.176489px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">CAN L</font></nobr>");
write("</p>");
write("<p id=\"p14_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831.546064px;top:213.176489px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">CAN H</font></nobr>");
write("</p>");
write("<p id=\"p14_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815.616380px;top:146.386160px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">CAN L</font></nobr>");
write("</p>");
write("<p id=\"p14_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831.546064px;top:146.386160px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">CAN H</font></nobr>");
write("</p>");
write("<p id=\"p14_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:821.466638px;top:337.548723px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">データ リンク <br>カプラ(DLC)<br>(4-A)<br></font></nobr>");
write("</p>");
write("<p id=\"p14_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:651.786158px;top:337.882063px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">データ リンク <br>カプラ(DLC)<br>(4-B)</font></nobr>");
write("</p>");
write("<p id=\"p14_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91.056394px;top:266.774544px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">PG</font></nobr>");
write("</p>");
write("<p id=\"p14_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199.364593px;top:238.550878px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">EPSコントロール ユニット</font></nobr>");
write("</p>");
write("<p id=\"p14_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:210.887317px;top:338.696142px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">モータ</font></nobr>");
write("</p>");
write("<p id=\"p14_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355.659244px;top:273.602261px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B7</font></nobr>");
write("</p>");
write("<p id=\"p14_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355.659244px;top:315.561147px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p14_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:302.309267px;top:338.696142px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">モータ角度センサ</font></nobr>");
write("</p>");
write("<p id=\"p14_224\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342.005711px;top:273.602261px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B9</font></nobr>");
write("</p>");
write("<p id=\"p14_225\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342.005711px;top:315.561147px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p14_226\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328.351503px;top:273.602261px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B12</font></nobr>");
write("</p>");
write("<p id=\"p14_227\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328.351503px;top:315.561147px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p14_228\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314.697970px;top:273.602261px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B13</font></nobr>");
write("</p>");
write("<p id=\"p14_229\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314.697970px;top:315.561147px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p14_230\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301.044438px;top:273.602261px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B10</font></nobr>");
write("</p>");
write("<p id=\"p14_231\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301.044438px;top:315.561147px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p14_232\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287.390905px;top:315.561147px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p14_233\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287.390905px;top:273.602261px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B11</font></nobr>");
write("</p>");
write("<p id=\"p14_234\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:273.736697px;top:315.561147px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">8</font></nobr>");
write("</p>");
write("<p id=\"p14_235\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260.083164px;top:315.561147px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p14_236\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:205.468358px;top:273.602261px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B16</font></nobr>");
write("</p>");
write("<p id=\"p14_237\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:232.775423px;top:273.602261px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B15</font></nobr>");
write("</p>");
write("<p id=\"p14_238\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:232.775423px;top:315.561147px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p14_239\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219.121891px;top:273.602261px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B14</font></nobr>");
write("</p>");
write("<p id=\"p14_240\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219.121891px;top:315.561147px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p14_241\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:205.468358px;top:315.561147px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p14_242\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:178.160617px;top:273.602261px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B1</font></nobr>");
write("</p>");
write("<p id=\"p14_243\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:178.160617px;top:315.561147px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p14_244\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:135.775650px;top:338.696142px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">トルク センサ</font></nobr>");
write("</p>");
write("<p id=\"p14_245\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109.566439px;top:360.722258px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ステアリング ギヤボックス</font></nobr>");
write("</p>");
write("<p id=\"p14_246\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:164.507085px;top:273.602261px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B5</font></nobr>");
write("</p>");
write("<p id=\"p14_247\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:164.507085px;top:315.561147px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p14_248\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150.853552px;top:273.602261px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B2</font></nobr>");
write("</p>");
write("<p id=\"p14_249\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150.853552px;top:315.561147px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p14_250\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137.200020px;top:273.602261px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B4</font></nobr>");
write("</p>");
write("<p id=\"p14_251\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137.200020px;top:315.561147px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p14_252\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:123.545811px;top:273.602261px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B3</font></nobr>");
write("</p>");
write("<p id=\"p14_253\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:123.545811px;top:315.561147px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p14_254\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109.892279px;top:273.602261px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B8</font></nobr>");
write("</p>");
write("<p id=\"p14_255\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:96.238746px;top:273.602261px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A10</font></nobr>");
write("</p>");
write("<p id=\"p14_256\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:104.710602px;top:266.774544px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">SG</font></nobr>");
write("</p>");
write("<p id=\"p14_257\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118.364135px;top:266.774544px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">SE</font></nobr>");
write("</p>");
write("<p id=\"p14_258\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131.341649px;top:266.774544px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">Sub</font></nobr>");
write("</p>");
write("<p id=\"p14_259\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:144.319164px;top:266.774544px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">Main</font></nobr>");
write("</p>");
write("<p id=\"p14_260\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158.649390px;top:266.774544px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">Vref</font></nobr>");
write("</p>");
write("<p id=\"p14_261\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172.302923px;top:266.774544px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">Vcc</font></nobr>");
write("</p>");
write("<p id=\"p14_262\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:200.286006px;top:266.774544px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MW</font></nobr>");
write("</p>");
write("<p id=\"p14_263\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:213.940214px;top:266.774544px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MV</font></nobr>");
write("</p>");
write("<p id=\"p14_264\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227.593747px;top:266.774544px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MU</font></nobr>");
write("</p>");
write("<p id=\"p14_265\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282.208553px;top:266.774544px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">S4</font></nobr>");
write("</p>");
write("<p id=\"p14_266\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.862085px;top:266.774544px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">S2</font></nobr>");
write("</p>");
write("<p id=\"p14_267\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309.516294px;top:266.774544px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">S3</font></nobr>");
write("</p>");
write("<p id=\"p14_268\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323.169826px;top:266.774544px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">S1</font></nobr>");
write("</p>");
write("<p id=\"p14_269\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336.823359px;top:266.774544px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R2</font></nobr>");
write("</p>");
write("<p id=\"p14_270\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350.476891px;top:266.774544px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R1</font></nobr>");
write("</p>");
write("<p id=\"p14_271\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:20.851264px;top:12.186827px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">EPS、ABS、VSA</font></nobr>");
write("</p>");
write("<p id=\"p14_272\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459.713939px;top:142.469925px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p14_273\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:449.815010px;top:128.406775px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.58(40A)*<sup>２</sup><br><sup></sup>ヒューズ<br>(1-A )</font></nobr>");
write("</p>");
write("<p id=\"p14_274\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:486.100944px;top:142.469925px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p14_275\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:476.197958px;top:128.406775px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.37(20A)*<sup>２</sup><br><sup></sup>ヒューズ<br>(1-A)</font></nobr>");
write("</p>");
write("<p id=\"p14_276\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511.684163px;top:142.469925px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">70</font></nobr>");
write("</p>");
write("<p id=\"p14_277\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:502.580907px;top:128.406775px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.11(7.5A)*<sup>２</sup><br><sup></sup>ヒューズ<br>(2-C)</font></nobr>");
write("</p>");
write("<p id=\"p14_278\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530.992585px;top:128.406775px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">データ リンク<br>カプラ(DLC)<br>(4-B)</font></nobr>");
write("</p>");
write("<p id=\"p14_279\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:563.098701px;top:142.469925px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">111</font></nobr>");
write("</p>");
write("<p id=\"p14_280\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:589.483001px;top:142.469925px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">112</font></nobr>");
write("</p>");
write("<p id=\"p14_281\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:661.872344px;top:327.556645px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">165</font></nobr>");
write("</p>");
write("<p id=\"p14_282\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831.702224px;top:327.556645px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">109</font></nobr>");
write("</p>");
write("<p id=\"p14_283\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:563.704412px;top:128.406775px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">コンビネーション<br>メータ(6-Ｂ)</font></nobr>");
write("</p>");
write("<p id=\"p14_284\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:147.280798px;top:142.469925px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">70</font></nobr>");
write("</p>");
write("<p id=\"p14_285\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138.057887px;top:128.406775px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.11(7.5A)*<sup>２</sup><br><sup></sup>ヒューズ<br>(2-C )</font></nobr>");
write("</p>");
write("<p id=\"p14_286\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177.957812px;top:142.469925px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p14_287\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167.820924px;top:128.406775px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.2(60A)*<sup>1</sup><br><sup></sup>ヒューズ<br>(1-A)</font></nobr>");
write("</p>");
write("<p id=\"p14_288\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201.640069px;top:128.406775px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">PGM-FI<br>ECU<br>(4-B)</font></nobr>");
write("</p>");
write("<p id=\"p14_289\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225.319623px;top:128.406775px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">データ リンク<br>カプラ(DLC)<br>(4-B)</font></nobr>");
write("</p>");
write("<p id=\"p14_290\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299.568691px;top:174.826869px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p14_291\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294.511402px;top:212.604470px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">CAN H</font></nobr>");
write("</p>");
write("<p id=\"p14_292\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:303.706596px;top:205.321707px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A5</font></nobr>");
write("</p>");
write("<p id=\"p14_293\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298.001681px;top:142.469925px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">112</font></nobr>");
write("</p>");
write("<p id=\"p14_294\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:205.330451px;top:142.469925px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">105</font></nobr>");
write("</p>");
write("<p id=\"p14_295\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266.425564px;top:174.826869px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p14_296\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:270.560765px;top:205.321707px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A3</font></nobr>");
write("</p>");
write("<p id=\"p14_297\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262.293067px;top:212.604470px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">CAN L</font></nobr>");
write("</p>");
write("<p id=\"p14_298\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264.857878px;top:142.469925px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">111</font></nobr>");
write("</p>");
write("<p id=\"p14_299\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:268.847736px;top:128.406775px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">コンビネーション<br>メータ(6-B)</font></nobr>");
write("</p>");
write("<p id=\"p14_300\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629.999455px;top:142.469925px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p14_301\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.339666px;top:128.406775px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.58(40A)*<sup>２</sup><br><sup></sup>ヒューズ<br>(1-A)</font></nobr>");
write("</p>");
write("<p id=\"p14_302\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:656.382404px;top:142.469925px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p14_303\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647.723291px;top:128.406775px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.37(20A)*<sup>２</sup><br><sup></sup>ヒューズ<br>(1-A)</font></nobr>");
write("</p>");
write("<p id=\"p14_304\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:782.121723px;top:142.469925px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">70</font></nobr>");
write("</p>");
write("<p id=\"p14_305\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:773.019143px;top:128.406775px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.11(7.5A)*<sup>２</sup><br><sup></sup>ヒューズ<br>(2-C)</font></nobr>");
write("</p>");
write("<p id=\"p14_306\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:830.540150px;top:36.656534px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">バッテリ ターミナル ヒューズ ボックス<br>ヒューズ ボックス<br>CANライン<br>その他の通信線<br>シールド線</font></nobr>");
write("</p>");
write("<p id=\"p14_307\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824.602685px;top:36.656534px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*1:<br>*2:</font></nobr>");
write("</p>");
write("<p id=\"p14_308\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:828.666904px;top:44.787860px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">:<br>:<br>:</font></nobr>");
write("</p>");
write("<p id=\"p14_309\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1.000000px;top:16.771094px;font-weight:normal;font-size:9.0pt;color:black;\" prt_font_size=\"10.2pt\" disp_font_size=\"9.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">14</font></nobr>");
write("</p>");
write("<p id=\"p14_310\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:933.953980px;top:16.771094px;font-weight:normal;font-size:9.0pt;color:black;\" prt_font_size=\"10.2pt\" disp_font_size=\"9.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">14</font></nobr>");
write("</p>");
write("</v:group>");
}