with(document) {
write("<v:group id=\"group8\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:495.14px;\" coordsize=\"950.00,495.14\">");
write("<v:rect id=\"rect8\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:495.14px;\">");
write("<img id=\"img8\" name=\"PrtImgId\" src=\"../img/1607_2.0_jpn_9507958_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:495.14px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p8_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:9.024673px;top:16.772469px;font-weight:normal;font-size:9.0pt;color:black;\" prt_font_size=\"10.2pt\" disp_font_size=\"9.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">8</font></nobr>");
write("</p>");
write("<p id=\"p8_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:20.365471px;top:12.187802px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ライティング システム、ヘッドライト レベリング システム、ドア ロック</font></nobr>");
write("</p>");
write("<p id=\"p8_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:933.353150px;top:16.772469px;font-weight:normal;font-size:9.0pt;color:black;\" prt_font_size=\"10.2pt\" disp_font_size=\"9.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">8</font></nobr>");
write("</p>");
write("<p id=\"p8_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:828.603187px;top:36.772567px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ヒューズ ボックス<br>3列シート非装備車<br>3列シート装備車</font></nobr>");
write("</p>");
write("<p id=\"p8_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:822.662414px;top:36.729966px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*1:<br>*2:<br>*3:<br></font></nobr>");
write("</p>");
write("<p id=\"p8_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:826.709899px;top:48.892179px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">: CANライン<br>: その他の通信線</font></nobr>");
write("</p>");
write("<p id=\"p8_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291.442189px;top:308.249036px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p8_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323.055561px;top:150.337044px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">フード<br>COMP</font></nobr>");
write("</p>");
write("<p id=\"p8_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:422.621796px;top:381.834278px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p8_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408.969984px;top:381.834278px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p8_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395.318172px;top:381.834278px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p8_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:488.861171px;top:381.834278px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p8_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475.210035px;top:381.834278px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p8_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:461.558223px;top:381.834278px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p8_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408.640129px;top:249.750590px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.5(10A)*<sup>1</sup><br><sup></sup>ヒューズ<br>(2-C)</font></nobr>");
write("</p>");
write("<p id=\"p8_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350.069886px;top:442.828594px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(ディスチャージ ヘッドライト装備車)</font></nobr>");
write("</p>");
write("<p id=\"p8_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:417.012231px;top:324.739633px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">IG1</font></nobr>");
write("</p>");
write("<p id=\"p8_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:445.293930px;top:324.739633px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B-CAN</font></nobr>");
write("</p>");
write("<p id=\"p8_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:482.560127px;top:324.739633px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">SCS</font></nobr>");
write("</p>");
write("<p id=\"p8_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521.049762px;top:324.739633px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">SSR</font></nobr>");
write("</p>");
write("<p id=\"p8_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538.392842px;top:336.072820px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">SG</font></nobr>");
write("</p>");
write("<p id=\"p8_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:522.466516px;top:336.072820px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">SSF</font></nobr>");
write("</p>");
write("<p id=\"p8_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506.538839px;top:336.072820px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">SV</font></nobr>");
write("</p>");
write("<p id=\"p8_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483.784917px;top:336.072820px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">AV</font></nobr>");
write("</p>");
write("<p id=\"p8_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:470.135132px;top:336.072820px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">AS</font></nobr>");
write("</p>");
write("<p id=\"p8_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:456.481968px;top:336.072820px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">AG</font></nobr>");
write("</p>");
write("<p id=\"p8_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:422.396711px;top:317.440006px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p8_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453.891118px;top:317.440006px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">16</font></nobr>");
write("</p>");
write("<p id=\"p8_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:488.861171px;top:317.440006px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">14</font></nobr>");
write("</p>");
write("<p id=\"p8_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527.542771px;top:317.440006px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p8_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:543.469097px;top:402.160983px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p8_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527.542771px;top:402.160983px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p8_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511.615769px;top:402.160983px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p8_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:543.469097px;top:342.531248px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p8_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545.117021px;top:259.182290px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p8_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545.117021px;top:265.958535px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p8_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527.542771px;top:278.834820px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p8_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527.542771px;top:342.531248px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p8_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511.615769px;top:342.531248px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">13</font></nobr>");
write("</p>");
write("<p id=\"p8_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:488.861171px;top:342.531248px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p8_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475.210035px;top:342.531248px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">11</font></nobr>");
write("</p>");
write("<p id=\"p8_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:461.558223px;top:342.531248px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p8_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:372.822456px;top:342.531248px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">9</font></nobr>");
write("</p>");
write("<p id=\"p8_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403.672024px;top:330.214184px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ヘッドライト オート レベリング コントロール ユニット</font></nobr>");
write("</p>");
write("<p id=\"p8_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450.182952px;top:429.142893px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.ヘッドライト<br>レベリング モータ</font></nobr>");
write("</p>");
write("<p id=\"p8_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366.138158px;top:336.072144px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">GND</font></nobr>");
write("</p>");
write("<p id=\"p8_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464.886515px;top:394.014073px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">駆動回路</font></nobr>");
write("</p>");
write("<p id=\"p8_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:384.200431px;top:429.142893px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.ヘッドライト<br>レベリング モータ</font></nobr>");
write("</p>");
write("<p id=\"p8_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398.901967px;top:394.014073px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">駆動回路</font></nobr>");
write("</p>");
write("<p id=\"p8_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85.951219px;top:442.828594px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(ディスチャージ ヘッドライト非装備車)</font></nobr>");
write("</p>");
write("<p id=\"p8_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:284.204978px;top:254.420458px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(12-C)</font></nobr>");
write("</p>");
write("<p id=\"p8_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:163.068379px;top:249.941956px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.5(10A)*<sup>1</sup><br><sup></sup>ヒューズ<br>(2-C)</font></nobr>");
write("</p>");
write("<p id=\"p8_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:154.541488px;top:315.476985px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p8_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:154.541488px;top:361.095764px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p8_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:154.541488px;top:338.284008px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p8_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:93.491924px;top:308.249036px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.ヘッドライト レベリング モータ</font></nobr>");
write("</p>");
write("<p id=\"p8_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130.946030px;top:330.146564px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">駆動回路</font></nobr>");
write("</p>");
write("<p id=\"p8_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:154.541488px;top:326.879821px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p8_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:154.541488px;top:372.499952px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p8_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258.873049px;top:235.391389px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(ディスチャージ ヘッドライト装備車)</font></nobr>");
write("</p>");
write("<p id=\"p8_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130.988614px;top:375.766696px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">駆動回路</font></nobr>");
write("</p>");
write("<p id=\"p8_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:93.491924px;top:353.869168px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.ヘッドライト レベリング モータ</font></nobr>");
write("</p>");
write("<p id=\"p8_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240.044944px;top:324.216928px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p8_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:246.870512px;top:337.901277px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p8_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:246.870512px;top:351.587654px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p8_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240.044944px;top:365.274708px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">0</font></nobr>");
write("</p>");
write("<p id=\"p8_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204.962010px;top:388.084436px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ヘッドライト マニュアル<br>レベリング スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p8_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:154.541488px;top:383.905492px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p8_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256.474164px;top:308.249036px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p8_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256.474164px;top:388.084436px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p8_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.993244px;top:346.569541px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">照明<br>(1.12W×2)</font></nobr>");
write("</p>");
write("<p id=\"p8_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291.442189px;top:388.084436px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p8_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258.750029px;top:319.106174px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2150Ω*<sup>2</sup><br><sup></sup>3090Ω*<sup>3</sup></font></nobr>");
write("</p>");
write("<p id=\"p8_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:267.325587px;top:131.377624px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.<br>ヘッドライト</font></nobr>");
write("</p>");
write("<p id=\"p8_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.642435px;top:135.027099px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p8_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281.624943px;top:180.647231px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p8_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319.727268px;top:135.027099px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p8_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:320.305191px;top:180.647231px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p8_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:276.482447px;top:146.432640px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ディスチャージ<br>ヘッドライト<br>ユニット</font></nobr>");
write("</p>");
write("<p id=\"p8_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283.244478px;top:173.804043px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">バルブ(35W)</font></nobr>");
write("</p>");
write("<p id=\"p8_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85.951219px;top:235.391389px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(ディスチャージ ヘッドライト非装備車)</font></nobr>");
write("</p>");
write("<p id=\"p8_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:198.358824px;top:180.647231px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p8_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:223.736716px;top:150.951714px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">HI<br>(60W)</font></nobr>");
write("</p>");
write("<p id=\"p8_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199.582262px;top:150.951714px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">LO<br>(55W)</font></nobr>");
write("</p>");
write("<p id=\"p8_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:732.432161px;top:214.861823px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(11-A)</font></nobr>");
write("</p>");
write("<p id=\"p8_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:542.705969px;top:218.511974px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(11-C)</font></nobr>");
write("</p>");
write("<p id=\"p8_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:542.705969px;top:214.861823px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU</font></nobr>");
write("</p>");
write("<p id=\"p8_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515.843052px;top:80.283617px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">コンビネーション スイッチ(ライティング スイッチ)</font></nobr>");
write("</p>");
write("<p id=\"p8_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528.426891px;top:93.969318px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ターン シグナル スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p8_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:542.079379px;top:165.093853px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p8_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:560.280218px;top:165.028937px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p8_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:560.280218px;top:137.307937px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R</font></nobr>");
write("</p>");
write("<p id=\"p8_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535.253811px;top:137.307937px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L</font></nobr>");
write("</p>");
write("<p id=\"p8_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:763.350674px;top:165.007299px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p8_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:583.034816px;top:93.969318px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ライティング スイッチ </font></nobr>");
write("</p>");
write("<p id=\"p8_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:732.930323px;top:131.127428px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">パッシング</font></nobr>");
write("</p>");
write("<p id=\"p8_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726.896948px;top:121.539525px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ディマ</font></nobr>");
write("</p>");
write("<p id=\"p8_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710.841519px;top:131.595362px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">HI</font></nobr>");
write("</p>");
write("<p id=\"p8_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722.134327px;top:142.706077px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">LO</font></nobr>");
write("</p>");
write("<p id=\"p8_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:585.249172px;top:131.106466px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">OFF</font></nobr>");
write("</p>");
write("<p id=\"p8_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:617.044369px;top:131.196401px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">)</font></nobr>");
write("</p>");
write("<p id=\"p8_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:717.846886px;top:165.028937px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p8_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:736.047049px;top:165.007299px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p8_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:603.512196px;top:165.028937px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">8</font></nobr>");
write("</p>");
write("<p id=\"p8_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:614.888144px;top:165.028937px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">9</font></nobr>");
write("</p>");
write("<p id=\"p8_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607.942935px;top:142.829822px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">)</font></nobr>");
write("</p>");
write("<p id=\"p8_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602.284703px;top:142.829822px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(</font></nobr>");
write("</p>");
write("<p id=\"p8_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:611.578777px;top:131.196401px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(</font></nobr>");
write("</p>");
write("<p id=\"p8_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:592.134898px;top:165.093853px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">10</font></nobr>");
write("</p>");
write("<p id=\"p8_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201.687792px;top:345.766886px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p8_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258.750029px;top:332.792552px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">604Ω*<sup>2</sup><br><sup></sup>316Ω*<sup>3</sup></font></nobr>");
write("</p>");
write("<p id=\"p8_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258.750029px;top:346.477577px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">243Ω*<sup>2</sup><br><sup></sup>237Ω*<sup>3</sup></font></nobr>");
write("</p>");
write("<p id=\"p8_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258.750029px;top:360.164631px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1210Ω*<sup>2</sup><br><sup></sup>523Ω*<sup>3</sup></font></nobr>");
write("</p>");
write("<p id=\"p8_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258.750029px;top:375.766696px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">487Ω</font></nobr>");
write("</p>");
write("<p id=\"p8_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:436.063394px;top:253.444695px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">コンビネーション<br>メータ(6-B)</font></nobr>");
write("</p>");
write("<p id=\"p8_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513.096061px;top:409.543784px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">フロント<br>ヘッドライト<br>レベリング<br>センサ</font></nobr>");
write("</p>");
write("<p id=\"p8_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513.225841px;top:259.329026px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">リヤ<br>ヘッドライト<br>レベリング<br>センサ </font></nobr>");
write("</p>");
write("<p id=\"p8_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:659.798463px;top:165.029614px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">8</font></nobr>");
write("</p>");
write("<p id=\"p8_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:686.380191px;top:165.029614px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">9</font></nobr>");
write("</p>");
write("<p id=\"p8_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647.408617px;top:165.029614px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">10</font></nobr>");
write("</p>");
write("<p id=\"p8_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:595.859287px;top:214.861823px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(11-A)</font></nobr>");
write("</p>");
write("<p id=\"p8_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:658.661544px;top:214.861823px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(11-A)</font></nobr>");
write("</p>");
write("<p id=\"p8_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:640.516131px;top:131.271460px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">OFF</font></nobr>");
write("</p>");
write("<p id=\"p8_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:691.848487px;top:136.122551px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">)</font></nobr>");
write("</p>");
write("<p id=\"p8_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:686.000317px;top:136.122551px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(</font></nobr>");
write("</p>");
write("<p id=\"p8_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:664.873365px;top:144.082153px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">)</font></nobr>");
write("</p>");
write("<p id=\"p8_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:659.023844px;top:144.082153px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(</font></nobr>");
write("</p>");
write("<p id=\"p8_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:667.733912px;top:144.219422px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">AUTO</font></nobr>");
write("</p>");
write("<p id=\"p8_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:633.093038px;top:229.970258px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(ディスチャージ ヘッドライト装備車)</font></nobr>");
write("</p>");
write("<p id=\"p8_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578.921766px;top:229.970258px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(ディスチャージ <br>ヘッドライト非装備車)</font></nobr>");
write("</p>");
write("<p id=\"p8_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:677.530205px;top:412.550188px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">フューエル リッド <br>ロック アクチュエータ</font></nobr>");
write("</p>");
write("<p id=\"p8_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711.539082px;top:423.804259px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p8_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:683.343226px;top:423.804259px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p8_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:791.837856px;top:384.720319px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.スライド ドア<br>ロック アクチュエータ</font></nobr>");
write("</p>");
write("<p id=\"p8_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:825.846733px;top:395.974389px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p8_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:797.650201px;top:395.974389px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p8_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:791.837856px;top:355.254035px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ドライバ ドア<br>ロック アクチュエータ</font></nobr>");
write("</p>");
write("<p id=\"p8_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:825.846733px;top:366.506752px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p8_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:797.650201px;top:366.506752px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p8_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:762.724760px;top:329.713793px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.50(15A)*<sup>1</sup><br><sup></sup>ヒューズ<br>(2-B)</font></nobr>");
write("</p>");
write("<p id=\"p8_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:837.119938px;top:329.713793px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.36(15A)*<sup>1</sup><br><sup></sup>ヒューズ<br>(2-B)</font></nobr>");
write("</p>");
write("<p id=\"p8_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:791.837180px;top:412.550188px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">テールゲート<br>ロック アクチュエータ</font></nobr>");
write("</p>");
write("<p id=\"p8_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:825.845381px;top:423.804259px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p8_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:797.650877px;top:423.804259px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p8_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:677.529529px;top:384.720319px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.スライド ドア<br>ロック アクチュエータ</font></nobr>");
write("</p>");
write("<p id=\"p8_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711.537730px;top:395.974389px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p8_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:683.343902px;top:395.974389px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p8_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:677.475454px;top:355.705063px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">アシスタント ドア<br>ロック アクチュエータ</font></nobr>");
write("</p>");
write("<p id=\"p8_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711.537730px;top:366.506752px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p8_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:683.343902px;top:366.506752px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p8_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:648.699648px;top:329.713793px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.49(15A)*<sup>1</sup><br><sup></sup>ヒューズ<br>(2-B)</font></nobr>");
write("</p>");
write("<p id=\"p8_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723.462534px;top:329.713793px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.35(15A)*<sup>1</sup><br><sup></sup>ヒューズ<br>(2-B)</font></nobr>");
write("</p>");
write("<p id=\"p8_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:773.111817px;top:440.124453px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(Hondaスマート キー システム非装備車)</font></nobr>");
write("</p>");
write("<p id=\"p8_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:473.908189px;top:249.750590px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">データ リンク<br>カプラ(DLC)<br>(4-A)</font></nobr>");
write("</p>");
write("<p id=\"p8_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:757.670135px;top:203.160782px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">114</font></nobr>");
write("</p>");
write("<p id=\"p8_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:730.350288px;top:208.458167px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">155</font></nobr>");
write("</p>");
write("<p id=\"p8_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:712.146069px;top:208.458167px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">154</font></nobr>");
write("</p>");
write("<p id=\"p8_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:681.253918px;top:208.640742px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">156</font></nobr>");
write("</p>");
write("<p id=\"p8_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:654.335575px;top:208.640742px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">152 </font></nobr>");
write("</p>");
write("<p id=\"p8_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642.397252px;top:208.640742px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">153</font></nobr>");
write("</p>");
write("<p id=\"p8_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609.189355px;top:208.458167px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">156</font></nobr>");
write("</p>");
write("<p id=\"p8_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:597.813408px;top:208.458167px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">152</font></nobr>");
write("</p>");
write("<p id=\"p8_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:586.438813px;top:208.458167px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">153</font></nobr>");
write("</p>");
write("<p id=\"p8_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:554.582782px;top:208.458167px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">129</font></nobr>");
write("</p>");
write("<p id=\"p8_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536.381267px;top:208.458167px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">128</font></nobr>");
write("</p>");
write("<p id=\"p8_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:731.823822px;top:181.180080px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p8_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713.619602px;top:181.180080px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p8_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535.662750px;top:181.180080px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p8_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:758.957111px;top:181.180080px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720.649302px;top:427.172433px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p8_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720.649302px;top:399.342563px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p8_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720.649302px;top:369.876956px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p8_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:733.573811px;top:360.371550px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p8_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:733.489320px;top:384.698004px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p8_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:659.177957px;top:343.628728px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">57</font></nobr>");
write("</p>");
write("<p id=\"p8_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:733.818499px;top:343.628728px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">55</font></nobr>");
write("</p>");
write("<p id=\"p8_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:773.361912px;top:343.628728px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">58</font></nobr>");
write("</p>");
write("<p id=\"p8_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:847.932157px;top:343.628728px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">56</font></nobr>");
write("</p>");
write("<p id=\"p8_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:555.885304px;top:181.178728px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p8_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588.077950px;top:181.180080px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p8_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:610.499989px;top:181.178728px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p8_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:599.122690px;top:181.180080px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p8_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:643.703830px;top:181.180080px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p8_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:682.542245px;top:181.178728px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p8_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:655.640125px;top:181.180080px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p8_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:672.095706px;top:369.881689px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p8_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:659.003566px;top:384.698680px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p8_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:659.003566px;top:360.372226px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p8_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:672.095706px;top:399.346621px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p8_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:672.095706px;top:427.177166px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p8_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:786.405385px;top:369.876956px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p8_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:773.312569px;top:360.372902px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p8_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:773.311217px;top:384.699357px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p8_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:786.405385px;top:399.341887px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p8_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:786.405385px;top:427.172433px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p8_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834.957629px;top:369.873574px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p8_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:847.878083px;top:360.372226px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p8_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:847.878083px;top:384.698680px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p8_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834.957629px;top:399.340535px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p8_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834.957629px;top:427.170404px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p8_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:365.136426px;top:431.284432px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G451</font></nobr>");
write("</p>");
write("<p id=\"p8_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248.789485px;top:431.284432px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G501</font></nobr>");
write("</p>");
write("<p id=\"p8_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:182.208765px;top:431.284432px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G401</font></nobr>");
write("</p>");
write("<p id=\"p8_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:160.174711px;top:431.284432px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G202</font></nobr>");
write("</p>");
write("<p id=\"p8_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:448.211256px;top:264.035409px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">113</font></nobr>");
write("</p>");
write("<p id=\"p8_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:418.164697px;top:264.035409px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">65</font></nobr>");
write("</p>");
write("<p id=\"p8_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:285.760299px;top:264.035409px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">172</font></nobr>");
write("</p>");
write("<p id=\"p8_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172.809920px;top:264.035409px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">65</font></nobr>");
write("</p>");
write("<p id=\"p8_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483.162383px;top:269.332795px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">108</font></nobr>");
write("</p>");
write("<p id=\"p8_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:523.320895px;top:349.648300px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p8_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:415.940878px;top:296.452649px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p8_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447.477869px;top:296.452649px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p8_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:484.557508px;top:296.451973px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p8_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:523.155968px;top:296.451973px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p8_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:539.076886px;top:349.647623px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p8_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564.108701px;top:296.451973px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p8_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287.136498px;top:396.126535px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:368.432274px;top:374.873430px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252.086009px;top:396.126535px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252.086009px;top:412.028158px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185.504612px;top:403.992145px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:163.470559px;top:403.992145px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:418.488468px;top:374.873430px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p8_224\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404.921147px;top:374.873430px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p8_225\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:507.223558px;top:349.646947px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p8_226\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:539.076886px;top:374.872754px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p8_227\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:507.223558px;top:374.872078px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p8_228\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:580.035703px;top:296.451297px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p8_229\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391.269335px;top:374.872078px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p8_230\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:484.387173px;top:374.873430px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p8_231\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:470.817148px;top:374.873430px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p8_232\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:457.165336px;top:374.872078px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p8_233\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:484.475720px;top:349.648300px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p8_234\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:470.905020px;top:349.648300px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p8_235\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:457.253208px;top:349.646947px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p8_236\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170.544194px;top:347.619686px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p8_237\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:250.142703px;top:300.284700px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p8_238\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170.292747px;top:300.284700px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p8_239\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:159.476473px;top:318.956057px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p8_240\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170.544194px;top:281.802005px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p8_241\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185.589780px;top:347.619010px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p8_242\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:174.472039px;top:375.891793px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p8_243\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287.049303px;top:281.802005px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p8_244\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312.618484px;top:223.847227px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G401</font></nobr>");
write("</p>");
write("<p id=\"p8_245\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:273.939588px;top:223.847227px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G451</font></nobr>");
write("</p>");
write("<p id=\"p8_246\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283.130921px;top:62.899754px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.48(15A)*<sup>1</sup><br><sup></sup>ヒューズ<br>(1-D)</font></nobr>");
write("</p>");
write("<p id=\"p8_247\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291.999834px;top:76.993207px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">39</font></nobr>");
write("</p>");
write("<p id=\"p8_248\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309.648436px;top:62.899754px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.34(10A)*<sup>1</sup><br><sup></sup>ヒューズ<br>(2-D)</font></nobr>");
write("</p>");
write("<p id=\"p8_249\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316.153612px;top:76.993207px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">89</font></nobr>");
write("</p>");
write("<p id=\"p8_250\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:406.769147px;top:150.337044px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">フード<br>COMP</font></nobr>");
write("</p>");
write("<p id=\"p8_251\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:351.041878px;top:131.377624px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.<br>ヘッドライト</font></nobr>");
write("</p>");
write("<p id=\"p8_252\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:379.358725px;top:135.027099px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p8_253\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:365.338530px;top:180.647231px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p8_254\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403.443558px;top:135.027099px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p8_255\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404.018777px;top:180.647231px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p8_256\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360.198738px;top:146.432640px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ディスチャージ<br>ヘッドライト<br>ユニット</font></nobr>");
write("</p>");
write("<p id=\"p8_257\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366.960768px;top:173.804043px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">バルブ(35W)</font></nobr>");
write("</p>");
write("<p id=\"p8_258\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:396.334775px;top:223.847227px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G201<br>G202</font></nobr>");
write("</p>");
write("<p id=\"p8_259\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:357.655203px;top:223.847227px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G301</font></nobr>");
write("</p>");
write("<p id=\"p8_260\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366.847211px;top:62.899754px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.32(15A)*<sup>1</sup><br><sup></sup>ヒューズ<br>(1-D)</font></nobr>");
write("</p>");
write("<p id=\"p8_261\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:375.715448px;top:76.993207px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">37</font></nobr>");
write("</p>");
write("<p id=\"p8_262\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393.002426px;top:62.899754px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.51(10A)*<sup>1</sup><br><sup></sup>ヒューズ<br>(2-D)</font></nobr>");
write("</p>");
write("<p id=\"p8_263\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:399.869902px;top:76.993207px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">88</font></nobr>");
write("</p>");
write("<p id=\"p8_264\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:277.231380px;top:195.686694px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_265\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:190.675497px;top:223.847227px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G202</font></nobr>");
write("</p>");
write("<p id=\"p8_266\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193.967965px;top:195.686694px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_267\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315.910952px;top:195.686694px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_268\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:361.036218px;top:195.686694px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_269\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:399.627242px;top:195.686694px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_270\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:375.476844px;top:111.517500px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p8_271\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:399.624539px;top:111.517500px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p8_272\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170.110921px;top:131.377624px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.<br>ヘッドライト</font></nobr>");
write("</p>");
write("<p id=\"p8_273\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197.853226px;top:135.027099px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p8_274\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221.938060px;top:135.027099px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p8_275\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185.341712px;top:62.899754px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.32(10A)*<sup>1</sup><br><sup></sup>ヒューズ<br>(1-D)</font></nobr>");
write("</p>");
write("<p id=\"p8_276\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194.210625px;top:76.993207px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">31</font></nobr>");
write("</p>");
write("<p id=\"p8_277\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:211.496252px;top:62.899754px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.51(10A)*<sup>1</sup><br><sup></sup>ヒューズ<br>(1-D)</font></nobr>");
write("</p>");
write("<p id=\"p8_278\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218.173115px;top:76.993207px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">35</font></nobr>");
write("</p>");
write("<p id=\"p8_279\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193.972021px;top:111.517500px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p8_280\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218.119040px;top:111.517500px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p8_281\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315.908924px;top:111.518176px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p8_282\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291.761229px;top:111.516824px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p8_283\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:123.633790px;top:180.647231px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p8_284\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:149.011682px;top:150.951714px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">HI<br>(60W)</font></nobr>");
write("</p>");
write("<p id=\"p8_285\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124.857228px;top:150.951714px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">LO<br>(55W)</font></nobr>");
write("</p>");
write("<p id=\"p8_286\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:115.950464px;top:223.847227px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G401</font></nobr>");
write("</p>");
write("<p id=\"p8_287\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:119.242931px;top:195.686694px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_288\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95.386564px;top:131.377624px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.<br>ヘッドライト</font></nobr>");
write("</p>");
write("<p id=\"p8_289\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:123.128193px;top:135.027099px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p8_290\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:147.213026px;top:135.027099px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p8_291\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:110.616679px;top:62.899754px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.34(10A)*<sup>1</sup><br><sup></sup>ヒューズ<br>(1-D)</font></nobr>");
write("</p>");
write("<p id=\"p8_292\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:119.293627px;top:76.993207px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">32</font></nobr>");
write("</p>");
write("<p id=\"p8_293\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:136.771218px;top:62.899754px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.48(10A)*<sup>1</sup><br><sup></sup>ヒューズ<br>(1-D)</font></nobr>");
write("</p>");
write("<p id=\"p8_294\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143.448081px;top:76.993207px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">34</font></nobr>");
write("</p>");
write("<p id=\"p8_295\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143.391303px;top:111.492480px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p8_296\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:119.244283px;top:111.491128px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p8_297\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:587.385119px;top:22.042129px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C</font></nobr>");
write("</p>");
write("<p id=\"p8_298\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132.328988px;top:22.042129px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A</font></nobr>");
write("</p>");
write("<p id=\"p8_299\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359.857392px;top:22.042129px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B</font></nobr>");
write("</p>");
write("<p id=\"p8_300\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:814.914198px;top:22.042129px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">D</font></nobr>");
write("</p>");
write("</v:group>");
}