with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:491.68px;\" coordsize=\"950.00,491.68\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:491.68px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/1690_2.0_jpn_9507910_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:491.68px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:561.778987px;top:243.115074px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">プレッシャ<br>レギュレータ</font></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226.671234px;top:302.089566px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">フューエル サブ ポンプ<br>センダ ユニット</font></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:99.125475px;top:87.077835px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">サクション フィルタ</font></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:732.153393px;top:418.900777px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">フューエル ポンプ</font></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:436.547507px;top:19.082441px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">フューエル サブ ポンプ</font></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:604.723347px;top:156.089097px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ジェット ポンプ</font></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312.458703px;top:383.074518px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">フューエル センダ ユニット</font></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446.122841px;top:428.707284px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">トランスファ チューブ</font></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:655.738758px;top:448.333843px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">サクション フィルタ</font></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:793.033422px;top:196.141364px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">フューエル フィルタ</font></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450.534438px;top:117.174601px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1ウェイ バルブ</font></nobr>");
write("</p>");
write("</v:group>");
}