with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:409.01px;\" coordsize=\"950.00,409.01\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:409.01px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/1723_2.0_jpn_9507810_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:409.01px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:88.966935px;top:44.253105px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.3pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">駆動力</font></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364.652229px;top:43.743291px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.3pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">駆動力</font></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220.240134px;top:95.304051px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.3pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">フロント<br>ポンプ</font></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:146.731773px;top:144.698100px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.3pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">オイル<br>ケース</font></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330.645798px;top:148.090858px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.3pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">フロント ポンプ油圧</font></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73.487558px;top:274.580028px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.3pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">リヤ ポンプ油圧</font></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227.278415px;top:261.584605px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.3pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">リヤ<br>ポンプ</font></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266.336243px;top:157.061096px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.3pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">多板<br>クラッチ</font></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:175.706801px;top:227.160556px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.3pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">リリーフ<br>バルブ</font></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453.759586px;top:191.149630px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.3pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ポンプ発生油圧:<br>フロント ポンプ＞リヤ ポンプ</font></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:88.249215px;top:347.650521px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.3pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">駆動力</font></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:365.288915px;top:347.140707px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.3pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">駆動力</font></nobr>");
write("</p>");
write("</v:group>");
}