with(document) {
write("<v:group id=\"group4\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:560.37px;\" coordsize=\"950.00,560.37\">");
write("<v:rect id=\"rect4\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:560.37px;\">");
write("<img id=\"img4\" name=\"PrtImgId\" src=\"../img/1778_2.0_jpn_9507687_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:560.37px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p4_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:443.533633px;top:17.191699px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ブロア モータ</font></nobr>");
write("</p>");
write("<p id=\"p4_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:152.936026px;top:48.292587px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">エキスパンション バルブ<br><font style=\"font-weight:normal;\">冷媒の膨張、霧化を行う。</font></font></nobr>");
write("</p>");
write("<p id=\"p4_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551.648118px;top:44.364896px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">エバポレータ<br><font style=\"font-weight:normal;\">ブロア モータより導かれた空気を<br>吸熱、冷却する。</font></font></nobr>");
write("</p>");
write("<p id=\"p4_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:561.164115px;top:111.616558px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">エバポレータ センサ<br><font style=\"font-weight:normal;\">エバポレータ コアの温度を<br>測定する。</font></font></nobr>");
write("</p>");
write("<p id=\"p4_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:678.314760px;top:331.246547px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">コンプレッサ<br><font style=\"font-weight:normal;\">冷媒の吸入、圧縮を行う。</font></font></nobr>");
write("</p>");
write("<p id=\"p4_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266.008395px;top:453.886652px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">コンデンサ<br><font style=\"font-weight:normal;\">冷媒の冷却、<br>凝縮を行う。</font></font></nobr>");
write("</p>");
write("<p id=\"p4_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374.442744px;top:501.980808px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">レシーバ タンク<br><font style=\"font-weight:normal;\">冷媒を気体と液体に分離し、<br>水分、ゴミを除去する。</font></font></nobr>");
write("</p>");
write("<p id=\"p4_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:684.072328px;top:406.353595px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">高温、高圧のガス</font></nobr>");
write("</p>");
write("<p id=\"p4_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:684.072328px;top:443.145624px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">高温、高圧の液化ガス</font></nobr>");
write("</p>");
write("<p id=\"p4_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:684.072328px;top:479.376553px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">高温、高圧の霧化ガス</font></nobr>");
write("</p>");
write("<p id=\"p4_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:684.072328px;top:515.366992px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">低圧ガス</font></nobr>");
write("</p>");
write("<p id=\"p4_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:29.297255px;top:249.009693px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A/Cプレッシャ スイッチ<br><font style=\"font-weight:normal;\">システム内の冷媒圧力が<br>約3,100kPa以上/約200kPa<br>以下でOFFになると、PGM-FI<br>ECUがコンプレッサをOFF<br>にして異常圧力時の制御を行う。</font></font></nobr>");
write("</p>");
write("</v:group>");
}