with(document) {
write("<v:group id=\"group7\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:658.14px;\" coordsize=\"950.00,658.14\">");
write("<v:rect id=\"rect7\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:658.14px;\">");
write("<img id=\"img7\" name=\"PrtImgId\" src=\"../img/1851_2.0_jpn_9507550_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:658.14px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p7_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783.953468px;top:154.439198px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">車両信号</font></nobr>");
write("</p>");
write("<p id=\"p7_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:797.725571px;top:171.088706px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">パーキング<br>ブレーキ スイッチ<br>バック アップ<br>ライト<br>PGM-FI ECU<br>(VSP)</font></nobr>");
write("</p>");
write("<p id=\"p7_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783.953468px;top:171.726285px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">·</font></nobr>");
write("</p>");
write("<p id=\"p7_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:784.677553px;top:200.765113px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">·</font></nobr>");
write("</p>");
write("<p id=\"p7_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783.953468px;top:231.252985px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">·</font></nobr>");
write("</p>");
write("<p id=\"p7_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197.717155px;top:17.883063px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">アンテナ</font></nobr>");
write("</p>");
write("<p id=\"p7_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199.556388px;top:108.299459px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">アンプ</font></nobr>");
write("</p>");
write("<p id=\"p7_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:166.366608px;top:189.013372px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">フロント エンド<br>I/F</font></nobr>");
write("</p>");
write("<p id=\"p7_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:154.375755px;top:279.911860px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">チューナ<br>I/F</font></nobr>");
write("</p>");
write("<p id=\"p7_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231.939775px;top:279.520618px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">TS<br>デコーダ</font></nobr>");
write("</p>");
write("<p id=\"p7_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176.046294px;top:432.198218px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">メモリ</font></nobr>");
write("</p>");
write("<p id=\"p7_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300.473896px;top:432.438247px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">CPU</font></nobr>");
write("</p>");
write("<p id=\"p7_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:303.112761px;top:521.894491px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">TVチューナ</font></nobr>");
write("</p>");
write("<p id=\"p7_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491.193581px;top:603.669329px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">リヤ カメラ</font></nobr>");
write("</p>");
write("<p id=\"p7_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538.053846px;top:537.897382px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">NTSC</font></nobr>");
write("</p>");
write("<p id=\"p7_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:597.388888px;top:421.876356px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.8pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">GA-NET II</font></nobr>");
write("</p>");
write("<p id=\"p7_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:606.105167px;top:277.050071px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">NTSC</font></nobr>");
write("</p>");
write("<p id=\"p7_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602.746580px;top:185.593483px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AUDIO</font></nobr>");
write("</p>");
write("<p id=\"p7_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:709.021814px;top:198.795881px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">DVD</font></nobr>");
write("</p>");
write("<p id=\"p7_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385.474829px;top:189.665441px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">音声<br>デコーダ</font></nobr>");
write("</p>");
write("<p id=\"p7_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385.547237px;top:280.723324px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">映像<br>デコーダ</font></nobr>");
write("</p>");
write("<p id=\"p7_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500.633360px;top:279.998802px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">75Ω<br>ドライバ</font></nobr>");
write("</p>");
write("<p id=\"p7_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670.158210px;top:98.297644px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">外部入力</font></nobr>");
write("</p>");
write("<p id=\"p7_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:683.189753px;top:273.753426px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">NTSC<br>セレクタ<br>回路</font></nobr>");
write("</p>");
write("<p id=\"p7_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:680.090668px;top:401.008411px;font-weight:normal;font-size:6.7pt;color:black;\" prt_font_size=\"8.2pt\" disp_font_size=\"6.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">ディスプレイ</font></nobr>");
write("</p>");
write("<p id=\"p7_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670.718009px;top:520.694278px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.7pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AVNユニット</font></nobr>");
write("</p>");
write("</v:group>");
}