with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:546.07px;\" coordsize=\"950.00,546.07\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:546.07px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/1976_2.0_jpn_9509251_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:546.07px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279.293817px;top:261.647357px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">+B<br>BACK UP</font></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:78.819969px;top:167.803684px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.スライド モータ回転センサ アッセンブリ</font></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:237.981981px;top:136.896825px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ヒューズ<br>ホルダ</font></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208.799493px;top:261.647357px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">EC－</font></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:173.732470px;top:261.647357px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">EC＋</font></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85.224264px;top:188.085858px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.スライド モータ回転センサ </font></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:14.083362px;top:176.428540px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.スライド モータ</font></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:7.404295px;top:30.421905px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">バッテリ</font></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95.882718px;top:295.871541px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B6</font></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:48.714147px;top:34.238104px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.1(100A)</font></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:267.445006px;top:253.115851px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B12</font></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256.356141px;top:261.647357px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">VMP2</font></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231.457593px;top:287.268820px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">SG</font></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:257.998046px;top:287.268820px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">PG2</font></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:286.940350px;top:287.268820px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">PG1</font></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:155.598496px;top:68.672690px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.40(20A)</font></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326.837975px;top:83.082418px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.22<br>(7.5A)</font></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.816629px;top:253.115851px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B2</font></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:157.039606px;top:51.512479px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.1(10A)</font></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218.628827px;top:253.115851px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B1</font></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:181.592287px;top:253.115851px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B11</font></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133.415001px;top:253.115851px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B16</font></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158.434601px;top:253.115851px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B18</font></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112.667813px;top:253.115851px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B14</font></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:101.316665px;top:261.647357px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">SLSE1</font></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:122.092675px;top:261.647357px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">SLSE2</font></nobr>");
write("</p>");
write("<p id=\"p2_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145.150444px;top:261.647357px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">SEGND</font></nobr>");
write("</p>");
write("<p id=\"p2_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:81.021025px;top:261.647357px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">VREF</font></nobr>");
write("</p>");
write("<p id=\"p2_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:48.389479px;top:261.647357px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">SLMCL</font></nobr>");
write("</p>");
write("<p id=\"p2_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:7.437921px;top:261.647357px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">SLMOP</font></nobr>");
write("</p>");
write("<p id=\"p2_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:60.322835px;top:253.115851px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C3</font></nobr>");
write("</p>");
write("<p id=\"p2_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324.572549px;top:253.115851px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A14</font></nobr>");
write("</p>");
write("<p id=\"p2_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317.122969px;top:261.647357px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">IG1</font></nobr>");
write("</p>");
write("<p id=\"p2_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227.293745px;top:261.647357px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">VMP1</font></nobr>");
write("</p>");
write("<p id=\"p2_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:86.992987px;top:287.339073px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">VSP</font></nobr>");
write("</p>");
write("<p id=\"p2_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133.421726px;top:391.045225px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">PGM-FI ECU</font></nobr>");
write("</p>");
write("<p id=\"p2_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74.383270px;top:391.045225px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.パワー <br>スライド ドア<br>コントロール<br>ユニット</font></nobr>");
write("</p>");
write("<p id=\"p2_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238.480606px;top:253.115851px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C2</font></nobr>");
write("</p>");
write("<p id=\"p2_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238.480606px;top:295.872504px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B19</font></nobr>");
write("</p>");
write("<p id=\"p2_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228.215095px;top:527.062348px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">G602</font></nobr>");
write("</p>");
write("<p id=\"p2_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:257.206396px;top:527.062348px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">G602</font></nobr>");
write("</p>");
write("<p id=\"p2_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:285.628939px;top:527.062348px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">G602</font></nobr>");
write("</p>");
write("<p id=\"p2_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.816629px;top:295.872504px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C4</font></nobr>");
write("</p>");
write("<p id=\"p2_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:267.445006px;top:295.872504px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C1</font></nobr>");
write("</p>");
write("<p id=\"p2_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408.990883px;top:45.411948px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">IG1</font></nobr>");
write("</p>");
write("<p id=\"p2_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402.268582px;top:36.077816px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">BAT</font></nobr>");
write("</p>");
write("<p id=\"p2_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:377.930147px;top:23.415772px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">イグニッション スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p2_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:41.510578px;top:17.400893px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">バッテリ ターミナル<br>ヒューズ ボックス</font></nobr>");
write("</p>");
write("<p id=\"p2_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:122.212768px;top:23.415772px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ヒューズ ボックス</font></nobr>");
write("</p>");
write("<p id=\"p2_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:146.471462px;top:34.448506px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.60(IGN)(50A)</font></nobr>");
write("</p>");
write("<p id=\"p2_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91.592051px;top:253.115851px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A13</font></nobr>");
write("</p>");
write("<p id=\"p2_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:237.981981px;top:106.180519px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">T2</font></nobr>");
write("</p>");
write("<p id=\"p2_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:111.164254px;top:36.167318px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">T-9</font></nobr>");
write("</p>");
write("<p id=\"p2_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266.804192px;top:106.180519px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C8</font></nobr>");
write("</p>");
write("<p id=\"p2_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.159483px;top:106.180519px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C37</font></nobr>");
write("</p>");
write("<p id=\"p2_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324.195939px;top:106.180519px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C3</font></nobr>");
write("</p>");
write("<p id=\"p2_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349.748750px;top:63.675048px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">W1</font></nobr>");
write("</p>");
write("<p id=\"p2_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349.748750px;top:36.167318px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">T1</font></nobr>");
write("</p>");
write("<p id=\"p2_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:20.414641px;top:253.115851px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C5</font></nobr>");
write("</p>");
write("<p id=\"p2_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218.628827px;top:216.016073px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p2_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:181.592287px;top:216.016073px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p2_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112.668773px;top:216.016073px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p2_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133.415001px;top:216.016073px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p2_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158.434601px;top:216.016073px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p2_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91.593012px;top:216.016073px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p2_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:586.970917px;top:469.238662px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">(ラッチ ラチェット スイッチ)</font></nobr>");
write("</p>");
write("<p id=\"p2_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:883.915586px;top:373.043893px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">パワー<br>スライド ドア<br>スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p2_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740.128302px;top:82.602190px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">パワー スライド<br>ドア スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p2_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527.645200px;top:483.273061px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.スライド ドア クローザ アッセンブリ</font></nobr>");
write("</p>");
write("<p id=\"p2_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629.731549px;top:90.549530px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.リモート<br>コントロール スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p2_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:763.508879px;top:287.340998px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">REM＋</font></nobr>");
write("</p>");
write("<p id=\"p2_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:730.522819px;top:287.340998px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">CLM－</font></nobr>");
write("</p>");
write("<p id=\"p2_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:703.781572px;top:287.340998px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">CLM＋</font></nobr>");
write("</p>");
write("<p id=\"p2_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:784.162875px;top:412.443761px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.リリース<br>アクチュエータ</font></nobr>");
write("</p>");
write("<p id=\"p2_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:781.308516px;top:116.031448px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">クローズ</font></nobr>");
write("</p>");
write("<p id=\"p2_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:748.135112px;top:116.031448px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">オープン</font></nobr>");
write("</p>");
write("<p id=\"p2_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:755.019777px;top:101.746830px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.スライドドア</font></nobr>");
write("</p>");
write("<p id=\"p2_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:653.742372px;top:274.879130px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.パワー スライド ドア コントロール ユニット</font></nobr>");
write("</p>");
write("<p id=\"p2_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:161.917285px;top:275.078343px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.パワー スライド ドア コントロール ユニット</font></nobr>");
write("</p>");
write("<p id=\"p2_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:905.562988px;top:295.872504px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A10</font></nobr>");
write("</p>");
write("<p id=\"p2_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:895.929644px;top:287.340998px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">MAIN</font></nobr>");
write("</p>");
write("<p id=\"p2_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:554.882189px;top:351.858042px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">*4</font></nobr>");
write("</p>");
write("<p id=\"p2_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714.989569px;top:444.463131px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.<br>クローザ<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p2_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:580.485919px;top:444.463131px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.<br>ラチェット<br>スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p2_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536.024777px;top:395.860016px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B5</font></nobr>");
write("</p>");
write("<p id=\"p2_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742.425432px;top:395.860016px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A2</font></nobr>");
write("</p>");
write("<p id=\"p2_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715.658245px;top:395.860016px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A1</font></nobr>");
write("</p>");
write("<p id=\"p2_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:687.139628px;top:395.860016px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B6</font></nobr>");
write("</p>");
write("<p id=\"p2_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:644.455855px;top:395.860016px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B3</font></nobr>");
write("</p>");
write("<p id=\"p2_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:613.064624px;top:395.860016px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B1</font></nobr>");
write("</p>");
write("<p id=\"p2_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:581.673394px;top:395.860016px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B4</font></nobr>");
write("</p>");
write("<p id=\"p2_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:817.225866px;top:40.317627px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">: CANライン</font></nobr>");
write("</p>");
write("<p id=\"p2_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:678.621704px;top:190.230043px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C12</font></nobr>");
write("</p>");
write("<p id=\"p2_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:658.715164px;top:190.230043px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C14</font></nobr>");
write("</p>");
write("<p id=\"p2_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638.713510px;top:190.230043px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C6</font></nobr>");
write("</p>");
write("<p id=\"p2_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:775.569053px;top:478.686354px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C7</font></nobr>");
write("</p>");
write("<p id=\"p2_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:775.569053px;top:464.402698px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B14</font></nobr>");
write("</p>");
write("<p id=\"p2_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:775.569053px;top:433.055070px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p2_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:775.569053px;top:395.860016px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p2_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:775.569053px;top:358.760237px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B13</font></nobr>");
write("</p>");
write("<p id=\"p2_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:775.569053px;top:344.476582px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C8</font></nobr>");
write("</p>");
write("<p id=\"p2_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742.426392px;top:358.760237px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B6</font></nobr>");
write("</p>");
write("<p id=\"p2_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715.658245px;top:358.760237px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B5</font></nobr>");
write("</p>");
write("<p id=\"p2_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:687.139628px;top:358.760237px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B12</font></nobr>");
write("</p>");
write("<p id=\"p2_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:644.455855px;top:358.760237px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B8</font></nobr>");
write("</p>");
write("<p id=\"p2_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:613.064624px;top:358.760237px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B3</font></nobr>");
write("</p>");
write("<p id=\"p2_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:581.673394px;top:358.760237px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B4</font></nobr>");
write("</p>");
write("<p id=\"p2_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742.426392px;top:344.476582px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C1</font></nobr>");
write("</p>");
write("<p id=\"p2_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715.658245px;top:344.476582px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C2</font></nobr>");
write("</p>");
write("<p id=\"p2_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:687.139628px;top:344.476582px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C9</font></nobr>");
write("</p>");
write("<p id=\"p2_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:644.455855px;top:344.476582px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C13</font></nobr>");
write("</p>");
write("<p id=\"p2_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:613.064624px;top:344.476582px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C4</font></nobr>");
write("</p>");
write("<p id=\"p2_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:581.673394px;top:344.476582px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C3</font></nobr>");
write("</p>");
write("<p id=\"p2_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:857.477933px;top:295.872504px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A7</font></nobr>");
write("</p>");
write("<p id=\"p2_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:775.569053px;top:295.872504px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B10</font></nobr>");
write("</p>");
write("<p id=\"p2_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:743.955891px;top:295.872504px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B9</font></nobr>");
write("</p>");
write("<p id=\"p2_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715.658245px;top:295.872504px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B20</font></nobr>");
write("</p>");
write("<p id=\"p2_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:687.139628px;top:295.872504px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A3</font></nobr>");
write("</p>");
write("<p id=\"p2_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:644.455855px;top:295.872504px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A1</font></nobr>");
write("</p>");
write("<p id=\"p2_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:613.064624px;top:295.872504px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A2</font></nobr>");
write("</p>");
write("<p id=\"p2_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:581.673394px;top:295.872504px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A4</font></nobr>");
write("</p>");
write("<p id=\"p2_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:845.652180px;top:287.340998px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B-CAN</font></nobr>");
write("</p>");
write("<p id=\"p2_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:676.080545px;top:287.340998px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">CLMP</font></nobr>");
write("</p>");
write("<p id=\"p2_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636.049377px;top:287.340998px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">H/L</font></nobr>");
write("</p>");
write("<p id=\"p2_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:604.984799px;top:287.340998px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">F/L</font></nobr>");
write("</p>");
write("<p id=\"p2_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573.439849px;top:287.340998px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">L/P</font></nobr>");
write("</p>");
write("<p id=\"p2_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:786.955748px;top:138.846609px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">9</font></nobr>");
write("</p>");
write("<p id=\"p2_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769.920860px;top:138.846609px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">8</font></nobr>");
write("</p>");
write("<p id=\"p2_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:749.336038px;top:138.846609px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p2_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:698.622396px;top:190.230043px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C11</font></nobr>");
write("</p>");
write("<p id=\"p2_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:541.286752px;top:181.985327px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">*4</font></nobr>");
write("</p>");
write("<p id=\"p2_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593.062010px;top:173.166069px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B2</font></nobr>");
write("</p>");
write("<p id=\"p2_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:561.768775px;top:173.166069px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B11</font></nobr>");
write("</p>");
write("<p id=\"p2_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593.062010px;top:190.230043px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C5</font></nobr>");
write("</p>");
write("<p id=\"p2_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:561.768775px;top:190.230043px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C10</font></nobr>");
write("</p>");
write("<p id=\"p2_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:827.664238px;top:373.043893px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\"> コンビネーション<br> メータ<br> MICU<br> L.パワー<br> スライド ドア<br> コントロール ユニット<br></font></nobr>");
write("</p>");
write("<p id=\"p2_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:764.948068px;top:527.061385px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">G602</font></nobr>");
write("</p>");
write("<p id=\"p2_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:686.407543px;top:444.463131px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.元位置<br>スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p2_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:611.950166px;top:444.463131px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.フル<br>ラッチ<br>スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p2_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:643.174228px;top:444.463131px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.ハーフ<br>ラッチ<br>スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p2_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:598.900430px;top:110.374574px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.スライド<br>ドア<br>タッチ<br>センサ</font></nobr>");
write("</p>");
write("<p id=\"p2_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593.062971px;top:138.846609px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p2_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593.062971px;top:96.090919px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p2_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:698.623358px;top:173.166069px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B10</font></nobr>");
write("</p>");
write("<p id=\"p2_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:698.623358px;top:138.846609px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p2_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:682.640480px;top:114.880441px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">*3</font></nobr>");
write("</p>");
write("<p id=\"p2_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:663.589960px;top:114.880441px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">*2</font></nobr>");
write("</p>");
write("<p id=\"p2_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:643.414413px;top:114.880441px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">*1</font></nobr>");
write("</p>");
write("<p id=\"p2_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:678.621704px;top:138.846609px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p2_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:658.371218px;top:138.846609px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p2_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638.370526px;top:138.846609px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">３</font></nobr>");
write("</p>");
write("<p id=\"p2_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:678.621704px;top:173.166069px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B9</font></nobr>");
write("</p>");
write("<p id=\"p2_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:658.715164px;top:173.166069px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B7</font></nobr>");
write("</p>");
write("<p id=\"p2_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638.713510px;top:173.166069px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B1</font></nobr>");
write("</p>");
write("<p id=\"p2_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:776.957323px;top:261.650244px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">DRCL</font></nobr>");
write("</p>");
write("<p id=\"p2_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:757.142052px;top:261.650244px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">DROP</font></nobr>");
write("</p>");
write("<p id=\"p2_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:686.968616px;top:261.650244px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">SCOM</font></nobr>");
write("</p>");
write("<p id=\"p2_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:786.955748px;top:253.116813px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A9</font></nobr>");
write("</p>");
write("<p id=\"p2_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769.921821px;top:253.116813px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A8</font></nobr>");
write("</p>");
write("<p id=\"p2_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:698.623358px;top:253.116813px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B5</font></nobr>");
write("</p>");
write("<p id=\"p2_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:668.074696px;top:261.650244px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">R/C3</font></nobr>");
write("</p>");
write("<p id=\"p2_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647.899149px;top:261.650244px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">R/C2</font></nobr>");
write("</p>");
write("<p id=\"p2_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:678.621704px;top:253.116813px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A12</font></nobr>");
write("</p>");
write("<p id=\"p2_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:658.715164px;top:253.116813px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A11</font></nobr>");
write("</p>");
write("<p id=\"p2_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638.713510px;top:253.116813px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A5</font></nobr>");
write("</p>");
write("<p id=\"p2_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:628.203971px;top:261.650244px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">R/C1</font></nobr>");
write("</p>");
write("<p id=\"p2_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584.649768px;top:261.650244px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">TSE</font></nobr>");
write("</p>");
write("<p id=\"p2_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593.063932px;top:253.116813px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B13</font></nobr>");
write("</p>");
write("<p id=\"p2_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:550.703929px;top:261.650244px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">FGND</font></nobr>");
write("</p>");
write("<p id=\"p2_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:561.769737px;top:253.116813px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B17</font></nobr>");
write("</p>");
write("<p id=\"p2_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137.824799px;top:84.655910px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.60(PSD MAIN)(60A)</font></nobr>");
write("</p>");
write("<p id=\"p2_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240.601921px;top:157.191511px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.1<br>(40A)</font></nobr>");
write("</p>");
write("<p id=\"p2_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:377.850406px;top:40.622178px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p2_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:97.318052px;top:40.266904px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p2_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:764.457130px;top:212.128054px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p2_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:781.307555px;top:212.128054px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p2_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:707.132635px;top:315.183636px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p2_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:849.012849px;top:315.183636px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p2_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:377.610221px;top:68.172252px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p2_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690.041064px;top:152.379607px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p2_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690.041064px;top:212.128054px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p2_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740.690335px;top:212.128054px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p2_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690.041064px;top:240.037097px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p2_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:672.955257px;top:152.379607px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p2_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652.989151px;top:152.379607px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p2_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:633.077807px;top:152.379607px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p2_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:587.437836px;top:152.379607px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p2_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:672.963904px;top:226.406898px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p2_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652.997798px;top:226.406898px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p2_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:633.086454px;top:226.406898px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p2_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:587.446483px;top:226.406898px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p2_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:587.446483px;top:86.778922px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p2_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:556.447362px;top:86.779960px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p2_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:556.085996px;top:226.406898px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p2_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530.421739px;top:86.778922px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p2_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530.421739px;top:381.267436px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p2_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:900.001261px;top:315.183636px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p2_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:576.000325px;top:381.263622px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p2_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607.413550px;top:381.267436px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p2_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638.774036px;top:381.267436px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p2_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:681.529865px;top:381.267436px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p2_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710.013895px;top:381.267436px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p2_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:736.846412px;top:381.267436px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p2_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769.914135px;top:381.267436px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p2_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:822.112120px;top:373.043893px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">・<br><br>・<br>・</font></nobr>");
write("</p>");
write("<p id=\"p2_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:576.362015px;top:314.823645px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p2_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607.413550px;top:315.183636px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p2_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638.775244px;top:314.823645px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p2_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:681.527005px;top:314.823645px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p2_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:736.851110px;top:314.823645px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p2_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769.916812px;top:314.823645px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p2_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769.914135px;top:498.676927px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p2_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:152.721078px;top:233.541026px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p2_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:107.081107px;top:233.541026px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p2_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85.944819px;top:233.541026px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p2_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:54.704426px;top:233.541026px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p2_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:14.770291px;top:233.541026px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p2_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:175.946015px;top:233.541026px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p2_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:213.002732px;top:233.541026px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p2_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:232.768043px;top:233.541026px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p2_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233.132654px;top:121.104988px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p2_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261.760305px;top:233.541026px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p2_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:290.182848px;top:233.541026px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p2_224\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319.005059px;top:233.541026px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p2_225\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:232.768043px;top:313.899820px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p2_226\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261.760305px;top:313.899820px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p2_227\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:290.182848px;top:313.899820px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p2_228\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769.914135px;top:443.821224px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p2_229\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:90.235486px;top:313.899820px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p2_230\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:90.235486px;top:354.319812px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p2_231\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:149.273942px;top:354.319812px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p2_232\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:127.737025px;top:233.541026px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p2_233\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185.621632px;top:188.182096px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">クラッチ</font></nobr>");
write("</p>");
write("<p id=\"p2_234\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:3.401851px;top:157.537968px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.パワー スライド ドア ドライブ ユニット　</font></nobr>");
write("</p>");
write("<p id=\"p2_235\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:60.084571px;top:216.016073px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p2_236\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19.573993px;top:216.016073px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p2_237\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:810.621406px;top:16.542998px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">*1: リモート コントロール スイッチ1<br>*2: リモート コントロール スイッチ2<br>*3: リモート コントロール スイッチ3<br>*4: CESS Assy</font></nobr>");
write("</p>");
write("</v:group>");
}