with(document) {
write("<v:group id=\"group5\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:1092.14px;\" coordsize=\"950.00,1092.14\">");
write("<v:rect id=\"rect5\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:1092.14px;\">");
write("<img id=\"img5\" name=\"PrtImgId\" src=\"../img/2261_2.0_jpn_9506902_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:1092.14px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p5_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.715494px;top:42.146930px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">イグニッション キー スイッチ<br></font></nobr>");
write("</p>");
write("<p id=\"p5_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.715494px;top:544.611948px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">コンビネーション メータ(PG)</font></nobr>");
write("</p>");
write("<p id=\"p5_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:371.834026px;top:721.009754px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">(内部接続)</font></nobr>");
write("</p>");
write("<p id=\"p5_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165.825375px;top:810.302397px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ヒューズ<br>ボックス</font></nobr>");
write("</p>");
write("<p id=\"p5_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:76.918565px;top:1011.654394px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">インストルメント ワイヤ ハーネス</font></nobr>");
write("</p>");
write("<p id=\"p5_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.715494px;top:145.185330px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">パワー ミラー スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p5_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.715494px;top:303.472028px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ドライバ ドア ロック ノブ スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p5_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.715494px;top:258.175037px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">パワー ウインド マスタ スイッチ(PG1)</font></nobr>");
write("</p>");
write("<p id=\"p5_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.715494px;top:677.467745px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ヘッドライト マニュアル レベリング スイッチ<br>(ディスチャージ ヘッドライト非装備車)</font></nobr>");
write("</p>");
write("<p id=\"p5_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.715494px;top:729.621277px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ブロア モータ リレー</font></nobr>");
write("</p>");
write("<p id=\"p5_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.715494px;top:588.876711px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">コンビネーション メータ(SG) </font></nobr>");
write("</p>");
write("<p id=\"p5_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.715494px;top:635.305886px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ヘッドライト マニュアル レベリング スイッチ照明<br>(ディスチャージ ヘッドライト非装備車)</font></nobr>");
write("</p>");
write("<p id=\"p5_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.715494px;top:272.153382px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">パワー ウインド マスタ スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p5_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309.195924px;top:1011.654394px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ドライバ ドア ワイヤ ハーネス</font></nobr>");
write("</p>");
write("<p id=\"p5_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:55.479116px;top:942.289352px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">G501</font></nobr>");
write("</p>");
write("<p id=\"p5_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69.641994px;top:1010.504910px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">:</font></nobr>");
write("</p>");
write("<p id=\"p5_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:623.088142px;top:212.445547px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ELD</font></nobr>");
write("</p>");
write("<p id=\"p5_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.715494px;top:317.450373px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.パワー ミラー<br>(ドア ミラー サイド ターン シグナル ライト装備車)</font></nobr>");
write("</p>");
write("<p id=\"p5_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622.897818px;top:453.201026px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU(PG)</font></nobr>");
write("</p>");
write("<p id=\"p5_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622.897818px;top:499.191936px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU(SG)</font></nobr>");
write("</p>");
write("<p id=\"p5_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301.919353px;top:1010.314610px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">:</font></nobr>");
write("</p>");
write("<p id=\"p5_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.715494px;top:75.943310px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">パワー スライド ドア スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p5_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.715494px;top:110.274066px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">パワー スライド ドア スイッチ照明</font></nobr>");
write("</p>");
write("<p id=\"p5_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.715494px;top:178.783723px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">パワー ミラー スイッチ照明</font></nobr>");
write("</p>");
write("<p id=\"p5_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.715494px;top:363.310574px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">イルミネーション コントローラ/トリップ/<br>リセット スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p5_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.715494px;top:407.089015px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">イルミネーション コントローラ/トリップ/<br>リセット スイッチ照明</font></nobr>");
write("</p>");
write("<p id=\"p5_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:373.116317px;top:770.987338px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">(内部接続)</font></nobr>");
write("</p>");
write("<p id=\"p5_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.715494px;top:779.593093px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">パワー ウインド リレー(P/W)</font></nobr>");
write("</p>");
write("<p id=\"p5_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279.732061px;top:42.110407px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p5_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.440609px;top:41.658687px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p5_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279.732061px;top:76.608396px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p5_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.440609px;top:76.154753px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p5_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279.732061px;top:111.008352px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p5_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.440609px;top:110.554708px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p5_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279.732061px;top:145.406385px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p5_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.440609px;top:144.952742px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p5_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279.732061px;top:179.243131px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p5_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.440609px;top:178.791411px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p5_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279.732061px;top:213.120245px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p5_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.440609px;top:212.668524px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p5_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172.146476px;top:258.415314px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p5_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:187.855024px;top:257.963593px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p5_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172.146476px;top:303.472028px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p5_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:187.855024px;top:303.020307px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p5_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279.732061px;top:363.237529px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p5_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.440609px;top:362.783887px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p5_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279.732061px;top:408.532598px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p5_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.440609px;top:408.080878px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p5_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279.732061px;top:453.827667px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p5_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.440609px;top:453.374024px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p5_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279.732061px;top:499.122736px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p5_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.440609px;top:498.669093px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p5_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279.732061px;top:544.425494px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p5_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.440609px;top:543.969928px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p5_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279.732061px;top:589.716718px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p5_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.440609px;top:589.263075px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p5_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279.732061px;top:635.017554px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p5_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.440609px;top:634.561989px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p5_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279.732061px;top:680.308779px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p5_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.440609px;top:679.855136px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p5_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:50.797889px;top:1011.039285px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p5_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:458.391571px;top:258.417236px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p5_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:474.100120px;top:257.961671px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AA</font></nobr>");
write("</p>");
write("<p id=\"p5_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:458.391571px;top:303.714227px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p5_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:474.100120px;top:303.258662px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AA</font></nobr>");
write("</p>");
write("<p id=\"p5_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278.991908px;top:1011.039285px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AA</font></nobr>");
write("</p>");
write("<p id=\"p5_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:117.603918px;top:729.580910px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p5_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133.312466px;top:729.127267px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("</v:group>");
}