with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475.00px; height:415.05px;\" coordsize=\"475.00,415.05\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:475.00px;height:415.05px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/238_3.0_jpn_9512508_3.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475.00px;height:415.05px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225.476356px;top:97.533588px;font-weight:normal;font-size:11.2pt;color:black;\" prt_font_size=\"12.3pt\" disp_font_size=\"11.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">IGPLS</font></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167.759041px;top:150.170884px;font-weight:normal;font-size:11.2pt;color:black;\" prt_font_size=\"12.3pt\" disp_font_size=\"11.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">メス端子のコード側</font></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:127.148506px;top:17.120080px;font-weight:normal;font-size:11.2pt;color:black;\" prt_font_size=\"12.3pt\" disp_font_size=\"11.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">イグニッション コイル3Pカプラ</font></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170.237247px;top:192.195379px;font-weight:normal;font-size:11.2pt;color:black;\" prt_font_size=\"12.3pt\" disp_font_size=\"11.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ECUカプラC(49P)</font></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:175.513425px;top:386.117545px;font-weight:normal;font-size:11.2pt;color:black;\" prt_font_size=\"12.3pt\" disp_font_size=\"11.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">メス端子の端子側</font></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:126.580964px;top:214.789047px;font-weight:normal;font-size:11.2pt;color:black;\" prt_font_size=\"12.3pt\" disp_font_size=\"11.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">IGPLS2(白/緑)</font></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:263.382693px;top:216.397174px;font-weight:normal;font-size:11.2pt;color:black;\" prt_font_size=\"12.3pt\" disp_font_size=\"11.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">IGPLS3(白/黒)</font></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282.312963px;top:238.865011px;font-weight:normal;font-size:11.2pt;color:black;\" prt_font_size=\"12.3pt\" disp_font_size=\"11.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">IGPLS4(白/青)</font></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128.412926px;top:237.410038px;font-weight:normal;font-size:11.2pt;color:black;\" prt_font_size=\"12.3pt\" disp_font_size=\"11.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">IGPLS1(白)</font></nobr>");
write("</p>");
write("</v:group>");
}