with(document) {
write("<v:group id=\"group4\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:981.96px;\" coordsize=\"950.00,981.96\">");
write("<v:rect id=\"rect4\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:981.96px;\">");
write("<img id=\"img4\" name=\"PrtImgId\" src=\"../img/2395_2.0_jpn_9507240_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:981.96px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p4_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:263.756749px;top:114.528416px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">8×1.25mm<br>トルク 29N･m<br>(3.0kgf･m)</font></nobr>");
write("</p>");
write("<p id=\"p4_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:160.919919px;top:26.238353px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">フットレスト カーペット</font></nobr>");
write("</p>");
write("<p id=\"p4_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240.690543px;top:59.845960px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">アッパ カバー</font></nobr>");
write("</p>");
write("<p id=\"p4_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389.659782px;top:25.278136px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">クリップ</font></nobr>");
write("</p>");
write("<p id=\"p4_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251.262554px;top:88.652479px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">フット レストAssy.</font></nobr>");
write("</p>");
write("<p id=\"p4_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:3.739113px;top:367.939375px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ロア カバー</font></nobr>");
write("</p>");
write("<p id=\"p4_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:3.739113px;top:393.865244px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">モータ マウント プレート</font></nobr>");
write("</p>");
write("<p id=\"p4_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112.342492px;top:417.870677px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">モータ マウント<br>クッション</font></nobr>");
write("</p>");
write("<p id=\"p4_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:633.590664px;top:52.565592px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">アッパ シャッタ サブAssy.</font></nobr>");
write("</p>");
write("<p id=\"p4_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:581.835867px;top:181.336498px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">シート ブラケット サポート</font></nobr>");
write("</p>");
write("<p id=\"p4_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:656.320486px;top:266.795842px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">シート ブラケット サブAssy.</font></nobr>");
write("</p>");
write("<p id=\"p4_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355.300748px;top:387.954146px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">外スライド モータ<br>ブラケット</font></nobr>");
write("</p>");
write("<p id=\"p4_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:334.721850px;top:430.908508px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">外スライド<br>トラックAssy.</font></nobr>");
write("</p>");
write("<p id=\"p4_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605.019324px;top:375.148687px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">スラスト ワッシャ</font></nobr>");
write("</p>");
write("<p id=\"p4_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:634.403748px;top:399.154121px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ブッシュ</font></nobr>");
write("</p>");
write("<p id=\"p4_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:668.582096px;top:438.523032px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">スラスト ワッシャ</font></nobr>");
write("</p>");
write("<p id=\"p4_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:725.286516px;top:478.852160px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">アッパ アーム ピン</font></nobr>");
write("</p>");
write("<p id=\"p4_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:736.819618px;top:519.181289px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">スライド ガイド サブAssy.</font></nobr>");
write("</p>");
write("<p id=\"p4_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:760.523988px;top:926.952946px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">スラスト ワッシャ</font></nobr>");
write("</p>");
write("<p id=\"p4_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713.430486px;top:957.293894px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">アッパ アーム ピン</font></nobr>");
write("</p>");
write("<p id=\"p4_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298.238802px;top:958.067829px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">トラック マウント スペーサB</font></nobr>");
write("</p>");
write("<p id=\"p4_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316.499548px;top:924.460222px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">トラック スペーサ シール</font></nobr>");
write("</p>");
write("<p id=\"p4_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296.316619px;top:888.932181px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">スラスト プレート</font></nobr>");
write("</p>");
write("<p id=\"p4_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323.227191px;top:837.080444px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">外スライド<br>ブラケット</font></nobr>");
write("</p>");
write("<p id=\"p4_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:542.356136px;top:770.825448px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ピン</font></nobr>");
write("</p>");
write("<p id=\"p4_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:659.611265px;top:787.813612px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ピン</font></nobr>");
write("</p>");
write("<p id=\"p4_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:28.171990px;top:657.519801px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">モータ マウント<br>カラー</font></nobr>");
write("</p>");
write("<p id=\"p4_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:847.983348px;top:742.712205px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ブッシュ</font></nobr>");
write("</p>");
write("<p id=\"p4_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114.297353px;top:907.176310px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">外スライド ロッド<br>サブAssy.</font></nobr>");
write("</p>");
write("<p id=\"p4_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44.510550px;top:723.774797px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">外スライド モータ</font></nobr>");
write("</p>");
write("<p id=\"p4_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:583.984868px;top:306.890677px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">8×1.25mm<br>トルク 13N･m<br>(1.3kgf･m)</font></nobr>");
write("</p>");
write("<p id=\"p4_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:290.025312px;top:173.743100px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">8×1.25mm<br>トルク 25N･m<br>(2.5kgf･m)</font></nobr>");
write("</p>");
write("<p id=\"p4_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:273.844368px;top:669.605097px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">8×1.25mm<br>トルク 25N･m<br>(2.5kgf･m)</font></nobr>");
write("</p>");
write("<p id=\"p4_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:458.374007px;top:812.665958px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">8×1.25mm<br>トルク 5N･m<br>(0.5kgf･m)</font></nobr>");
write("</p>");
write("<p id=\"p4_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:817.822363px;top:867.780513px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">8×1.25mm<br>トルク 13N･m<br>(1.3kgf･m)</font></nobr>");
write("</p>");
write("<p id=\"p4_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:554.483192px;top:925.011388px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">10×1.25mm<br>トルク 20N･m<br>(2.0kgf･m)</font></nobr>");
write("</p>");
write("<p id=\"p4_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460.138572px;top:48.596053px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">6×1.0mm<br>トルク 12N･m<br>(1.2kgf･m)</font></nobr>");
write("</p>");
write("<p id=\"p4_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:9.126993px;top:581.918049px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">6×1.0mm<br>トルク 5N･m<br>(0.5kgf･m)</font></nobr>");
write("</p>");
write("</v:group>");
}