with(document) {
write("<v:group id=\"group100\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475.00px; height:173.71px;\" coordsize=\"475.00,173.71\">");
write("<v:rect id=\"rect100\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:475.00px;height:173.71px;\">");
write("<img id=\"img100\" name=\"PrtImgId\" src=\"../img/2454_2.0_jpn_9507106_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475.00px;height:173.71px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p100_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:61.173761px;top:91.441202px;font-weight:normal;font-size:11.2pt;color:black;\" prt_font_size=\"12.3pt\" disp_font_size=\"11.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">OFF</font></nobr>");
write("</p>");
write("<p id=\"p100_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69.296105px;top:56.156477px;font-weight:normal;font-size:11.2pt;color:black;\" prt_font_size=\"12.3pt\" disp_font_size=\"11.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ON</font></nobr>");
write("</p>");
write("<p id=\"p100_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300.985770px;top:30.029512px;font-weight:normal;font-size:11.2pt;color:black;\" prt_font_size=\"12.3pt\" disp_font_size=\"11.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">断続的に吹鳴</font></nobr>");
write("</p>");
write("<p id=\"p100_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:127.172779px;top:20.552836px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.2pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">0.1[S]</font></nobr>");
write("</p>");
write("<p id=\"p100_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168.029123px;top:20.552836px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.2pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">0.1[S]</font></nobr>");
write("</p>");
write("<p id=\"p100_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208.885469px;top:20.552836px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.2pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">0.1[S]</font></nobr>");
write("</p>");
write("<p id=\"p100_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:147.601946px;top:136.640610px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.2pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">0.1[S]</font></nobr>");
write("</p>");
write("<p id=\"p100_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:188.458290px;top:136.640610px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.2pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">0.1[S]</font></nobr>");
write("</p>");
write("<p id=\"p100_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269.854758px;top:135.025840px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.2pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">0.5[S]</font></nobr>");
write("</p>");
write("</v:group>");
}