with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:546.07px;\" coordsize=\"950.00,546.07\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:546.07px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/2614_2.0_jpn_9507343_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:546.07px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:42.966128px;top:318.531781px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">サブ フレーム マウント用 Ø15（前）</font></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:13.688438px;top:318.536976px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">e1</font></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:42.966128px;top:328.180777px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">フューエル タンク ストラップ 取付け用 Ø11（前）</font></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:13.811654px;top:328.172389px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">k1</font></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:3.355612px;top:42.418135px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">単位: mm　Ø: 穴径を示す。</font></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:42.966128px;top:337.800754px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">フューエル タンク サポート ブラケット ロケート ホール Ø10（内）</font></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:13.473870px;top:337.800754px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">n1</font></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:42.966128px;top:348.436415px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">フューエル タンク サポート ブラケット ロケート ホール Ø8（外）</font></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:13.480510px;top:348.439518px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">n2</font></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:42.974557px;top:358.062406px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">スプリング ベース マウント17</font></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:16.333748px;top:339.513271px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">r</font></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:42.966128px;top:367.705388px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">CBS用 Ø11</font></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:12.779714px;top:367.697819px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">y右, 左</font></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:42.966128px;top:377.325364px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">リヤ デフ マウント用 Ø11（外）</font></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:13.969526px;top:377.333232px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">z1</font></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:42.966128px;top:386.974361px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">リヤ デフ マウント用 Ø11（内）</font></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:13.969526px;top:386.968646px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">z2</font></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:42.966128px;top:396.594337px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">リヤ デフ マウント用 Ø13（後）</font></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:12.779714px;top:396.604059px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">z3右, 左</font></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:33.744853px;top:1.634010px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.5pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">図以外の測定位置および寸法は2WD車を参照する。</font></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:3.355612px;top:14.624673px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.5pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\"> ・ <a title=\"2WD車平面図\" href=\"javascript:CtsProc('0','000000000003704','')\">平面図</a></font></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:3.355612px;top:26.188959px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.5pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\"> ・ <a title=\"2WD車側面図\" href=\"javascript:CtsProc('0','000000000003708','')\">側面図</a></font></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403.211253px;top:323.092600px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">1388</font></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167.219207px;top:180.950153px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">中心線</font></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168.661566px;top:464.072017px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">基準線</font></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281.288795px;top:520.573057px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">基準線</font></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400.000879px;top:315.930597px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">1345</font></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:560.968756px;top:337.503304px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">2318</font></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442.369145px;top:330.335478px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">1923</font></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:618.605137px;top:351.541505px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">2975</font></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:587.895209px;top:344.373679px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">2588</font></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345.905035px;top:403.087459px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">e1</font></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:543.414013px;top:42.534213px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">k1</font></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:486.495187px;top:41.917548px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">y右</font></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:489.887268px;top:311.472779px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">y左</font></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:617.735373px;top:44.137543px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">n1</font></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:683.409826px;top:47.910083px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">z1</font></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:683.409826px;top:311.211603px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">z2</font></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838.039423px;top:99.165841px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">z3右</font></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834.777807px;top:307.177887px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">z3左</font></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:628.375490px;top:320.882364px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">n2</font></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726.840057px;top:49.099884px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">r</font></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:524.670592px;top:424.039565px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">k1</font></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:498.048556px;top:422.595843px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">y</font></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:592.468720px;top:421.558395px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">n</font></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:641.211761px;top:415.616644px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">z1, z2</font></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:814.664508px;top:377.390658px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">z3</font></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:664.840358px;top:392.916111px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">r</font></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292.443523px;top:136.637319px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">e1</font></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:303.619994px;top:309.100431px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">65</font></nobr>");
write("</p>");
write("<v:line id=\"bl1_1\" from=\"617,194\" to=\"616,186\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_1\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"73\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.7pt;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_2\" from=\"617,212\" to=\"616,204\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_2\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"24\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.7pt;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_3\" from=\"278,496\" to=\"277,488\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_3\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"55\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.7pt;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_4\" from=\"282,511\" to=\"281,503\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_4\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"e1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.7pt;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_5\" from=\"678,496\" to=\"677,492\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_5\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"7\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.7pt;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_6\" from=\"681,522\" to=\"680,503\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_6\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"z1, z2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.7pt;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_7\" from=\"500,496\" to=\"499,492\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_7\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"7\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.7pt;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_8\" from=\"502,508\" to=\"501,505\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_8\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"y\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.7pt;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_9\" from=\"522,496\" to=\"521,492\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_9\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"5\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.7pt;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_10\" from=\"525,511\" to=\"524,504\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_10\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"k1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.7pt;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_11\" from=\"592,496\" to=\"591,484\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_11\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"107\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.7pt;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_12\" from=\"594,510\" to=\"593,506\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_12\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"n\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.7pt;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_13\" from=\"717,496\" to=\"716,488\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_13\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"80\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.7pt;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_14\" from=\"720,509\" to=\"719,507\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_14\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"r\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.7pt;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_15\" from=\"782,496\" to=\"781,488\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_15\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"34\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.7pt;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_16\" from=\"785,511\" to=\"784,504\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_16\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"z3\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.7pt;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_17\" from=\"543,183\" to=\"542,171\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_17\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"451\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.7pt;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_18\" from=\"528,182\" to=\"527,174\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_18\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"76\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.7pt;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_19\" from=\"528,194\" to=\"527,186\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_19\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"77\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.7pt;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_20\" from=\"846,212\" to=\"845,200\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_20\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"282\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.7pt;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_21\" from=\"845,181\" to=\"844,173\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_21\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"98\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.7pt;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_22\" from=\"676,182\" to=\"675,174\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_22\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"76\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.7pt;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_23\" from=\"676,170\" to=\"675,158\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_23\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"102\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.7pt;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_24\" from=\"690,184\" to=\"689,172\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_24\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"917\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.7pt;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\"/>");
write("</v:line>");
write("<v:line id=\"bl1_25\" from=\"323,184\" to=\"322,172\" strokecolor=\"black\">");
write("<v:fill on=\"true\" color=\"black\"/>");
write("<v:path textpathok=\"true\"/>");
write("<v:textpath id=\"tp1_25\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"854\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.7pt;\" prt_font_size=\"4.7pt\" disp_font_size=\"3.7pt\"/>");
write("</v:line>");
write("</v:group>");
}