with(document) {
write("<v:group id=\"group9\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:495.14px;\" coordsize=\"950.00,495.14\">");
write("<v:rect id=\"rect9\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:495.14px;\">");
write("<img id=\"img9\" name=\"PrtImgId\" src=\"../img/2640_2.0_jpn_9507046_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:495.14px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p9_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:8.967894px;top:16.772469px;font-weight:normal;font-size:9.0pt;color:black;\" prt_font_size=\"10.2pt\" disp_font_size=\"9.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">9</font></nobr>");
write("</p>");
write("<p id=\"p9_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:933.351122px;top:16.772469px;font-weight:normal;font-size:9.0pt;color:black;\" prt_font_size=\"10.2pt\" disp_font_size=\"9.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">9</font></nobr>");
write("</p>");
write("<p id=\"p9_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:20.364119px;top:12.187802px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">インテリア ライト、フロント ポジション ライト、テール ライト、ライセンス プレート ライト、バック ライト、ブレーキ ライト、ターン シグナル/ハザード ライト、ホーン、アクセサリ ソケット、センタ トレイ ライト</font></nobr>");
write("</p>");
write("<p id=\"p9_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:448.622223px;top:384.969162px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p9_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:473.651334px;top:384.969162px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p9_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:473.651334px;top:355.316922px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p9_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:448.622223px;top:355.316922px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:496.403228px;top:369.001947px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ハザード<br>スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p9_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:477.626494px;top:369.001947px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">照明<br>(1.12W)</font></nobr>");
write("</p>");
write("<p id=\"p9_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:735.560377px;top:122.671492px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ブレーキ<br>スイッチ<br>(ON:ブレーキ<br>ペダルを踏む)</font></nobr>");
write("</p>");
write("<p id=\"p9_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726.459620px;top:143.326832px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p9_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124.604430px;top:133.934353px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">OFF</font></nobr>");
write("</p>");
write("<p id=\"p9_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:106.016957px;top:133.289254px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ON</font></nobr>");
write("</p>");
write("<p id=\"p9_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124.918062px;top:117.323391px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(8W)</font></nobr>");
write("</p>");
write("<p id=\"p9_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:120.367683px;top:99.988214px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p9_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:126.010369px;top:157.375656px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">インテリア<br>ライト</font></nobr>");
write("</p>");
write("<p id=\"p9_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:120.380526px;top:156.905017px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176.931082px;top:133.934353px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">OFF</font></nobr>");
write("</p>");
write("<p id=\"p9_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158.342933px;top:133.289254px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ON</font></nobr>");
write("</p>");
write("<p id=\"p9_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177.244715px;top:117.323391px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(8W)</font></nobr>");
write("</p>");
write("<p id=\"p9_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172.693660px;top:99.988214px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p9_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:178.337022px;top:157.375656px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">カーゴ<br>エリア<br>ライト</font></nobr>");
write("</p>");
write("<p id=\"p9_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172.706503px;top:156.905017px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726.459620px;top:113.673239px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180.396589px;top:403.385590px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">10</font></nobr>");
write("</p>");
write("<p id=\"p9_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180.396589px;top:327.715609px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">9</font></nobr>");
write("</p>");
write("<p id=\"p9_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:147.260341px;top:403.259816px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.ドア ミラー<br>サイド ターン <br>シグナル ライト<br>(LED)</font></nobr>");
write("</p>");
write("<p id=\"p9_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346.584102px;top:403.167175px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">10</font></nobr>");
write("</p>");
write("<p id=\"p9_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346.584102px;top:327.497871px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">9</font></nobr>");
write("</p>");
write("<p id=\"p9_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313.448530px;top:403.042078px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.ドア ミラー<br>サイド ターン <br>シグナル ライト<br>(LED)</font></nobr>");
write("</p>");
write("<p id=\"p9_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:614.622502px;top:116.830438px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.バック<br>ライト<br>(16W)<br></font></nobr>");
write("</p>");
write("<p id=\"p9_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:610.072123px;top:115.006039px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p9_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:610.072123px;top:128.691064px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p9_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:580.508856px;top:116.867629px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.バック<br>ライト<br>(16W)<br></font></nobr>");
write("</p>");
write("<p id=\"p9_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:575.959153px;top:115.043230px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p9_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:575.959153px;top:128.728255px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p9_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424.416398px;top:134.610557px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ライセンス<br>プレート<br>ライト<br>(5W)<br></font></nobr>");
write("</p>");
write("<p id=\"p9_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:422.599491px;top:115.104088px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:422.599491px;top:128.789789px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p9_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394.655758px;top:134.610557px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.<br>テールライト<br>(5W)<br></font></nobr>");
write("</p>");
write("<p id=\"p9_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:392.838850px;top:115.104088px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p9_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:392.838850px;top:128.789789px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p9_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364.892414px;top:134.610557px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.<br>テールライト<br>(5W)<br></font></nobr>");
write("</p>");
write("<p id=\"p9_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363.076183px;top:115.104088px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p9_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363.076183px;top:128.789789px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p9_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335.482583px;top:134.945955px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.<br>フロント<br>ポジション<br>ライト<br>(5W)<br></font></nobr>");
write("</p>");
write("<p id=\"p9_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333.667028px;top:115.440162px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333.667028px;top:129.125187px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p9_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:305.720591px;top:134.945955px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.<br>フロント<br>ポジション<br>ライト<br>(5W)<br></font></nobr>");
write("</p>");
write("<p id=\"p9_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:303.904360px;top:115.440162px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:303.904360px;top:129.125187px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p9_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:741.597808px;top:366.676480px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p9_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:741.597808px;top:341.586591px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:747.991455px;top:351.562635px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">アクセサリ<br>ソケット</font></nobr>");
write("</p>");
write("<p id=\"p9_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:522.876807px;top:457.685482px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(セキュリティ アラーム システム装備車)</font></nobr>");
write("</p>");
write("<p id=\"p9_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578.276250px;top:408.850674px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ホーン</font></nobr>");
write("</p>");
write("<p id=\"p9_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:542.215917px;top:407.876263px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ホーン<br>スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p9_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:542.018545px;top:352.463339px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ケーブル<br>リール</font></nobr>");
write("</p>");
write("<p id=\"p9_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638.070607px;top:352.463339px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ケーブル<br>リール</font></nobr>");
write("</p>");
write("<p id=\"p9_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537.482361px;top:401.847224px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573.762372px;top:401.847224px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537.257275px;top:366.221394px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">11</font></nobr>");
write("</p>");
write("<p id=\"p9_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537.257275px;top:341.488541px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:634.599017px;top:134.020907px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">AVNユニット*<sup>2</sup><br><sup></sup>(20-A)</font></nobr>");
write("</p>");
write("<p id=\"p9_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:639.033804px;top:122.465912px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">113</font></nobr>");
write("</p>");
write("<p id=\"p9_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:716.856644px;top:213.892146px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">PGM-FI ECU<br>(BKSW)(4-C)<br>MICU<br>(11-C)</font></nobr>");
write("</p>");
write("<p id=\"p9_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714.749762px;top:213.892146px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">･<br><br>･</font></nobr>");
write("</p>");
write("<p id=\"p9_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720.783813px;top:202.145123px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">114</font></nobr>");
write("</p>");
write("<p id=\"p9_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567.792820px;top:41.380020px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(11-C)</font></nobr>");
write("</p>");
write("<p id=\"p9_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:712.567175px;top:36.985571px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.24(10A)*<sup>1</sup><br><sup></sup>ヒューズ<br>(2-D)</font></nobr>");
write("</p>");
write("<p id=\"p9_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722.124188px;top:51.078348px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">84</font></nobr>");
write("</p>");
write("<p id=\"p9_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354.395179px;top:40.818974px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(11-B)</font></nobr>");
write("</p>");
write("<p id=\"p9_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:357.388210px;top:51.078348px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">162</font></nobr>");
write("</p>");
write("<p id=\"p9_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570.530900px;top:50.885694px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">154</font></nobr>");
write("</p>");
write("<p id=\"p9_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324.985348px;top:41.226725px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(12-B)</font></nobr>");
write("</p>");
write("<p id=\"p9_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328.168315px;top:51.486099px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">161</font></nobr>");
write("</p>");
write("<p id=\"p9_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.223357px;top:41.226725px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(12-B)</font></nobr>");
write("</p>");
write("<p id=\"p9_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298.214359px;top:51.486099px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">160</font></nobr>");
write("</p>");
write("<p id=\"p9_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:108.390832px;top:36.577144px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.1(10A)*<sup>1</sup><br><sup></sup>ヒューズ<br>(1-C)</font></nobr>");
write("</p>");
write("<p id=\"p9_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116.025492px;top:50.670596px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">15</font></nobr>");
write("</p>");
write("<p id=\"p9_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:727.704688px;top:280.503016px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.13(20A)*<sup>1</sup><br><sup></sup>ヒューズ<br>(2-D)</font></nobr>");
write("</p>");
write("<p id=\"p9_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:737.450285px;top:294.595116px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">77</font></nobr>");
write("</p>");
write("<p id=\"p9_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:533.328754px;top:294.595116px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">95</font></nobr>");
write("</p>");
write("<p id=\"p9_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570.213725px;top:294.595116px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">94</font></nobr>");
write("</p>");
write("<p id=\"p9_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467.966064px;top:294.810149px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">163</font></nobr>");
write("</p>");
write("<p id=\"p9_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442.936953px;top:294.810149px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">120</font></nobr>");
write("</p>");
write("<p id=\"p9_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340.265483px;top:294.711423px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">130</font></nobr>");
write("</p>");
write("<p id=\"p9_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271.953698px;top:295.001515px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">128</font></nobr>");
write("</p>");
write("<p id=\"p9_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230.389246px;top:294.810149px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">124</font></nobr>");
write("</p>");
write("<p id=\"p9_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:174.076619px;top:294.929161px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">125</font></nobr>");
write("</p>");
write("<p id=\"p9_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114.686469px;top:295.001515px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">123</font></nobr>");
write("</p>");
write("<p id=\"p9_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114.697284px;top:244.949539px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">112</font></nobr>");
write("</p>");
write("<p id=\"p9_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278.765072px;top:377.930550px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.<br>リヤ<br>ターン<br>シグナル<br>ライト<br>(21W)<br></font></nobr>");
write("</p>");
write("<p id=\"p9_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:277.624097px;top:358.930558px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:277.624097px;top:372.615583px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p9_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:237.203323px;top:377.930550px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.<br>フロント<br>ターン<br>シグナル<br>ライト<br>(21W)<br></font></nobr>");
write("</p>");
write("<p id=\"p9_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:236.061673px;top:358.930558px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:236.061673px;top:372.615583px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p9_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:122.303555px;top:378.155050px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.<br>リヤ<br>ターン<br>シグナル<br>ライト<br>(21W)<br></font></nobr>");
write("</p>");
write("<p id=\"p9_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:120.373091px;top:358.967749px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:120.373091px;top:372.652775px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p9_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:396.031957px;top:295.001515px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">129</font></nobr>");
write("</p>");
write("<p id=\"p9_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:406.253411px;top:360.754958px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.<br>フロント<br>ターン<br>シグナル<br>ライト<br>(21W)<br></font></nobr>");
write("</p>");
write("<p id=\"p9_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401.702356px;top:358.930558px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401.702356px;top:372.615583px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p9_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:733.915833px;top:453.261076px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G502</font></nobr>");
write("</p>");
write("<p id=\"p9_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:465.965303px;top:453.261076px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G502</font></nobr>");
write("</p>");
write("<p id=\"p9_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394.029168px;top:453.261076px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G202</font></nobr>");
write("</p>");
write("<p id=\"p9_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:338.263370px;top:453.261752px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G501</font></nobr>");
write("</p>");
write("<p id=\"p9_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269.951585px;top:453.261076px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G602</font></nobr>");
write("</p>");
write("<p id=\"p9_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228.388485px;top:453.261076px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G401</font></nobr>");
write("</p>");
write("<p id=\"p9_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172.075857px;top:453.261076px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G502</font></nobr>");
write("</p>");
write("<p id=\"p9_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112.683681px;top:453.261076px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G701</font></nobr>");
write("</p>");
write("<p id=\"p9_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442.936953px;top:446.260331px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">115</font></nobr>");
write("</p>");
write("<p id=\"p9_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:614.977367px;top:457.685482px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(セキュリティ アラーム システム非装備車)</font></nobr>");
write("</p>");
write("<p id=\"p9_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674.208671px;top:408.850674px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ホーン</font></nobr>");
write("</p>");
write("<p id=\"p9_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638.148339px;top:407.876263px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ホーン<br>スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p9_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:633.414783px;top:401.847224px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:669.694117px;top:401.847224px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:633.189697px;top:366.221394px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">11</font></nobr>");
write("</p>");
write("<p id=\"p9_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:633.189697px;top:341.488541px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:665.060836px;top:294.596504px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">153</font></nobr>");
write("</p>");
write("<p id=\"p9_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:628.127287px;top:294.341933px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">152</font></nobr>");
write("</p>");
write("<p id=\"p9_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568.276502px;top:225.304448px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G701</font></nobr>");
write("</p>");
write("<p id=\"p9_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602.406371px;top:225.304448px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G602</font></nobr>");
write("</p>");
write("<p id=\"p9_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:794.407076px;top:116.750646px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.<br>ブレーキ<br>ライト<br>(21W)<br></font></nobr>");
write("</p>");
write("<p id=\"p9_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:789.857373px;top:114.926246px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p9_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:789.857373px;top:128.611272px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p9_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:782.193649px;top:225.224656px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G701</font></nobr>");
write("</p>");
write("<p id=\"p9_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:827.001226px;top:116.750646px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.<br>ブレーキ<br>ライト<br>(21W)<br></font></nobr>");
write("</p>");
write("<p id=\"p9_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:822.451523px;top:114.926246px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p9_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:822.451523px;top:128.611272px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p9_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:814.787798px;top:225.224656px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G602</font></nobr>");
write("</p>");
write("<p id=\"p9_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:859.595376px;top:116.830438px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ハイ<br>マウント<br>ブレーキ<br>ライト<br>(21W)<br></font></nobr>");
write("</p>");
write("<p id=\"p9_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:855.044997px;top:115.006039px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p9_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:855.044997px;top:128.691064px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:847.381272px;top:225.304448px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G602</font></nobr>");
write("</p>");
write("<p id=\"p9_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:414.913460px;top:225.304448px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G602</font></nobr>");
write("</p>");
write("<p id=\"p9_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355.386773px;top:225.304448px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G701</font></nobr>");
write("</p>");
write("<p id=\"p9_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325.975590px;top:225.304448px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G202</font></nobr>");
write("</p>");
write("<p id=\"p9_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385.151468px;top:225.304448px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G602</font></nobr>");
write("</p>");
write("<p id=\"p9_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296.213598px;top:225.304448px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G401</font></nobr>");
write("</p>");
write("<p id=\"p9_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722.244503px;top:72.482923px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p9_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:848.631748px;top:103.057506px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p9_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:816.037598px;top:103.057506px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p9_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783.446828px;top:103.057506px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p9_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742.552901px;top:169.325540px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p9_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720.134918px;top:155.069799px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p9_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720.134918px;top:185.780299px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p9_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:799.763843px;top:86.733931px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p9_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:444.225957px;top:317.027522px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p9_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:785.480709px;top:169.325540px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605.702894px;top:169.325540px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:737.206949px;top:400.587456px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571.566942px;top:169.325540px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:418.211336px;top:169.325540px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388.447992px;top:169.325540px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358.683297px;top:169.325540px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:329.272789px;top:169.325540px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299.510122px;top:169.325540px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:818.073507px;top:169.325540px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:850.669009px;top:169.325540px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:115.980880px;top:317.220240px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p9_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:175.373057px;top:317.220240px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p9_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231.673518px;top:317.220240px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p9_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571.570998px;top:72.482247px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p9_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:589.102664px;top:86.733255px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p9_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571.482451px;top:103.056830px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p9_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605.688024px;top:103.056830px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p9_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:639.821272px;top:103.056830px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p9_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299.506742px;top:72.482923px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p9_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:329.268734px;top:72.482923px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p9_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358.680593px;top:72.482923px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p9_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:469.254392px;top:317.220240px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p9_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:531.361791px;top:317.220240px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p9_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666.099507px;top:317.220240px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p9_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388.443936px;top:103.057506px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p9_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358.767788px;top:103.057506px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p9_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:418.205928px;top:103.057506px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p9_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116.322226px;top:69.698313px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p9_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116.073483px;top:91.562707px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p9_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168.395404px;top:91.562707px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p9_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116.076863px;top:174.961028px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p9_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116.076863px;top:221.393958px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p9_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168.143957px;top:174.961028px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p9_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:273.214313px;top:317.030227px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p9_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341.537588px;top:317.030227px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p9_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397.291895px;top:317.030227px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p9_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112.723561px;top:284.387134px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(11-C)</font></nobr>");
write("</p>");
write("<p id=\"p9_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228.291827px;top:284.387134px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(11-C)</font></nobr>");
write("</p>");
write("<p id=\"p9_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171.867670px;top:284.387134px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(11-C)</font></nobr>");
write("</p>");
write("<p id=\"p9_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269.446664px;top:284.387134px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(11-C)</font></nobr>");
write("</p>");
write("<p id=\"p9_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337.832801px;top:284.387134px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(11-C)</font></nobr>");
write("</p>");
write("<p id=\"p9_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:392.881434px;top:284.387134px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(11-C)</font></nobr>");
write("</p>");
write("<p id=\"p9_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:440.347455px;top:284.387134px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(11-B)</font></nobr>");
write("</p>");
write("<p id=\"p9_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:440.347455px;top:456.819264px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(11-B)</font></nobr>");
write("</p>");
write("<p id=\"p9_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464.681031px;top:284.387134px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(12-C)</font></nobr>");
write("</p>");
write("<p id=\"p9_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528.894636px;top:284.387134px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ホーン リレー　<br>(3-C)</font></nobr>");
write("</p>");
write("<p id=\"p9_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:566.746866px;top:284.387134px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ホーン リレー<br>(3-C)</font></nobr>");
write("</p>");
write("<p id=\"p9_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624.730399px;top:284.387134px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(11-B)</font></nobr>");
write("</p>");
write("<p id=\"p9_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:662.053374px;top:284.387134px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(11-B)</font></nobr>");
write("</p>");
write("<p id=\"p9_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112.885109px;top:256.122465px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(11-B)</font></nobr>");
write("</p>");
write("<p id=\"p9_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:533.282791px;top:383.457169px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p9_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629.213861px;top:383.457169px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p9_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629.129369px;top:317.219564px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p9_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570.167085px;top:317.220240px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p9_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:737.212357px;top:317.220240px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p9_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:822.590089px;top:366.676480px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:822.590089px;top:341.586591px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p9_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:846.549875px;top:351.562635px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">センタ トレイ<br>ライト</font></nobr>");
write("</p>");
write("<p id=\"p9_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:808.696293px;top:280.503016px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.13(20A)*<sup>1</sup><br><sup></sup>ヒューズ<br>(12-C)</font></nobr>");
write("</p>");
write("<p id=\"p9_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:816.910227px;top:294.403750px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">163</font></nobr>");
write("</p>");
write("<p id=\"p9_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:814.907439px;top:453.261076px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G502</font></nobr>");
write("</p>");
write("<p id=\"p9_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:818.199231px;top:400.587456px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:818.203962px;top:317.220240px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p9_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:469.175308px;top:418.487263px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397.239849px;top:418.487263px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341.556514px;top:418.487263px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:273.249461px;top:418.487263px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231.769500px;top:418.487263px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:115.982232px;top:418.487263px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:175.366974px;top:418.487263px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:444.144845px;top:418.487263px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p9_224\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:828.603187px;top:36.729966px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ヒューズ ボックス<br> NAV.装備車</font></nobr>");
write("</p>");
write("<p id=\"p9_225\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:822.662414px;top:36.729966px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*1:<br>*2:</font></nobr>");
write("</p>");
write("<p id=\"p9_226\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:827.331757px;top:352.989426px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">照明<br>(1.4W)</font></nobr>");
write("</p>");
write("<p id=\"p9_227\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:587.383767px;top:22.042129px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C</font></nobr>");
write("</p>");
write("<p id=\"p9_228\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132.327636px;top:22.042129px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A</font></nobr>");
write("</p>");
write("<p id=\"p9_229\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359.856039px;top:22.042129px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B</font></nobr>");
write("</p>");
write("<p id=\"p9_230\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:814.912846px;top:22.042129px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">D</font></nobr>");
write("</p>");
write("</v:group>");
}