with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:1092.14px;\" coordsize=\"950.00,1092.14\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:1092.14px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/2885_2.0_jpn_9509823_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:1092.14px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745.084894px;top:136.407920px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">リヤ ロア サッシュ</font></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519.343953px;top:277.506654px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">インナ <br>ハンドル</font></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168.611346px;top:92.186940px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ガラス ランチャンネル</font></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593.765476px;top:19.444935px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ガラス<br><font style=\"font-weight:normal;\"><a title=\"スライド ドア ガラスの脱着\" href=\"javascript:CtsProc('0','000000000001388','')\">脱着</a><a title=\"スライド ドア ガラスの建付け調整\" href=\"javascript:CtsProc('0','000000000001309','')\"><br>建付け調整</a></font></font></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:583.353124px;top:543.250973px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">レギュレータ<br><font style=\"font-weight:normal;\"><a title=\"スライド ドア ガラス レギュレータの脱着\" href=\"javascript:CtsProc('0','000000000001386','')\">脱着</a></font></font></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:635.096284px;top:697.421844px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">リヤ ストライカ<font style=\"font-weight:normal;\"><a title=\"スライド ドア ストライカの調整\" href=\"javascript:CtsProc('0','000000000001394','')\"><br>調整</a></font></font></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491.061167px;top:993.193580px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">リヤ ラッチ<font style=\"font-weight:normal;\"><a title=\"スライド ドア リヤ ラッチの脱着\" href=\"javascript:CtsProc('0','000000000001390','')\"><br>脱着</a></font></font></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:101.126564px;top:395.540850px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">アウタ ハンドル<font style=\"font-weight:normal;\"><a title=\"スライド ドア アウタ ハンドルの脱着\" href=\"javascript:CtsProc('0','000000000001391','')\"><br>脱着</a></font></font></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17.668452px;top:812.744534px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">フロント ストライカ<br><font style=\"font-weight:normal;\"><a title=\"スライド ドア ストライカの調整\" href=\"javascript:CtsProc('0','000000000001394','')\">調整</a></font><br></font></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:23.388728px;top:1043.975734px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">フロント ラッチ<font style=\"font-weight:normal;\"><a title=\"スライド ドア フロント ラッチの脱着\" href=\"javascript:CtsProc('0','000000000001389','')\"><br>脱着</a></font></font></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491.046685px;top:815.991646px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">リヤ ラッチ<br>(イージ ドア クローザ装備車)<font style=\"font-weight:normal;\"><a title=\"スライド ドア リヤ ラッチの脱着\" href=\"javascript:CtsProc('0','000000000001390','')\"><br>脱着</a></font><br></font></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:356.569499px;top:1011.621778px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">オープン <br>ケーブル</font></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:93.480219px;top:708.820211px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">アウタ ハンドル ケーブル</font></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450.700633px;top:699.949235px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">リヤ ラッチ ケーブル</font></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225.987893px;top:573.730308px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">オート クローザ ケーブル<br>(イージ ドア クローザ装備車)</font></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218.573256px;top:984.155227px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">フロント ラッチ <br>ケーブル</font></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516.143494px;top:588.710541px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">リモート コントロール<font style=\"font-weight:normal;\"><a title=\"スライド ドア リモート コントロールの脱着\" href=\"javascript:CtsProc('0','000000000001400','')\"><br>脱着</a></font></font></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95.073207px;top:231.695594px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">リモート コントロール<br>(パワー スライド ドア)<font style=\"font-weight:normal;\"><a title=\"スライド ドア リモート コントロールの脱着\" href=\"javascript:CtsProc('0','000000000001400','')\"><br>脱着</a></font></font></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:42.794224px;top:474.459063px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">アウタ ハンドル <br>ブラケット</font></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528.467432px;top:957.692938px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">イージ ドア クローザ非装備車</font></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:413.004734px;top:438.004372px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">マニュアル スライド ドア</font></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536.273075px;top:391.456854px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">リテーナ <br>クリップ</font></nobr>");
write("</p>");
write("</v:group>");
}