with(document) {
write("<v:group id=\"group8\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:493.10px;\" coordsize=\"950.00,493.10\">");
write("<v:rect id=\"rect8\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:493.10px;\">");
write("<img id=\"img8\" name=\"PrtImgId\" src=\"../img/2934_2.0_jpn_9507979_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:493.10px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p8_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19.140800px;top:10.934837px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">コンビネーション メータ</font></nobr>");
write("</p>");
write("<p id=\"p8_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:49.952322px;top:161.301035px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">コンビネーション メータ</font></nobr>");
write("</p>");
write("<p id=\"p8_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690.759513px;top:196.586392px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">シート ベルト<br>警告灯<br>(LED)</font></nobr>");
write("</p>");
write("<p id=\"p8_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:579.691731px;top:248.658828px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ライトON<br>インジケータ<br>(LED)</font></nobr>");
write("</p>");
write("<p id=\"p8_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609.593605px;top:248.658828px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">フォグ ライト<br>インジケータ<br>(LED)</font></nobr>");
write("</p>");
write("<p id=\"p8_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408.931957px;top:284.470135px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">13</font></nobr>");
write("</p>");
write("<p id=\"p8_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:436.024287px;top:284.470135px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">17</font></nobr>");
write("</p>");
write("<p id=\"p8_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278.548893px;top:284.178391px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">23</font></nobr>");
write("</p>");
write("<p id=\"p8_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407.410008px;top:196.142346px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">EPS<br>警告灯<br>(LED)</font></nobr>");
write("</p>");
write("<p id=\"p8_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513.372790px;top:194.223340px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">VSA<br>警告灯<br>(LED)</font></nobr>");
write("</p>");
write("<p id=\"p8_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:457.886989px;top:196.142346px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ABS<br>警告灯<br>(LED)</font></nobr>");
write("</p>");
write("<p id=\"p8_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:432.900463px;top:196.142346px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">SRS<br>警告灯<br>(LED)</font></nobr>");
write("</p>");
write("<p id=\"p8_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380.594027px;top:193.767787px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">PGM-FI<br>警告灯<br>(LED)</font></nobr>");
write("</p>");
write("<p id=\"p8_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:290.116252px;top:232.688765px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">CPU/メイン パワー供給回路/<br>コントローラ エリア ネットワーク コントローラ</font></nobr>");
write("</p>");
write("<p id=\"p8_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:698.661866px;top:233.456368px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">CPU/メイン パワー供給回路/<br>コントローラ エリア ネットワーク コントローラ</font></nobr>");
write("</p>");
write("<p id=\"p8_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:748.951228px;top:349.495697px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p8_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715.834769px;top:365.479298px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p8_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715.834769px;top:347.211165px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p8_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:868.299311px;top:123.868557px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU(11-C)</font></nobr>");
write("</p>");
write("<p id=\"p8_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:577.858211px;top:267.381836px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">点灯回路</font></nobr>");
write("</p>");
write("<p id=\"p8_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:894.843007px;top:161.361956px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">9</font></nobr>");
write("</p>");
write("<p id=\"p8_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:866.283591px;top:161.361956px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">10</font></nobr>");
write("</p>");
write("<p id=\"p8_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:895.034013px;top:214.866031px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.ターン<br>シグナル<br>インジケータ<br>(LED)</font></nobr>");
write("</p>");
write("<p id=\"p8_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:866.475274px;top:214.866031px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.ターン<br>シグナル<br>インジケータ<br>(LED)</font></nobr>");
write("</p>");
write("<p id=\"p8_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:833.200321px;top:223.105915px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ターン<br>シグナル<br>ハザード<br>リレー<br>(音用)</font></nobr>");
write("</p>");
write("<p id=\"p8_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:753.422929px;top:350.591595px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">パーキング<br>ブレーキ<br>スイッチ<br>(ON：<br>ペダルを踏む)<br>(OFF：<br>ペダル解除)</font></nobr>");
write("</p>");
write("<p id=\"p8_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:748.951228px;top:284.189898px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">20</font></nobr>");
write("</p>");
write("<p id=\"p8_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720.393844px;top:350.591595px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ブレーキ<br>フルード<br>レベル<br>スイッチ<br>(ON：<br>フロート<br>ダウン)<br>(OFF：<br>フロート<br>アップ)</font></nobr>");
write("</p>");
write("<p id=\"p8_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715.834769px;top:284.189898px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">19</font></nobr>");
write("</p>");
write("<p id=\"p8_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:614.299660px;top:193.337280px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">オート ライト<br>コントロール<br>警告灯 (LED)</font></nobr>");
write("</p>");
write("<p id=\"p8_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:799.300873px;top:196.574884px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ブレーキ<br>警告灯<br>(LED)</font></nobr>");
write("</p>");
write("<p id=\"p8_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722.864727px;top:196.438151px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">充電<br>警告灯<br>(LED)</font></nobr>");
write("</p>");
write("<p id=\"p8_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:672.588233px;top:196.503810px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">油圧<br>警告灯<br>(LED)</font></nobr>");
write("</p>");
write("<p id=\"p8_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:572.497182px;top:189.313796px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">助手席サイド<br>エアバッグ<br>自動停止<br>表示灯(LED)</font></nobr>");
write("</p>");
write("<p id=\"p8_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:770.753649px;top:196.427321px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ドア<br>インジケータ<br>(LED)</font></nobr>");
write("</p>");
write("<p id=\"p8_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:743.278630px;top:186.562204px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">パワー<br>スライド<br>ドア<br>インジケータ<br>(LED)</font></nobr>");
write("</p>");
write("<p id=\"p8_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:651.784868px;top:196.635806px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">燃料残量<br>警告灯<br>(LED)</font></nobr>");
write("</p>");
write("<p id=\"p8_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535.990710px;top:194.223340px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">VSA作動<br>表示灯<br>(LED)</font></nobr>");
write("</p>");
write("<p id=\"p8_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:587.153145px;top:218.112436px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">点灯回路</font></nobr>");
write("</p>");
write("<p id=\"p8_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332.902206px;top:351.370705px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">熱線入り<br>フロント<br>ウインド/<br>VSA OFF<br>スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p8_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558.981836px;top:248.712979px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">低水温<br>表示灯<br>(LED)</font></nobr>");
write("</p>");
write("<p id=\"p8_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:478.838012px;top:196.237789px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">高水温<br>警告灯<br>(LED)</font></nobr>");
write("</p>");
write("<p id=\"p8_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279.282436px;top:210.542682px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">強制点灯回路</font></nobr>");
write("</p>");
write("<p id=\"p8_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:302.514012px;top:179.540061px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">強制消灯回路</font></nobr>");
write("</p>");
write("<p id=\"p8_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258.747291px;top:176.958370px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">フェイル<br>セーフ回路</font></nobr>");
write("</p>");
write("<p id=\"p8_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330.854652px;top:193.312234px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">シフト ポジション<br>インジケータ<br>点灯回路(6-A)</font></nobr>");
write("</p>");
write("<p id=\"p8_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638.805285px;top:172.201806px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*3</font></nobr>");
write("</p>");
write("<p id=\"p8_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:595.027050px;top:172.201806px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*2</font></nobr>");
write("</p>");
write("<p id=\"p8_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551.316547px;top:172.201806px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*1</font></nobr>");
write("</p>");
write("<p id=\"p8_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331.642382px;top:442.479869px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(VSA装備車)</font></nobr>");
write("</p>");
write("<p id=\"p8_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:122.745137px;top:213.223876px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(LED)</font></nobr>");
write("</p>");
write("<p id=\"p8_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105.469281px;top:184.241120px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">指針用<br>調光回路(赤)</font></nobr>");
write("</p>");
write("<p id=\"p8_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:156.609363px;top:213.223876px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(LED)</font></nobr>");
write("</p>");
write("<p id=\"p8_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:139.719583px;top:184.241120px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">文字盤用<br>調光回路(白)</font></nobr>");
write("</p>");
write("<p id=\"p8_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:189.797620px;top:213.223876px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(LED)</font></nobr>");
write("</p>");
write("<p id=\"p8_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172.715479px;top:184.241120px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">LCD用<br>調光回路(白)</font></nobr>");
write("</p>");
write("<p id=\"p8_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:222.986554px;top:213.223876px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(LED)</font></nobr>");
write("</p>");
write("<p id=\"p8_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:205.904413px;top:184.241120px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">LCD用<br>調光回路(橙)</font></nobr>");
write("</p>");
write("<p id=\"p8_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:525.257138px;top:225.368786px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">減光回路<br>(6-D)</font></nobr>");
write("</p>");
write("<p id=\"p8_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:58.896402px;top:173.838546px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B</font></nobr>");
write("</p>");
write("<p id=\"p8_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:58.704719px;top:168.380715px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A</font></nobr>");
write("</p>");
write("<p id=\"p8_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:860.597447px;top:132.571438px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">134</font></nobr>");
write("</p>");
write("<p id=\"p8_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:775.182678px;top:298.976066px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">180</font></nobr>");
write("</p>");
write("<p id=\"p8_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530.378394px;top:236.835444px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B</font></nobr>");
write("</p>");
write("<p id=\"p8_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:889.350578px;top:132.571438px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">135</font></nobr>");
write("</p>");
write("<p id=\"p8_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:708.136291px;top:430.186718px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G301</font></nobr>");
write("</p>");
write("<p id=\"p8_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401.617523px;top:432.558570px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G501</font></nobr>");
write("</p>");
write("<p id=\"p8_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:428.710530px;top:432.558570px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G501</font></nobr>");
write("</p>");
write("<p id=\"p8_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:270.847705px;top:432.459742px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G501</font></nobr>");
write("</p>");
write("<p id=\"p8_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:293.646471px;top:432.459742px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G501</font></nobr>");
write("</p>");
write("<p id=\"p8_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:210.702584px;top:382.519537px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p8_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167.141093px;top:336.313102px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p8_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:210.787927px;top:336.313102px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p8_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167.141093px;top:284.178391px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">24</font></nobr>");
write("</p>");
write("<p id=\"p8_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:215.726305px;top:355.892386px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">照明<br>(1.12W×2)</font></nobr>");
write("</p>");
write("<p id=\"p8_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:305.841033px;top:355.892386px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">照明<br>(1.12W×2)</font></nobr>");
write("</p>");
write("<p id=\"p8_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170.279140px;top:353.635607px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">トリップ/<br>リセット<br>スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p8_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143.206453px;top:382.753743px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">イルミネーション コントローラ/<br>トリップ/リセット スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p8_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:202.546912px;top:285.293243px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(12-C)</font></nobr>");
write("</p>");
write("<p id=\"p8_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137.224317px;top:382.519537px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p8_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137.224317px;top:336.313102px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p8_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137.224317px;top:284.178391px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">21</font></nobr>");
write("</p>");
write("<p id=\"p8_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140.362365px;top:355.553937px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">VOL.</font></nobr>");
write("</p>");
write("<p id=\"p8_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129.519743px;top:432.459742px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G501</font></nobr>");
write("</p>");
write("<p id=\"p8_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:107.307541px;top:336.313102px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p8_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:107.307541px;top:284.178391px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">22</font></nobr>");
write("</p>");
write("<p id=\"p8_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:203.352251px;top:432.459742px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G501</font></nobr>");
write("</p>");
write("<p id=\"p8_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:205.272469px;top:296.632644px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">175</font></nobr>");
write("</p>");
write("<p id=\"p8_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322.059584px;top:198.168980px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">C</font></nobr>");
write("</p>");
write("<p id=\"p8_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:890.809536px;top:152.448558px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p8_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132.820349px;top:310.859693px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p8_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:744.644118px;top:303.728569px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p8_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761.342215px;top:324.590576px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p8_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:744.644118px;top:338.814918px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p8_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:432.010458px;top:303.789490px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:405.005503px;top:303.789490px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:206.652857px;top:400.832344px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132.820349px;top:400.832344px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711.525625px;top:387.778360px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:162.736447px;top:310.860370px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p8_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:862.080789px;top:152.448558px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p8_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:206.652857px;top:320.087172px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p8_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300.993417px;top:382.519537px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p8_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278.550247px;top:336.225105px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">10</font></nobr>");
write("</p>");
write("<p id=\"p8_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301.082824px;top:336.313102px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p8_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292.838422px;top:285.293243px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(12-C)</font></nobr>");
write("</p>");
write("<p id=\"p8_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.566010px;top:296.632644px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">175</font></nobr>");
write("</p>");
write("<p id=\"p8_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296.947076px;top:400.832344px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278.195329px;top:382.519537px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">11</font></nobr>");
write("</p>");
write("<p id=\"p8_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:274.148311px;top:400.832344px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:274.148311px;top:310.772373px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p8_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296.947076px;top:320.087172px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p8_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711.436896px;top:303.789490px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p8_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:102.903573px;top:310.859016px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p8_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:142.077352px;top:360.337577px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">－</font></nobr>");
write("</p>");
write("<p id=\"p8_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:110.446266px;top:355.462556px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">VOL.</font></nobr>");
write("</p>");
write("<p id=\"p8_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112.161254px;top:360.315240px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">＋</font></nobr>");
write("</p>");
write("<p id=\"p8_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:587.312994px;top:20.799953px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C</font></nobr>");
write("</p>");
write("<p id=\"p8_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131.329556px;top:20.799953px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A</font></nobr>");
write("</p>");
write("<p id=\"p8_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359.321952px;top:20.799953px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B</font></nobr>");
write("</p>");
write("<p id=\"p8_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815.305390px;top:20.799953px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">D</font></nobr>");
write("</p>");
write("<p id=\"p8_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:757.360221px;top:288.569431px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">・スマートECU*<sup>4</sup>(17-B)</font></nobr>");
write("</p>");
write("<p id=\"p8_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:757.360221px;top:293.142556px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">・AVNユニット*<sup>5</sup>(20-A)</font></nobr>");
write("</p>");
write("<p id=\"p8_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:839.957317px;top:35.081832px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*1：VSA装備車</font></nobr>");
write("</p>");
write("<p id=\"p8_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:839.957317px;top:39.255587px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*2：サイド エア バッグ装備車</font></nobr>");
write("</p>");
write("<p id=\"p8_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:839.957317px;top:43.430019px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*3：ディスチャージ ヘッドライト装備車</font></nobr>");
write("</p>");
write("<p id=\"p8_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:839.957317px;top:47.604451px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*4：Hondaスマート キー システム装備車</font></nobr>");
write("</p>");
write("<p id=\"p8_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:839.957317px;top:51.778206px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*5：NAV.装備車</font></nobr>");
write("</p>");
write("<p id=\"p8_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:8.680868px;top:15.966899px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.2pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p8_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:934.108903px;top:16.014282px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.2pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("</v:group>");
}