with(document) {
write("<v:group id=\"group8\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:1092.14px;\" coordsize=\"950.00,1092.14\">");
write("<v:rect id=\"rect8\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:1092.14px;\">");
write("<img id=\"img8\" name=\"PrtImgId\" src=\"../img/2953_2.0_jpn_9508681_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:1092.14px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p8_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91.221785px;top:986.977000px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">フロア ワイヤ ハーネス</font></nobr>");
write("</p>");
write("<p id=\"p8_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:90.941103px;top:1015.619924px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">テールゲート ワイヤ ハーネス</font></nobr>");
write("</p>");
write("<p id=\"p8_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312.858240px;top:1015.619924px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">リヤ ワイヤ ハーネス</font></nobr>");
write("</p>");
write("<p id=\"p8_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.741251px;top:164.688120px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ハイ マウント ストップ ランプ</font></nobr>");
write("</p>");
write("<p id=\"p8_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83.945213px;top:987.271100px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">:</font></nobr>");
write("</p>");
write("<p id=\"p8_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83.474207px;top:1015.912100px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">:</font></nobr>");
write("</p>");
write("<p id=\"p8_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:302.682575px;top:1015.285457px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">:</font></nobr>");
write("</p>");
write("<p id=\"p8_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52.418535px;top:533.140170px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">G602</font></nobr>");
write("</p>");
write("<p id=\"p8_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.741251px;top:201.060269px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ライセンス プレート ライト</font></nobr>");
write("</p>");
write("<p id=\"p8_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.741251px;top:216.328421px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">リヤ デフロスタ</font></nobr>");
write("</p>");
write("<p id=\"p8_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.741251px;top:258.703646px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">テールゲート ハンドル スイッチ<br>(Hondaスマート キー システム装備車)</font></nobr>");
write("</p>");
write("<p id=\"p8_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.741251px;top:287.292746px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">テールゲート ラッチ スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p8_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.741251px;top:301.463314px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">リヤ ワイパ モータ</font></nobr>");
write("</p>");
write("<p id=\"p8_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.741251px;top:315.631959px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">テールゲート ロック ボタン<br>(Hondaスマート キー システム装備車)</font></nobr>");
write("</p>");
write("<p id=\"p8_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.741251px;top:230.116468px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">テールゲート リリース アクチュエータ<br>(Hondaスマート キー システム装備車)</font></nobr>");
write("</p>");
write("<p id=\"p8_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.741251px;top:361.578658px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.パワー スライド ドア コントロール ユニット<br>(PG1)</font></nobr>");
write("</p>");
write("<p id=\"p8_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.741251px;top:391.372988px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.パワー スライド ドア コントロール ユニット<br>(PG2)</font></nobr>");
write("</p>");
write("<p id=\"p8_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.741251px;top:421.167316px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.パワー スライド ドア コントロール ユニット<br>(SG)</font></nobr>");
write("</p>");
write("<p id=\"p8_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.741251px;top:450.525302px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.リリース アクチュエータ<br>(両側パワー スライド ドア装備車)</font></nobr>");
write("</p>");
write("<p id=\"p8_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52.076334px;top:929.472024px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">G701</font></nobr>");
write("</p>");
write("<p id=\"p8_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.741251px;top:564.706782px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.コンビネーション ライト</font></nobr>");
write("</p>");
write("<p id=\"p8_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.741251px;top:579.494381px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">フューエル リッド スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p8_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.741251px;top:614.286467px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.パワー スライド ドア コントロール ユニット<br>(PG1)</font></nobr>");
write("</p>");
write("<p id=\"p8_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.741251px;top:649.122766px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.パワー スライド ドア コントロール ユニット<br>(PG2)</font></nobr>");
write("</p>");
write("<p id=\"p8_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.741251px;top:686.563665px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.パワー スライド ドア コントロール ユニット<br>(SG)</font></nobr>");
write("</p>");
write("<p id=\"p8_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.741251px;top:725.004116px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.リリース アクチュエータ<br>(L.パワー スライド ドア装備車)</font></nobr>");
write("</p>");
write("<p id=\"p8_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.741251px;top:775.008612px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">RFユニット(Hondaスマート キー システム装備車)</font></nobr>");
write("</p>");
write("<p id=\"p8_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.741251px;top:819.425227px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">アンサ バック ブザー<br>(Hondaスマート キー システム装備車)</font></nobr>");
write("</p>");
write("<p id=\"p8_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:302.682575px;top:986.504136px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">:</font></nobr>");
write("</p>");
write("<p id=\"p8_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:524.257512px;top:986.313836px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">:</font></nobr>");
write("</p>");
write("<p id=\"p8_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:82.960906px;top:1046.475315px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">:</font></nobr>");
write("</p>");
write("<p id=\"p8_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312.858240px;top:987.617098px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.CESS Assy.</font></nobr>");
write("</p>");
write("<p id=\"p8_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:533.942944px;top:986.977000px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.CESS Assy.</font></nobr>");
write("</p>");
write("<p id=\"p8_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91.483241px;top:1047.144245px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">リヤ パネル サブ ハーネス</font></nobr>");
write("</p>");
write("<p id=\"p8_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:524.313263px;top:1016.298465px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">:</font></nobr>");
write("</p>");
write("<p id=\"p8_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:302.342298px;top:1044.941387px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">:</font></nobr>");
write("</p>");
write("<p id=\"p8_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:524.169078px;top:1045.514207px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">:</font></nobr>");
write("</p>");
write("<p id=\"p8_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:533.942944px;top:1015.619924px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">テールゲート サブ ハーネス</font></nobr>");
write("</p>");
write("<p id=\"p8_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312.858240px;top:1047.144245px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.スライド ドア ハーネス</font></nobr>");
write("</p>");
write("<p id=\"p8_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:533.942944px;top:1047.144245px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.スライド ドア ハーネス </font></nobr>");
write("</p>");
write("<p id=\"p8_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.493252px;top:36.330307px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.スライド ドア クローザ コントロール ユニット</font></nobr>");
write("</p>");
write("<p id=\"p8_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.741251px;top:84.883531px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.スライド ドア ロック ノブ スイッチ<br>(セキュリティ アラーム システム装備車)</font></nobr>");
write("</p>");
write("<p id=\"p8_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.741251px;top:128.542794px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.コンビネーション ライト</font></nobr>");
write("</p>");
write("<p id=\"p8_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.744502px;top:51.019094px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">(L.パワー スライド ドア装備および<br>イージ ドア クローザ装備車)</font></nobr>");
write("</p>");
write("<p id=\"p8_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:65.258750px;top:987.476777px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">S</font></nobr>");
write("</p>");
write("<p id=\"p8_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:377.547624px;top:35.832454px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">U</font></nobr>");
write("</p>");
write("<p id=\"p8_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:377.547624px;top:451.036612px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">U</font></nobr>");
write("</p>");
write("<p id=\"p8_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283.569322px;top:987.476777px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">U</font></nobr>");
write("</p>");
write("<p id=\"p8_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:65.575959px;top:1046.104327px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Z</font></nobr>");
write("</p>");
write("<p id=\"p8_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283.996112px;top:1016.113932px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">X</font></nobr>");
write("</p>");
write("<p id=\"p8_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506.061279px;top:1016.309998px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Y</font></nobr>");
write("</p>");
write("<p id=\"p8_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506.061279px;top:987.476777px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">V</font></nobr>");
write("</p>");
write("<p id=\"p8_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:484.587225px;top:725.442381px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">V</font></nobr>");
write("</p>");
write("<p id=\"p8_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279.491751px;top:1046.104327px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AC</font></nobr>");
write("</p>");
write("<p id=\"p8_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:501.560763px;top:1046.104327px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AD</font></nobr>");
write("</p>");
write("<p id=\"p8_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296.223057px;top:360.942405px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312.998580px;top:360.488763px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">S</font></nobr>");
write("</p>");
write("<p id=\"p8_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296.223057px;top:389.712193px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312.998580px;top:389.258551px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">S</font></nobr>");
write("</p>");
write("<p id=\"p8_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296.223057px;top:420.467630px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312.998580px;top:420.013988px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">S</font></nobr>");
write("</p>");
write("<p id=\"p8_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219.131781px;top:450.980867px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235.907304px;top:450.525302px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">S</font></nobr>");
write("</p>");
write("<p id=\"p8_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370.838183px;top:725.896024px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387.613706px;top:725.442381px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">S</font></nobr>");
write("</p>");
write("<p id=\"p8_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165.475485px;top:164.028802px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:182.251008px;top:163.575159px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">S</font></nobr>");
write("</p>");
write("<p id=\"p8_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219.131781px;top:36.399507px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235.907304px;top:35.943943px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">S</font></nobr>");
write("</p>");
write("<p id=\"p8_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363.926883px;top:128.342885px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380.700484px;top:127.889242px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">S</font></nobr>");
write("</p>");
write("<p id=\"p8_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:306.417946px;top:163.711637px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219.131781px;top:819.513649px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235.907304px;top:819.060007px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">X</font></nobr>");
write("</p>");
write("<p id=\"p8_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219.131781px;top:647.490805px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235.907304px;top:647.037163px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">X</font></nobr>");
write("</p>");
write("<p id=\"p8_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266.653458px;top:687.303717px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283.428982px;top:686.850075px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">X</font></nobr>");
write("</p>");
write("<p id=\"p8_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266.653458px;top:725.880646px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283.428982px;top:725.427003px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">X</font></nobr>");
write("</p>");
write("<p id=\"p8_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:296.223057px;top:774.856757px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312.998580px;top:774.401191px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">X</font></nobr>");
write("</p>");
write("<p id=\"p8_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165.475485px;top:687.582439px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:182.251008px;top:687.128797px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">X</font></nobr>");
write("</p>");
write("<p id=\"p8_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219.131781px;top:614.922720px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235.907304px;top:614.467155px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">X</font></nobr>");
write("</p>");
write("<p id=\"p8_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219.131781px;top:565.008570px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235.907304px;top:564.553004px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">X</font></nobr>");
write("</p>");
write("<p id=\"p8_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370.838183px;top:819.513649px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387.932837px;top:819.060007px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Z</font></nobr>");
write("</p>");
write("<p id=\"p8_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:563.760542px;top:725.896024px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:579.044224px;top:725.442381px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AD</font></nobr>");
write("</p>");
write("<p id=\"p8_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512.743805px;top:36.399507px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528.027487px;top:35.943943px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AC</font></nobr>");
write("</p>");
write("<p id=\"p8_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512.993726px;top:450.744434px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528.277408px;top:450.290792px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AC</font></nobr>");
write("</p>");
write("<p id=\"p8_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321.699706px;top:163.256071px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">W</font></nobr>");
write("</p>");
write("<p id=\"p8_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:411.039073px;top:163.461748px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:426.320833px;top:163.008106px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">W</font></nobr>");
write("</p>");
write("<p id=\"p8_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:411.039073px;top:202.332775px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:426.320833px;top:201.879132px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">W</font></nobr>");
write("</p>");
write("<p id=\"p8_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527.491116px;top:202.232820px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p8_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:63.764986px;top:1016.113932px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">W</font></nobr>");
write("</p>");
write("<p id=\"p8_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:544.264716px;top:201.777256px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Y</font></nobr>");
write("</p>");
write("</v:group>");
}