with(document) {
write("<v:group id=\"group7\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:1092.14px;\" coordsize=\"950.00,1092.14\">");
write("<v:rect id=\"rect7\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:1092.14px;\">");
write("<img id=\"img7\" name=\"PrtImgId\" src=\"../img/3393_2.0_jpn_9505360_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:1092.14px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p7_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568.065315px;top:254.961017px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AG</font></nobr>");
write("</p>");
write("<p id=\"p7_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:612.415116px;top:243.008347px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AE</font></nobr>");
write("</p>");
write("<p id=\"p7_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460.607369px;top:135.060611px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">5V</font></nobr>");
write("</p>");
write("<p id=\"p7_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:707.464968px;top:849.252412px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">クラッチ プレッシャ<br>コントロールSOL.V.</font></nobr>");
write("</p>");
write("<p id=\"p7_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:707.464968px;top:761.885230px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ドリブン プーリ<br>コントロールSOL.V.</font></nobr>");
write("</p>");
write("<p id=\"p7_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:707.464968px;top:674.518047px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ドライブ プーリ<br>コントロールSOL.V.</font></nobr>");
write("</p>");
write("<p id=\"p7_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607.059436px;top:980.587315px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">G101</font></nobr>");
write("</p>");
write("<p id=\"p7_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:614.715904px;top:935.802845px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p7_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:614.436962px;top:853.975692px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p7_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690.126339px;top:898.945085px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p7_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652.609647px;top:908.580422px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p7_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690.126339px;top:877.098957px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p7_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521.572473px;top:878.543678px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B48</font></nobr>");
write("</p>");
write("<p id=\"p7_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521.572473px;top:894.926831px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">CPCLS</font></nobr>");
write("</p>");
write("<p id=\"p7_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652.609647px;top:886.740070px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p7_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690.126339px;top:811.574051px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p7_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652.609647px;top:821.213239px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p7_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690.126339px;top:789.733700px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p7_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521.572473px;top:791.178423px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B26</font></nobr>");
write("</p>");
write("<p id=\"p7_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521.572473px;top:807.559649px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">DNLS</font></nobr>");
write("</p>");
write("<p id=\"p7_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652.759699px;top:799.132102px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p7_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690.126339px;top:724.208794px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p7_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652.609647px;top:733.846057px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p7_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:653.252176px;top:625.813565px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p7_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652.609647px;top:597.558646px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p7_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690.126339px;top:702.364592px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p7_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690.126339px;top:590.652874px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p7_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689.806999px;top:617.929233px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p7_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521.572473px;top:703.809315px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B40</font></nobr>");
write("</p>");
write("<p id=\"p7_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521.572473px;top:720.190540px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">DRLS</font></nobr>");
write("</p>");
write("<p id=\"p7_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652.759699px;top:711.279493px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p7_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:205.631604px;top:678.596018px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p7_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:135.063211px;top:526.981065px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p7_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:135.063211px;top:548.821415px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p7_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:135.063211px;top:614.348248px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p7_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:135.063211px;top:636.192452px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p7_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:58.717839px;top:586.501703px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">シフト コントロール<br>SOL.V.B</font></nobr>");
write("</p>");
write("<p id=\"p7_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:58.717839px;top:499.130668px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">シフト コントロール<br>SOL.V.A</font></nobr>");
write("</p>");
write("<p id=\"p7_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197.278744px;top:727.712729px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">G101</font></nobr>");
write("</p>");
write("<p id=\"p7_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167.458918px;top:645.831639px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p7_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321.721353px;top:614.348248px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B27</font></nobr>");
write("</p>");
write("<p id=\"p7_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:311.440910px;top:630.731401px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">SOLB</font></nobr>");
write("</p>");
write("<p id=\"p7_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167.458918px;top:623.989362px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p7_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167.458918px;top:558.458678px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p7_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321.721353px;top:526.981065px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B21</font></nobr>");
write("</p>");
write("<p id=\"p7_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:311.440910px;top:543.360364px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">SOLA</font></nobr>");
write("</p>");
write("<p id=\"p7_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167.458918px;top:536.618328px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p7_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:49.732070px;top:58.014526px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">*2</font></nobr>");
write("</p>");
write("<p id=\"p7_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660.766286px;top:96.835182px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">トルク コンバータ タービン スピード センサ</font></nobr>");
write("</p>");
write("<p id=\"p7_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:700.545291px;top:245.551059px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">セカンダリ ギヤ スピード センサ</font></nobr>");
write("</p>");
write("<p id=\"p7_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690.276391px;top:200.587444px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p7_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652.748157px;top:209.903013px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p7_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690.276391px;top:156.902889px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p7_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690.276391px;top:113.216409px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p7_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:646.334422px;top:122.539683px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">薄茶</font></nobr>");
write("</p>");
write("<p id=\"p7_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521.884119px;top:157.866038px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B49</font></nobr>");
write("</p>");
write("<p id=\"p7_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521.884119px;top:174.243411px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">NTDD</font></nobr>");
write("</p>");
write("<p id=\"p7_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:646.653763px;top:166.378342px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p7_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690.170586px;top:352.002061px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p7_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652.642352px;top:361.961014px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p7_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690.170586px;top:308.317507px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p7_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690.170586px;top:264.632952px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p7_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652.803945px;top:273.952376px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p7_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521.778313px;top:310.003017px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B38</font></nobr>");
write("</p>");
write("<p id=\"p7_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521.778313px;top:326.384242px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">VELDD</font></nobr>");
write("</p>");
write("<p id=\"p7_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652.642352px;top:317.796812px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p7_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568.432749px;top:410.170440px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AP</font></nobr>");
write("</p>");
write("<p id=\"p7_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:611.355138px;top:562.667636px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AQ</font></nobr>");
write("</p>");
write("<p id=\"p7_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:612.582481px;top:399.745322px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AO</font></nobr>");
write("</p>");
write("<p id=\"p7_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:707.239891px;top:402.236024px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ドリブン プーリ油圧センサ</font></nobr>");
write("</p>");
write("<p id=\"p7_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705.635496px;top:555.376604px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">トランスミッション<br>フルード温度センサ</font></nobr>");
write("</p>");
write("<p id=\"p7_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690.174433px;top:507.696910px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p7_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652.488452px;top:517.657789px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p7_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690.174433px;top:464.012356px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p7_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690.174433px;top:420.327801px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p7_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:646.555651px;top:429.801328px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">薄茶</font></nobr>");
write("</p>");
write("<p id=\"p7_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521.784084px;top:465.697866px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">C39</font></nobr>");
write("</p>");
write("<p id=\"p7_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521.784084px;top:482.079091px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">PDN</font></nobr>");
write("</p>");
write("<p id=\"p7_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521.383947px;top:589.782187px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B28</font></nobr>");
write("</p>");
write("<p id=\"p7_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521.383947px;top:606.163412px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">TATF</font></nobr>");
write("</p>");
write("<p id=\"p7_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:653.127132px;top:473.651544px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p7_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249.567802px;top:356.422912px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">薄茶</font></nobr>");
write("</p>");
write("<p id=\"p7_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254.709947px;top:378.265190px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p7_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:200.785714px;top:92.712908px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">24Pジャンクション カプラ</font></nobr>");
write("</p>");
write("<p id=\"p7_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:239.962590px;top:130.612794px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">15</font></nobr>");
write("</p>");
write("<p id=\"p7_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261.773903px;top:130.612794px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">13</font></nobr>");
write("</p>");
write("<p id=\"p7_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:283.587142px;top:130.612794px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">16</font></nobr>");
write("</p>");
write("<p id=\"p7_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:159.763976px;top:370.230606px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">10</font></nobr>");
write("</p>");
write("<p id=\"p7_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:161.368371px;top:349.033637px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p7_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254.709947px;top:307.279233px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p7_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254.709947px;top:290.896081px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p7_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254.858075px;top:273.713515px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p7_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:305.402304px;top:130.612794px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">17</font></nobr>");
write("</p>");
write("<p id=\"p7_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:275.872962px;top:148.284638px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p7_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:232.898632px;top:148.926095px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p7_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254.709947px;top:165.307321px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p7_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298.324880px;top:164.665864px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p7_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131.844801px;top:307.317759px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">L</font></nobr>");
write("</p>");
write("<p id=\"p7_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130.882932px;top:290.936532px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">D</font></nobr>");
write("</p>");
write("<p id=\"p7_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130.882932px;top:274.555307px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">N</font></nobr>");
write("</p>");
write("<p id=\"p7_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131.215739px;top:241.794781px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">P</font></nobr>");
write("</p>");
write("<p id=\"p7_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130.882932px;top:258.176006px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">R</font></nobr>");
write("</p>");
write("<p id=\"p7_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:293.594414px;top:364.449790px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ATPFWD</font></nobr>");
write("</p>");
write("<p id=\"p7_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321.721353px;top:348.070490px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B29</font></nobr>");
write("</p>");
write("<p id=\"p7_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386.537776px;top:161.129184px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">12V</font></nobr>");
write("</p>");
write("<p id=\"p7_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:53.264049px;top:199.350761px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">シフト ポジション センサ</font></nobr>");
write("</p>");
write("<p id=\"p7_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:162.330239px;top:299.566341px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p7_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:162.330239px;top:283.185116px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">8</font></nobr>");
write("</p>");
write("<p id=\"p7_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:162.330239px;top:266.803889px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p7_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:162.330239px;top:250.420736px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p7_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:162.330239px;top:234.039510px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p7_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:162.330239px;top:217.658284px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p7_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313.430052px;top:331.689264px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ATPL</font></nobr>");
write("</p>");
write("<p id=\"p7_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321.721353px;top:315.308037px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B17</font></nobr>");
write("</p>");
write("<p id=\"p7_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:311.506317px;top:298.924885px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ATPD</font></nobr>");
write("</p>");
write("<p id=\"p7_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321.721353px;top:282.543658px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B22</font></nobr>");
write("</p>");
write("<p id=\"p7_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:311.506317px;top:266.162431px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ATPN</font></nobr>");
write("</p>");
write("<p id=\"p7_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321.721353px;top:249.779280px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B13</font></nobr>");
write("</p>");
write("<p id=\"p7_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:311.506317px;top:233.398053px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ATPR</font></nobr>");
write("</p>");
write("<p id=\"p7_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321.721353px;top:217.016828px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B15</font></nobr>");
write("</p>");
write("<p id=\"p7_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312.168081px;top:200.635601px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ATPP</font></nobr>");
write("</p>");
write("<p id=\"p7_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321.721353px;top:184.256300px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B14</font></nobr>");
write("</p>");
write("<p id=\"p7_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118.378651px;top:165.307321px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p7_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133.099077px;top:155.668133px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">11</font></nobr>");
write("</p>");
write("<p id=\"p7_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:148.500504px;top:130.620498px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">13P<br>カプラ</font></nobr>");
write("</p>");
write("<p id=\"p7_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172.589521px;top:165.307321px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p7_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401.173557px;top:16.903505px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">PGM-FI ECU</font></nobr>");
write("</p>");
write("<p id=\"p7_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68.388459px;top:1041.820431px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">*2: CVT車</font></nobr>");
write("</p>");
write("<p id=\"p7_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.437353px;top:421.920849px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">G101</font></nobr>");
write("</p>");
write("<p id=\"p7_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568.948309px;top:104.024120px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AJ</font></nobr>");
write("</p>");
write("<p id=\"p7_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:96.573108px;top:124.073016px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">W</font></nobr>");
write("</p>");
write("<p id=\"p7_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:614.258055px;top:92.865085px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AI</font></nobr>");
write("</p>");
write("</v:group>");
}