with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:1092.14px;\" coordsize=\"950.00,1092.14\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:1092.14px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/3654_2.0_jpn_9505155_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:1092.14px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:25.729008px;top:112.328298px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">カウンタシャフト<br>スピード センサ</font></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:35.316031px;top:242.319904px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">メインシャフト<br>スピード センサ</font></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:46.135878px;top:783.266260px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">アクセル<br>ペダル<br>ポジション<br>センサ</font></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624.162476px;top:773.100899px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624.162476px;top:802.347552px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624.162476px;top:831.751891px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:729.996695px;top:339.554683px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:729.996695px;top:415.993272px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624.162476px;top:743.061976px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:729.877265px;top:492.045341px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:708.716970px;top:884.345487px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">G101</font></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:655.428087px;top:560.586237px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">G101</font></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:620.311823px;top:242.209419px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">G502</font></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185.644515px;top:210.874404px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185.644515px;top:240.586421px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185.644515px;top:270.823411px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185.644515px;top:80.709583px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185.644515px;top:110.419677px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185.644515px;top:140.658590px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185.650293px;top:739.202547px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185.650293px;top:775.735386px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185.650293px;top:757.842026px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:778.864741px;top:295.349141px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:778.864741px;top:330.172447px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:778.864741px;top:371.849266px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:778.864741px;top:406.672571px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p2_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:778.864741px;top:448.351313px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p2_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:778.864741px;top:483.170773px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p2_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:223.837065px;top:350.334927px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p2_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:717.728154px;top:130.862913px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p2_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:717.728154px;top:178.216378px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p2_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:768.410767px;top:130.687921px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p2_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:768.410767px;top:178.237531px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p2_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:223.837065px;top:391.617535px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p2_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185.650293px;top:828.305904px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p2_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185.650293px;top:811.960546px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p2_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287.685869px;top:594.148066px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p2_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287.685869px;top:524.566836px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p2_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:288.577740px;top:453.422220px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p2_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287.685869px;top:382.973724px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p2_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287.685869px;top:341.856495px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p2_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287.685869px;top:665.433059px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">8</font></nobr>");
write("</p>");
write("<p id=\"p2_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185.650293px;top:846.247339px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p2_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395.355840px;top:140.737432px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">SG1</font></nobr>");
write("</p>");
write("<p id=\"p2_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:534.591924px;top:734.360476px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">PG1</font></nobr>");
write("</p>");
write("<p id=\"p2_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536.080946px;top:793.011468px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">LG1</font></nobr>");
write("</p>");
write("<p id=\"p2_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536.080946px;top:823.058083px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">LG2</font></nobr>");
write("</p>");
write("<p id=\"p2_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:534.591924px;top:763.685972px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">PG2</font></nobr>");
write("</p>");
write("<p id=\"p2_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:222.974086px;top:603.316851px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p2_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330.199085px;top:603.316851px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p2_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:329.501769px;top:749.338593px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p2_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:329.501769px;top:767.012734px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p2_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:222.974086px;top:532.951043px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p2_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:329.501769px;top:784.729179px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p2_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:222.974086px;top:462.179486px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p2_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:329.501769px;top:819.669786px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p2_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:329.501769px;top:837.228548px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p2_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:329.501769px;top:854.720005px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p2_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:222.974086px;top:673.892264px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p2_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624.162476px;top:380.546919px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p2_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624.162476px;top:303.867958px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p2_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330.628647px;top:391.875214px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p2_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624.162476px;top:456.181701px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p2_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624.162476px;top:591.882792px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p2_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624.162476px;top:655.821988px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p2_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324.420216px;top:462.423705px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p2_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:222.974086px;top:90.161047px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p2_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216.101084px;top:220.058573px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">薄茶</font></nobr>");
write("</p>");
write("<p id=\"p2_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:222.974086px;top:249.268690px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p2_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:222.974086px;top:119.667304px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p2_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:222.974086px;top:148.956263px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p2_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330.199085px;top:532.910661px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p2_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330.199085px;top:674.065332px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p2_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:222.974086px;top:278.899941px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p2_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304.958909px;top:319.828719px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p2_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:534.836563px;top:448.560918px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">LSC</font></nobr>");
write("</p>");
write("<p id=\"p2_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535.689910px;top:371.401211px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">LSB</font></nobr>");
write("</p>");
write("<p id=\"p2_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535.689910px;top:294.843397px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">LSA</font></nobr>");
write("</p>");
write("<p id=\"p2_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515.151806px;top:582.767850px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">OP2SW</font></nobr>");
write("</p>");
write("<p id=\"p2_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515.151806px;top:647.841607px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">OP3SW</font></nobr>");
write("</p>");
write("<p id=\"p2_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838.516159px;top:301.025788px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ATクラッチ<br>プレッシャ<br>コントロール<br>SOL.V.A</font></nobr>");
write("</p>");
write("<p id=\"p2_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118.605775px;top:493.099136px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">シフト コントロール<br>SOL.V.B</font></nobr>");
write("</p>");
write("<p id=\"p2_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:117.931574px;top:422.716021px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">シフト コントロール<br>SOL.V.A</font></nobr>");
write("</p>");
write("<p id=\"p2_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118.605775px;top:563.282260px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">シフト コントロール<br>SOL.V.C</font></nobr>");
write("</p>");
write("<p id=\"p2_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:117.931574px;top:634.080739px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">シフト コントロール<br>SOL.V.D</font></nobr>");
write("</p>");
write("<p id=\"p2_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838.516159px;top:376.022140px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ATクラッチ<br>プレッシャ<br>コントロール<br>SOL.V.B</font></nobr>");
write("</p>");
write("<p id=\"p2_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838.516159px;top:452.941474px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ATクラッチ<br>プレッシャ<br>コントロール<br>SOL.V.C</font></nobr>");
write("</p>");
write("<p id=\"p2_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:440.758493px;top:37.627064px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">PGM-FI ECU</font></nobr>");
write("</p>");
write("<p id=\"p2_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492.423513px;top:265.864037px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">To 12V</font></nobr>");
write("</p>");
write("<p id=\"p2_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424.040223px;top:52.412883px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">To 5V</font></nobr>");
write("</p>");
write("<p id=\"p2_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359.216716px;top:81.246096px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">C13</font></nobr>");
write("</p>");
write("<p id=\"p2_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359.216716px;top:140.858580px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">C14</font></nobr>");
write("</p>");
write("<p id=\"p2_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395.355840px;top:81.246096px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">VCC1</font></nobr>");
write("</p>");
write("<p id=\"p2_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360.071989px;top:111.515778px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B38</font></nobr>");
write("</p>");
write("<p id=\"p2_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395.355840px;top:111.515778px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">NC</font></nobr>");
write("</p>");
write("<p id=\"p2_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360.071989px;top:211.047473px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B19</font></nobr>");
write("</p>");
write("<p id=\"p2_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360.071989px;top:270.659957px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B34</font></nobr>");
write("</p>");
write("<p id=\"p2_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359.216716px;top:740.562097px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A26</font></nobr>");
write("</p>");
write("<p id=\"p2_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359.216716px;top:758.507378px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A18</font></nobr>");
write("</p>");
write("<p id=\"p2_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359.216716px;top:776.133443px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A36</font></nobr>");
write("</p>");
write("<p id=\"p2_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359.216716px;top:811.106742px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A25</font></nobr>");
write("</p>");
write("<p id=\"p2_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359.216716px;top:828.732808px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A19</font></nobr>");
write("</p>");
write("<p id=\"p2_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359.216716px;top:846.362719px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A35</font></nobr>");
write("</p>");
write("<p id=\"p2_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571.439923px;top:371.605046px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B48</font></nobr>");
write("</p>");
write("<p id=\"p2_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573.474084px;top:582.767850px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B8</font></nobr>");
write("</p>");
write("<p id=\"p2_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:603.460640px;top:131.647490px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p2_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660.526976px;top:131.647490px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p2_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660.526976px;top:178.760583px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p2_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521.148347px;top:122.532549px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">D3SW</font></nobr>");
write("</p>");
write("<p id=\"p2_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571.439923px;top:122.534472px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A43</font></nobr>");
write("</p>");
write("<p id=\"p2_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573.474084px;top:648.160824px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B9</font></nobr>");
write("</p>");
write("<p id=\"p2_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571.439923px;top:734.498930px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B10</font></nobr>");
write("</p>");
write("<p id=\"p2_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571.439923px;top:793.149923px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">C44</font></nobr>");
write("</p>");
write("<p id=\"p2_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571.439923px;top:823.196538px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">C48</font></nobr>");
write("</p>");
write("<p id=\"p2_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573.474084px;top:763.824427px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B1</font></nobr>");
write("</p>");
write("<p id=\"p2_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571.439923px;top:294.685712px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B40</font></nobr>");
write("</p>");
write("<p id=\"p2_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571.439923px;top:448.524382px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B26</font></nobr>");
write("</p>");
write("<p id=\"p2_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395.355840px;top:211.047473px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">VCC2</font></nobr>");
write("</p>");
write("<p id=\"p2_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395.355840px;top:740.602479px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">VCC4</font></nobr>");
write("</p>");
write("<p id=\"p2_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395.355840px;top:757.951635px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">APS1</font></nobr>");
write("</p>");
write("<p id=\"p2_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395.355840px;top:775.971912px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">SG4</font></nobr>");
write("</p>");
write("<p id=\"p2_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395.355840px;top:810.833679px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">VCC5</font></nobr>");
write("</p>");
write("<p id=\"p2_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395.355840px;top:828.627043px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">APS2<br></font></nobr>");
write("</p>");
write("<p id=\"p2_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395.355840px;top:845.972353px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">SG5</font></nobr>");
write("</p>");
write("<p id=\"p2_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360.071989px;top:241.317154px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B18</font></nobr>");
write("</p>");
write("<p id=\"p2_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395.355840px;top:241.317154px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">NM</font></nobr>");
write("</p>");
write("<p id=\"p2_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395.355840px;top:270.538809px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">SG2</font></nobr>");
write("</p>");
write("<p id=\"p2_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360.071989px;top:382.823731px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B28</font></nobr>");
write("</p>");
write("<p id=\"p2_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395.355840px;top:382.704506px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">TATF</font></nobr>");
write("</p>");
write("<p id=\"p2_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360.071989px;top:453.335686px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B11</font></nobr>");
write("</p>");
write("<p id=\"p2_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395.355840px;top:453.214538px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">SHA</font></nobr>");
write("</p>");
write("<p id=\"p2_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360.071989px;top:524.482224px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B27</font></nobr>");
write("</p>");
write("<p id=\"p2_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395.355840px;top:524.361076px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">SHB</font></nobr>");
write("</p>");
write("<p id=\"p2_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360.071989px;top:594.617274px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B21</font></nobr>");
write("</p>");
write("<p id=\"p2_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395.355840px;top:594.498049px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">SHC</font></nobr>");
write("</p>");
write("<p id=\"p2_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360.071989px;top:665.125383px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B12</font></nobr>");
write("</p>");
write("<p id=\"p2_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395.355840px;top:665.006157px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">SHD</font></nobr>");
write("</p>");
write("<p id=\"p2_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766.623170px;top:562.970736px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">2速クラッチ圧スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p2_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766.623170px;top:628.225254px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">3速クラッチ圧スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p2_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:30.384733px;top:360.670470px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ATF温度センサ</font></nobr>");
write("</p>");
write("<p id=\"p2_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:836.419847px;top:151.841229px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">D3スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p2_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:688.731713px;top:123.197901px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p2_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:688.731713px;top:170.157154px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p2_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382.349531px;top:911.951835px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">PGM-FI ECUハーネス カプラ端子配列</font></nobr>");
write("</p>");
write("<p id=\"p2_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:97.403102px;top:1056.896706px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A(49P)</font></nobr>");
write("</p>");
write("<p id=\"p2_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366.600184px;top:1056.896706px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">B(49P)</font></nobr>");
write("</p>");
write("<p id=\"p2_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:428.310806px;top:1070.476816px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">メス端子の端子側</font></nobr>");
write("</p>");
write("<p id=\"p2_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112.405048px;top:955.049738px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p2_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:152.641390px;top:955.049738px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p2_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172.401273px;top:955.049738px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p2_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:232.613240px;top:955.049738px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p2_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212.109811px;top:955.049738px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p2_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:289.101691px;top:955.049738px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">10</font></nobr>");
write("</p>");
write("<p id=\"p2_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271.770861px;top:955.049738px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">9</font></nobr>");
write("</p>");
write("<p id=\"p2_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500.962755px;top:955.049738px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p2_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:520.368200px;top:955.049738px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">8</font></nobr>");
write("</p>");
write("<p id=\"p2_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:557.732444px;top:955.049738px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">10</font></nobr>");
write("</p>");
write("<p id=\"p2_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:540.661663px;top:955.049738px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">9</font></nobr>");
write("</p>");
write("<p id=\"p2_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132.711996px;top:975.606431px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">(12)</font></nobr>");
write("</p>");
write("<p id=\"p2_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:183.176937px;top:975.039150px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">15</font></nobr>");
write("</p>");
write("<p id=\"p2_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197.932318px;top:975.606431px;font-weight:normal;font-size:4.5pt;color:black;\" prt_font_size=\"5.8pt\" disp_font_size=\"4.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">(16)</font></nobr>");
write("</p>");
write("<p id=\"p2_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:232.093142px;top:975.039150px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">18</font></nobr>");
write("</p>");
write("<p id=\"p2_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248.645752px;top:975.039150px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">19</font></nobr>");
write("</p>");
write("<p id=\"p2_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281.743263px;top:975.039150px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">21</font></nobr>");
write("</p>");
write("<p id=\"p2_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118.727131px;top:994.517049px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">22</font></nobr>");
write("</p>");
write("<p id=\"p2_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:151.393155px;top:994.307444px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">24</font></nobr>");
write("</p>");
write("<p id=\"p2_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199.502245px;top:994.517049px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">25</font></nobr>");
write("</p>");
write("<p id=\"p2_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248.645752px;top:994.517049px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">26</font></nobr>");
write("</p>");
write("<p id=\"p2_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281.743263px;top:994.517049px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">28</font></nobr>");
write("</p>");
write("<p id=\"p2_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118.623111px;top:1014.204553px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">29</font></nobr>");
write("</p>");
write("<p id=\"p2_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:135.094816px;top:1014.052637px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.5pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">30</font></nobr>");
write("</p>");
write("<p id=\"p2_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167.219552px;top:1014.204553px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">32</font></nobr>");
write("</p>");
write("<p id=\"p2_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199.833566px;top:1014.204553px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">34</font></nobr>");
write("</p>");
write("<p id=\"p2_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216.347649px;top:1014.204553px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">35</font></nobr>");
write("</p>");
write("<p id=\"p2_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:232.488032px;top:1014.204553px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">36</font></nobr>");
write("</p>");
write("<p id=\"p2_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265.450704px;top:1014.204553px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">38</font></nobr>");
write("</p>");
write("<p id=\"p2_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150.029341px;top:1033.993975px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">42</font></nobr>");
write("</p>");
write("<p id=\"p2_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170.380594px;top:1033.993975px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">43</font></nobr>");
write("</p>");
write("<p id=\"p2_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:189.462421px;top:1033.993975px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">44</font></nobr>");
write("</p>");
write("<p id=\"p2_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226.780435px;top:1033.370929px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(46)</font></nobr>");
write("</p>");
write("<p id=\"p2_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380.835467px;top:955.049738px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p2_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:421.156567px;top:955.049738px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p2_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401.660587px;top:955.049738px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p2_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:440.282699px;top:955.049738px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p2_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402.182611px;top:975.310291px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">12</font></nobr>");
write("</p>");
write("<p id=\"p2_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:419.553894px;top:975.310291px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">13</font></nobr>");
write("</p>");
write("<p id=\"p2_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435.829117px;top:975.310291px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">14</font></nobr>");
write("</p>");
write("<p id=\"p2_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386.741472px;top:975.310291px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">11</font></nobr>");
write("</p>");
write("<p id=\"p2_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:451.437843px;top:975.310291px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">15</font></nobr>");
write("</p>");
write("<p id=\"p2_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:468.235090px;top:975.610277px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">16</font></nobr>");
write("</p>");
write("<p id=\"p2_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:484.699091px;top:975.310291px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">17</font></nobr>");
write("</p>");
write("<p id=\"p2_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500.350195px;top:975.310291px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">18</font></nobr>");
write("</p>");
write("<p id=\"p2_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:517.043423px;top:975.310291px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">19</font></nobr>");
write("</p>");
write("<p id=\"p2_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:549.786499px;top:975.310291px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">21</font></nobr>");
write("</p>");
write("<p id=\"p2_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386.421708px;top:994.655503px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">22</font></nobr>");
write("</p>");
write("<p id=\"p2_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:403.122641px;top:994.655503px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">23</font></nobr>");
write("</p>");
write("<p id=\"p2_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:419.004901px;top:994.580509px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">24</font></nobr>");
write("</p>");
write("<p id=\"p2_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516.708248px;top:994.517049px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">26</font></nobr>");
write("</p>");
write("<p id=\"p2_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:533.118312px;top:994.517049px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">27</font></nobr>");
write("</p>");
write("<p id=\"p2_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:549.549564px;top:994.517049px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">28</font></nobr>");
write("</p>");
write("<p id=\"p2_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386.720282px;top:1015.129509px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">29</font></nobr>");
write("</p>");
write("<p id=\"p2_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402.987801px;top:1015.129509px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">30</font></nobr>");
write("</p>");
write("<p id=\"p2_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:419.515367px;top:1015.129509px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">31</font></nobr>");
write("</p>");
write("<p id=\"p2_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435.675014px;top:1015.129509px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">32</font></nobr>");
write("</p>");
write("<p id=\"p2_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:451.919416px;top:1015.129509px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">33</font></nobr>");
write("</p>");
write("<p id=\"p2_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:468.668506px;top:1015.129509px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">34</font></nobr>");
write("</p>");
write("<p id=\"p2_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:484.991886px;top:1015.129509px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">35</font></nobr>");
write("</p>");
write("<p id=\"p2_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500.903040px;top:1015.129509px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">36</font></nobr>");
write("</p>");
write("<p id=\"p2_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:533.434224px;top:1015.129509px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">38</font></nobr>");
write("</p>");
write("<p id=\"p2_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378.909178px;top:1033.993975px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">40</font></nobr>");
write("</p>");
write("<p id=\"p2_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:478.357743px;top:1033.993975px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">45</font></nobr>");
write("</p>");
write("<p id=\"p2_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:498.456653px;top:1033.993975px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">46</font></nobr>");
write("</p>");
write("<p id=\"p2_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518.178009px;top:1033.993975px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">47</font></nobr>");
write("</p>");
write("<p id=\"p2_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538.134371px;top:1033.993975px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">48</font></nobr>");
write("</p>");
write("<p id=\"p2_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:631.428441px;top:1056.652488px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">C(49P)</font></nobr>");
write("</p>");
write("<p id=\"p2_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766.301479px;top:954.805520px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p2_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:785.706923px;top:954.805520px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">8</font></nobr>");
write("</p>");
write("<p id=\"p2_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:746.429873px;top:954.805520px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p2_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726.394533px;top:954.805520px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p2_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:823.735737px;top:954.805520px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">10</font></nobr>");
write("</p>");
write("<p id=\"p2_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:806.004240px;top:954.805520px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">9</font></nobr>");
write("</p>");
write("<p id=\"p2_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:646.705847px;top:954.805520px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p2_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:686.479880px;top:954.805520px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p2_224\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666.983900px;top:954.805520px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p2_225\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705.607938px;top:954.805520px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p2_226\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:669.143272px;top:974.644939px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">12</font></nobr>");
write("</p>");
write("<p id=\"p2_227\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685.424273px;top:974.644939px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">13</font></nobr>");
write("</p>");
write("<p id=\"p2_228\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:701.699496px;top:974.644939px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">14</font></nobr>");
write("</p>");
write("<p id=\"p2_229\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:653.704057px;top:974.644939px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">11</font></nobr>");
write("</p>");
write("<p id=\"p2_230\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:716.759230px;top:974.644939px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">15</font></nobr>");
write("</p>");
write("<p id=\"p2_231\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734.059240px;top:974.644939px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">16</font></nobr>");
write("</p>");
write("<p id=\"p2_232\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:750.658080px;top:974.644939px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">17</font></nobr>");
write("</p>");
write("<p id=\"p2_233\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766.151229px;top:974.644939px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">18</font></nobr>");
write("</p>");
write("<p id=\"p2_234\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:816.246323px;top:974.644939px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">21</font></nobr>");
write("</p>");
write("<p id=\"p2_235\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:800.233075px;top:974.644939px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">20</font></nobr>");
write("</p>");
write("<p id=\"p2_236\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:653.097277px;top:1014.429542px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">29</font></nobr>");
write("</p>");
write("<p id=\"p2_237\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:669.802062px;top:1014.791063px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">30</font></nobr>");
write("</p>");
write("<p id=\"p2_238\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:686.337335px;top:1014.219937px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">31</font></nobr>");
write("</p>");
write("<p id=\"p2_239\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:701.632076px;top:1014.429542px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">32</font></nobr>");
write("</p>");
write("<p id=\"p2_240\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:704.968410px;top:1033.749756px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">43</font></nobr>");
write("</p>");
write("<p id=\"p2_241\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723.871092px;top:1033.749756px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">44</font></nobr>");
write("</p>");
write("<p id=\"p2_242\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:764.288507px;top:1033.749756px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">46</font></nobr>");
write("</p>");
write("<p id=\"p2_243\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:803.808269px;top:1033.749756px;font-weight:normal;font-size:5.2pt;color:black;\" prt_font_size=\"6.7pt\" disp_font_size=\"5.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">48</font></nobr>");
write("</p>");
write("</v:group>");
}