with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:546.07px;\" coordsize=\"950.00,546.07\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:546.07px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/4015_2.0_jpn_9504551_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:546.07px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834.039074px;top:310.731156px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">エア<br>ミックス<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:839.250077px;top:376.911966px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">モード<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673.098152px;top:338.538211px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">駆動<br>回路</font></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:872.398324px;top:79.996460px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">パワー<br>トランジスタ</font></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:884.061044px;top:53.111139px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ブロア<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783.174572px;top:146.287068px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">日射センサ</font></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629.337464px;top:35.292895px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:780.289188px;top:124.378334px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">外気温センサ</font></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629.337464px;top:488.733483px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629.337464px;top:511.757543px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740.543992px;top:135.256131px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740.543992px;top:341.223469px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740.543992px;top:384.106683px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740.543992px;top:375.569337px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740.543992px;top:358.396403px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740.543992px;top:349.859056px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740.543992px;top:306.785138px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740.543992px;top:315.515114px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740.543992px;top:324.147812px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:794.605499px;top:112.251334px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:794.605499px;top:95.881665px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740.543992px;top:160.967375px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740.543992px;top:512.414410px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:905.426348px;top:481.286421px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:643.282522px;top:536.927497px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">オートA/C コントロール ユニット</font></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:905.266690px;top:75.489890px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740.543992px;top:298.343143px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:779.455312px;top:298.343143px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:762.236305px;top:285.208689px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519.720783px;top:450.440633px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">リヤ デフロスタ<br>リレー</font></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:830.352516px;top:2.070058px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">*1：ディスチャージ ヘッドライト装備車</font></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:830.353477px;top:8.789943px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">*2：ディスチャージ ヘッドライト非装備車</font></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740.543992px;top:35.965172px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629.337464px;top:272.932401px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:891.160049px;top:329.673394px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:839.610749px;top:418.950500px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">内外気<br>切換え<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:848.579484px;top:460.372618px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629.337464px;top:420.847901px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:737.538384px;top:186.892437px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740.543992px;top:367.030064px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740.543992px;top:410.966000px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740.543992px;top:428.426916px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:847.166607px;top:161.061763px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:847.166607px;top:135.256131px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:626.289538px;top:380.974525px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629.337464px;top:453.025723px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:417.594557px;top:402.358343px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ECONスイッチ</font></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378.188875px;top:402.358343px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:905.426348px;top:35.582803px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:891.160049px;top:173.896678px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:891.160049px;top:207.917002px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:859.912308px;top:228.638174px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:891.160049px;top:263.733372px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:872.060734px;top:298.479910px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:863.870092px;top:16.013556px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">：CANライン</font></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:774.679041px;top:150.311102px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">4*<sup>1</sup></font></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:774.679041px;top:156.571566px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1*<sup>2</sup></font></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571.307593px;top:535.777499px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">G502</font></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642.961283px;top:485.185244px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">18</font></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642.961283px;top:508.017639px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">36</font></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:644.885834px;top:449.192393px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:644.884872px;top:376.371639px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722.149672px;top:508.002228px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">14</font></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:677.306003px;top:39.614542px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">17</font></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722.149672px;top:345.446873px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">11</font></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722.149672px;top:336.909527px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">10</font></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722.149672px;top:319.735630px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">13</font></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722.149672px;top:311.199246px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">12</font></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722.149672px;top:156.842210px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">19</font></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722.149672px;top:131.131930px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">22</font></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722.149672px;top:107.284378px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">34</font></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722.149672px;top:90.675849px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">15</font></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:760.622414px;top:535.777499px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">G502</font></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:812.188065px;top:157.895895px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:808.340887px;top:131.131930px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:910.943201px;top:85.907302px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:911.518354px;top:122.498268px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:865.352217px;top:108.328430px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:837.726594px;top:358.685347px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">S-COM</font></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807.749383px;top:350.052649px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">M-VENT</font></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807.749383px;top:341.513376px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">M-DEF</font></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807.749383px;top:384.395628px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">MODE 4</font></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807.749383px;top:367.223657px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">MODE 2</font></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807.749383px;top:375.760040px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">MODE 3</font></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807.749383px;top:358.685347px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">MODE 1</font></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:799.575091px;top:345.446873px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:911.041303px;top:67.624821px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:911.037457px;top:43.067429px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:799.575091px;top:336.909527px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:799.575091px;top:379.790816px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:799.575091px;top:362.619808px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:799.575091px;top:371.157154px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:799.575091px;top:354.081498px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783.334230px;top:131.131930px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:900.617375px;top:535.777499px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">G502</font></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:865.352217px;top:91.759390px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:799.575091px;top:294.027275px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:799.575091px;top:302.659973px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:799.575091px;top:311.199246px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:799.575091px;top:319.735630px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807.749383px;top:298.631124px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">S5V</font></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807.589725px;top:307.170397px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">AMD-P</font></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807.749383px;top:315.708707px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">M-HOT</font></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807.749383px;top:324.341405px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">M-COOL</font></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:837.726594px;top:298.631124px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">S-COM</font></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:861.289598px;top:294.027275px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:861.290559px;top:354.081498px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:654.343160px;top:381.456099px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B-CAN</font></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:654.343160px;top:517.166584px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ILL-</font></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:654.343160px;top:485.185244px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">SMALL</font></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705.638546px;top:508.002228px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">GND</font></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670.693666px;top:497.446122px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">照明<br>(1.12W×4)</font></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:654.397982px;top:442.946376px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">RrDEF<br>RLY</font></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724.073261px;top:182.577533px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:699.308014px;top:182.577533px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">S-COM</font></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724.073261px;top:302.659973px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724.073261px;top:294.123590px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705.919390px;top:161.350708px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">Tsun</font></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706.640736px;top:135.642354px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">Tam</font></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:687.404845px;top:86.418733px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">12V</font></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706.275254px;top:100.859215px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">BLW<br>-G</font></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706.275254px;top:85.213835px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">BLW<br>-V</font></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:676.223984px;top:48.150925px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">IG2</font></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765.792059px;top:57.366328px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:654.343160px;top:268.124365px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ACS</font></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:654.345083px;top:417.107996px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">Teva</font></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:847.665779px;top:410.967927px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">IG2</font></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807.910964px;top:410.872575px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">FRS</font></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807.749383px;top:427.756564px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">REC</font></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:796.809932px;top:460.207920px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722.149672px;top:354.081498px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">27</font></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722.149672px;top:362.619808px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">28</font></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722.149672px;top:371.252506px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">29</font></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722.149672px;top:379.887131px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">30</font></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:643.121903px;top:416.725627px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">23</font></nobr>");
write("</p>");
write("<p id=\"p1_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510.313471px;top:482.065607px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.29(10A)<br>ヒューズ<br>(ヒューズ ボックス)</font></nobr>");
write("</p>");
write("<p id=\"p1_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642.962245px;top:268.316994px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">26</font></nobr>");
write("</p>");
write("<p id=\"p1_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724.073261px;top:407.131706px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">9</font></nobr>");
write("</p>");
write("<p id=\"p1_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724.073261px;top:424.495344px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">8</font></nobr>");
write("</p>");
write("<p id=\"p1_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:861.380968px;top:407.324336px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:799.575091px;top:406.844688px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p1_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:799.575091px;top:424.015696px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p1_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251.818694px;top:398.649260px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">5V</font></nobr>");
write("</p>");
write("<p id=\"p1_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783.174572px;top:239.669111px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">湿度センサ</font></nobr>");
write("</p>");
write("<p id=\"p1_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783.174572px;top:217.759415px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">内気温センサ</font></nobr>");
write("</p>");
write("<p id=\"p1_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:778.846496px;top:202.831579px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">湿度/内気温センサ</font></nobr>");
write("</p>");
write("<p id=\"p1_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740.543992px;top:228.638174px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p1_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740.543992px;top:254.348455px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722.149672px;top:250.225217px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">24</font></nobr>");
write("</p>");
write("<p id=\"p1_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722.149672px;top:224.513010px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">20</font></nobr>");
write("</p>");
write("<p id=\"p1_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:836.474337px;top:224.513010px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:773.717246px;top:224.513010px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:773.717246px;top:250.263743px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p1_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:773.717246px;top:267.851794px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p1_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:698.601095px;top:254.731788px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">HUM</font></nobr>");
write("</p>");
write("<p id=\"p1_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706.928313px;top:229.023433px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">Tr</font></nobr>");
write("</p>");
write("<p id=\"p1_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335.253406px;top:471.785925px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ラジエータ<br>水温センサ</font></nobr>");
write("</p>");
write("<p id=\"p1_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321.067899px;top:361.794390px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">コンビネーション<br>メータ</font></nobr>");
write("</p>");
write("<p id=\"p1_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333.743389px;top:152.567758px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ブロア モータ<br>リレー</font></nobr>");
write("</p>");
write("<p id=\"p1_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:123.096927px;top:17.069166px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ヒューズ ボックス</font></nobr>");
write("</p>");
write("<p id=\"p1_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376.783693px;top:489.829546px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p1_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308.496283px;top:401.281544px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308.496283px;top:381.231685px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p1_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315.085537px;top:506.905202px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p1_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269.480127px;top:35.394989px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p1_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:209.600725px;top:35.394989px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:268.942484px;top:230.058818px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p1_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:369.182631px;top:230.057855px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328.693967px;top:230.057855px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p1_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:210.701017px;top:19.564684px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">イグニッション スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p1_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376.573060px;top:290.088962px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ヒューズ<br>ボックス</font></nobr>");
write("</p>");
write("<p id=\"p1_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73.484681px;top:152.567758px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">コンデンサ<br>ファン リレー</font></nobr>");
write("</p>");
write("<p id=\"p1_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219.436997px;top:152.567758px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A/C コンプレッサ<br>クラッチ リレー</font></nobr>");
write("</p>");
write("<p id=\"p1_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:139.968726px;top:152.567758px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ラジエータ<br>ファン リレー</font></nobr>");
write("</p>");
write("<p id=\"p1_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:77.252030px;top:246.669273px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">コンデンサ<br>ファン<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p1_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67.720647px;top:287.026150px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p1_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67.527326px;top:230.058818px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p1_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:268.942484px;top:120.773270px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p1_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134.973166px;top:120.773270px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p1_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67.438841px;top:120.773270px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p1_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:144.737303px;top:246.669273px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ラジエータ<br>ファン<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p1_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134.977012px;top:287.026150px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p1_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:174.737598px;top:230.058818px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p1_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134.973166px;top:230.058818px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p1_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227.533383px;top:290.855628px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">コンプレッサ<br>クラッチ</font></nobr>");
write("</p>");
write("<p id=\"p1_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227.533383px;top:246.836861px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">サーマル<br>プロテクタ</font></nobr>");
write("</p>");
write("<p id=\"p1_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:213.519075px;top:230.056891px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312.170338px;top:489.539639px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407.749628px;top:478.128257px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p1_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:417.167520px;top:452.606753px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">エバポレータ<br>センサ</font></nobr>");
write("</p>");
write("<p id=\"p1_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:31.645658px;top:9.515194px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">バッテリ ターミナル<br>ヒューズ ボックス</font></nobr>");
write("</p>");
write("<p id=\"p1_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:12.410730px;top:25.005508px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">バッテリ</font></nobr>");
write("</p>");
write("<p id=\"p1_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91.949212px;top:35.203322px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313.744795px;top:420.895096px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p1_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427.038417px;top:420.895096px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p1_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408.185321px;top:434.164390px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p1_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:399.735956px;top:361.996651px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:375.421791px;top:381.705555px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:425.114828px;top:381.705555px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427.038417px;top:272.444085px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p1_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434.732773px;top:35.203322px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p1_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:210.780847px;top:120.773270px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74.057910px;top:216.611341px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">サブ リレー ボックス 1</font></nobr>");
write("</p>");
write("<p id=\"p1_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269.531102px;top:401.473210px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">CAN HI</font></nobr>");
write("</p>");
write("<p id=\"p1_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269.531102px;top:381.499441px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">CAN LO</font></nobr>");
write("</p>");
write("<p id=\"p1_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:273.859177px;top:342.762580px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ACC L</font></nobr>");
write("</p>");
write("<p id=\"p1_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:274.660352px;top:334.126992px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A15</font></nobr>");
write("</p>");
write("<p id=\"p1_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297.102865px;top:376.818540px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A4</font></nobr>");
write("</p>");
write("<p id=\"p1_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297.322154px;top:396.866472px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A3</font></nobr>");
write("</p>");
write("<p id=\"p1_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362.745340px;top:396.866472px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p1_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.339896px;top:502.587408px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A10</font></nobr>");
write("</p>");
write("<p id=\"p1_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.339896px;top:485.415437px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A34</font></nobr>");
write("</p>");
write("<p id=\"p1_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360.517824px;top:485.415437px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335.414025px;top:485.415437px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:275.701976px;top:485.415437px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">TW2</font></nobr>");
write("</p>");
write("<p id=\"p1_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:276.114585px;top:502.587408px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">SG6</font></nobr>");
write("</p>");
write("<p id=\"p1_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74.085802px;top:82.628745px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.47<br>(30A)</font></nobr>");
write("</p>");
write("<p id=\"p1_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238.433400px;top:41.429113px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">IG2</font></nobr>");
write("</p>");
write("<p id=\"p1_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235.146949px;top:29.981132px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">BAT</font></nobr>");
write("</p>");
write("<p id=\"p1_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158.964168px;top:528.679096px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">PGM-FI ECU</font></nobr>");
write("</p>");
write("<p id=\"p1_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:274.260246px;top:190.995449px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p1_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:209.578603px;top:190.995449px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:274.260246px;top:159.626673px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p1_224\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:209.578603px;top:159.626673px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_225\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150.187793px;top:29.445622px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.60(IG)(50A)</font></nobr>");
write("</p>");
write("<p id=\"p1_226\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:375.668011px;top:159.626673px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_227\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324.754457px;top:159.626673px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p1_228\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:375.668011px;top:190.995449px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_229\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324.754457px;top:190.995449px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p1_230\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324.112940px;top:264.193757px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">G501</font></nobr>");
write("</p>");
write("<p id=\"p1_231\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:284.758233px;top:31.554917px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">S1</font></nobr>");
write("</p>");
write("<p id=\"p1_232\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:196.755959px;top:31.554917px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">T1</font></nobr>");
write("</p>");
write("<p id=\"p1_233\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333.891505px;top:217.417496px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">K1</font></nobr>");
write("</p>");
write("<p id=\"p1_234\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374.619655px;top:217.417496px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">S2</font></nobr>");
write("</p>");
write("<p id=\"p1_235\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315.537580px;top:396.866472px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">30</font></nobr>");
write("</p>");
write("<p id=\"p1_236\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315.317329px;top:376.817577px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">29</font></nobr>");
write("</p>");
write("<p id=\"p1_237\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362.745340px;top:377.428213px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">18</font></nobr>");
write("</p>");
write("<p id=\"p1_238\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326.918494px;top:381.423352px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">CAN LO</font></nobr>");
write("</p>");
write("<p id=\"p1_239\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326.757875px;top:401.473210px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">CAN HI</font></nobr>");
write("</p>");
write("<p id=\"p1_240\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:339.101546px;top:390.057977px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B-CAN</font></nobr>");
write("</p>");
write("<p id=\"p1_241\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397.651748px;top:323.559328px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU</font></nobr>");
write("</p>");
write("<p id=\"p1_242\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:410.957213px;top:342.075855px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">Q3</font></nobr>");
write("</p>");
write("<p id=\"p1_243\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:111.649648px;top:190.995449px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p1_244\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:63.745550px;top:190.995449px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_245\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:111.649648px;top:159.626673px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p1_246\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:63.745550px;top:159.626673px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_247\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180.123646px;top:190.995449px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p1_248\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131.003840px;top:190.995449px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_249\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219.597617px;top:243.076730px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_250\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180.123646px;top:159.626673px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p1_251\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131.003840px;top:159.626673px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_252\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:71.721711px;top:265.441034px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_253\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:71.721711px;top:239.728827px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_254\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:63.625325px;top:535.777499px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">G202</font></nobr>");
write("</p>");
write("<p id=\"p1_255\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138.966536px;top:265.441034px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_256\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138.966536px;top:239.728827px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_257\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:178.721351px;top:342.762580px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">FAN C</font></nobr>");
write("</p>");
write("<p id=\"p1_258\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180.644940px;top:334.126992px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A6</font></nobr>");
write("</p>");
write("<p id=\"p1_259\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.339896px;top:415.665200px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A38</font></nobr>");
write("</p>");
write("<p id=\"p1_260\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:276.104006px;top:415.667127px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">TAC</font></nobr>");
write("</p>");
write("<p id=\"p1_261\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:413.319380px;top:443.586870px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_262\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:413.319380px;top:467.859170px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_263\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408.552727px;top:296.412994px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A21</font></nobr>");
write("</p>");
write("<p id=\"p1_264\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:396.289847px;top:332.866231px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B-CAN</font></nobr>");
write("</p>");
write("<p id=\"p1_265\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:42.065740px;top:29.254919px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.1(100A)</font></nobr>");
write("</p>");
write("<p id=\"p1_266\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112.276739px;top:31.554917px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">T-9</font></nobr>");
write("</p>");
write("<p id=\"p1_267\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297.583762px;top:28.375564px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.10(7.5A)</font></nobr>");
write("</p>");
write("<p id=\"p1_268\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141.651867px;top:82.628745px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.30<br>(30A)</font></nobr>");
write("</p>");
write("<p id=\"p1_269\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220.519016px;top:82.628745px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.43<br>(7.5A)</font></nobr>");
write("</p>");
write("<p id=\"p1_270\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:375.662240px;top:82.628745px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.57<br>(40A)</font></nobr>");
write("</p>");
write("<p id=\"p1_271\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:396.495671px;top:31.359398px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">Q14</font></nobr>");
write("</p>");
write("<p id=\"p1_272\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72.883560px;top:108.204185px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A36</font></nobr>");
write("</p>");
write("<p id=\"p1_273\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219.076324px;top:108.204185px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A3</font></nobr>");
write("</p>");
write("<p id=\"p1_274\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140.449623px;top:108.204185px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A22</font></nobr>");
write("</p>");
write("<p id=\"p1_275\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:275.222040px;top:108.204185px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A33</font></nobr>");
write("</p>");
write("<p id=\"p1_276\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:557.923260px;top:268.518293px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_277\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537.244678px;top:268.518293px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_278\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:517.286481px;top:243.540968px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A/Cプレッシャ スイッチ<br>(高圧側OFF：3,100kPa(32kgf/cm2)以上)<br>(低圧側OFF：200kPa(2.0kgf/cm2)以下)</font></nobr>");
write("</p>");
write("<p id=\"p1_279\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:525.462696px;top:272.444085px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("</v:group>");
}