with(document) {
write("<v:group id=\"group20\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:493.10px;\" coordsize=\"950.00,493.10\">");
write("<v:rect id=\"rect20\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:493.10px;\">");
write("<img id=\"img20\" name=\"PrtImgId\" src=\"../img/4035_2.0_jpn_9504483_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:493.10px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p20_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:587.163768px;top:20.799953px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C</font></nobr>");
write("</p>");
write("<p id=\"p20_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19.140793px;top:10.934837px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">イージ ドア クローザ、オーディオ ユニット</font></nobr>");
write("</p>");
write("<p id=\"p20_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131.329508px;top:20.799953px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A</font></nobr>");
write("</p>");
write("<p id=\"p20_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359.247315px;top:20.799953px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B</font></nobr>");
write("</p>");
write("<p id=\"p20_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815.080897px;top:20.799953px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">D</font></nobr>");
write("</p>");
write("<p id=\"p20_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170.646188px;top:112.549462px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">14</font></nobr>");
write("</p>");
write("<p id=\"p20_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199.739326px;top:112.549462px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">24</font></nobr>");
write("</p>");
write("<p id=\"p20_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593.327425px;top:218.227509px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">163</font></nobr>");
write("</p>");
write("<p id=\"p20_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199.851085px;top:128.116094px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p20_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170.866319px;top:128.116094px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p20_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170.866319px;top:169.575440px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p20_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199.851085px;top:169.575440px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p20_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266.115137px;top:231.681540px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p20_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266.115137px;top:246.065630px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p20_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266.115137px;top:260.449720px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p20_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266.115137px;top:274.973251px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p20_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.594351px;top:374.067784px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p20_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238.345493px;top:289.217899px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p20_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.594351px;top:289.217899px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p20_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238.345493px;top:302.303021px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p20_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238.345493px;top:328.479357px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p20_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238.345493px;top:351.273232px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p20_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129.663289px;top:377.216038px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p20_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:524.062822px;top:312.641290px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p20_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513.494522px;top:238.182472px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p20_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:555.034182px;top:238.182472px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p20_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:594.590636px;top:238.182472px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p20_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632.503899px;top:238.182472px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p20_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:672.863659px;top:238.182472px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p20_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:565.601806px;top:312.641290px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p20_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605.830165px;top:312.641290px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p20_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673.614135px;top:312.641290px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p20_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689.713471px;top:312.641290px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p20_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:741.400814px;top:312.641290px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p20_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:757.498119px;top:312.641290px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p20_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:808.105128px;top:312.641290px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p20_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824.202432px;top:312.641290px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p20_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129.663289px;top:303.771214px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p20_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:263.971404px;top:200.318132px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p20_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:619.896849px;top:312.641290px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p20_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:126.276664px;top:421.878467px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G602</font></nobr>");
write("</p>");
write("<p id=\"p20_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:520.676198px;top:349.068574px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G502</font></nobr>");
write("</p>");
write("<p id=\"p20_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:562.215181px;top:349.438160px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G503</font></nobr>");
write("</p>");
write("<p id=\"p20_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201.232828px;top:351.602881px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R/C3</font></nobr>");
write("</p>");
write("<p id=\"p20_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201.232828px;top:328.475296px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R/C1</font></nobr>");
write("</p>");
write("<p id=\"p20_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:200.029221px;top:302.483076px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">CLMP</font></nobr>");
write("</p>");
write("<p id=\"p20_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201.988045px;top:289.214515px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">COM</font></nobr>");
write("</p>");
write("<p id=\"p20_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:163.629780px;top:291.019126px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">GND</font></nobr>");
write("</p>");
write("<p id=\"p20_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204.617420px;top:275.101185px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L/P</font></nobr>");
write("</p>");
write("<p id=\"p20_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204.840938px;top:260.627067px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">F/L</font></nobr>");
write("</p>");
write("<p id=\"p20_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204.316688px;top:246.050738px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">H/L</font></nobr>");
write("</p>");
write("<p id=\"p20_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201.532883px;top:231.677479px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">CLM-</font></nobr>");
write("</p>");
write("<p id=\"p20_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:198.749755px;top:200.089341px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">CLM＋</font></nobr>");
write("</p>");
write("<p id=\"p20_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197.368689px;top:185.363417px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">VMP</font></nobr>");
write("</p>");
write("<p id=\"p20_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:166.381074px;top:185.363417px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">＋B<br>BACK UP</font></nobr>");
write("</p>");
write("<p id=\"p20_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:203.603465px;top:143.680694px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">D7</font></nobr>");
write("</p>");
write("<p id=\"p20_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:174.704720px;top:143.680694px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">D4</font></nobr>");
write("</p>");
write("<p id=\"p20_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:203.603465px;top:177.976426px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p20_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214.892439px;top:196.929579px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p20_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:174.704720px;top:177.976426px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">9</font></nobr>");
write("</p>");
write("<p id=\"p20_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:203.603465px;top:153.834169px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A8</font></nobr>");
write("</p>");
write("<p id=\"p20_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133.727239px;top:322.157126px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A10</font></nobr>");
write("</p>");
write("<p id=\"p20_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133.727239px;top:332.310602px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">D5</font></nobr>");
write("</p>");
write("<p id=\"p20_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319.596714px;top:196.929579px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A1</font></nobr>");
write("</p>");
write("<p id=\"p20_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:353.094496px;top:213.513589px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.クローザ<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p20_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:329.713239px;top:235.682686px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(ラッチ ラチェット スイッチ)</font></nobr>");
write("</p>");
write("<p id=\"p20_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327.751029px;top:174.084260px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.スライド ドア<br>クローザ アッセンブリ</font></nobr>");
write("</p>");
write("<p id=\"p20_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171.656757px;top:263.040887px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.スライド<br>ドア クローザ<br>コントロール<br>ユニット</font></nobr>");
write("</p>");
write("<p id=\"p20_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:190.621855px;top:97.990056px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.40(20A)*<sup>1</sup><br>ヒューズ<br>(1-C)</font></nobr>");
write("</p>");
write("<p id=\"p20_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666.312572px;top:199.256079px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.14(7.5A)*<sup>1</sup><br>ヒューズ<br>(2-D)</font></nobr>");
write("</p>");
write("<p id=\"p20_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625.371667px;top:199.256079px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.1(10A)*<sup>1</sup><br>ヒューズ<br>(1-C)</font></nobr>");
write("</p>");
write("<p id=\"p20_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588.231232px;top:199.256079px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">データ リンク<br>カプラ(DLC)<br>(4-B)</font></nobr>");
write("</p>");
write("<p id=\"p20_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:549.047985px;top:203.025726px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">PGM-FI ECU<br>(4-D)</font></nobr>");
write("</p>");
write("<p id=\"p20_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509.469857px;top:202.640571px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(12-C)</font></nobr>");
write("</p>");
write("<p id=\"p20_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512.202863px;top:212.980193px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">171</font></nobr>");
write("</p>");
write("<p id=\"p20_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:553.743201px;top:212.980193px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">106</font></nobr>");
write("</p>");
write("<p id=\"p20_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632.407718px;top:212.980193px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">16</font></nobr>");
write("</p>");
write("<p id=\"p20_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673.054665px;top:212.980193px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">81</font></nobr>");
write("</p>");
write("<p id=\"p20_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:162.174208px;top:97.990056px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.1(10A)*<sup>1</sup><br>ヒューズ<br>(1-C)</font></nobr>");
write("</p>");
write("<p id=\"p20_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331.581978px;top:249.942227px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.ハーフ ラッチ スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p20_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331.581978px;top:265.127764px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.フル ラッチ スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p20_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333.695910px;top:278.834956px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.ラチェット スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p20_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326.429568px;top:388.268434px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.リモート コントロール スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p20_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:338.418896px;top:306.587788px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.元位置スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p20_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214.892439px;top:227.783959px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p20_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319.596714px;top:227.783959px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A2</font></nobr>");
write("</p>");
write("<p id=\"p20_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214.892439px;top:242.620895px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">12</font></nobr>");
write("</p>");
write("<p id=\"p20_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319.596714px;top:242.620895px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B3</font></nobr>");
write("</p>");
write("<p id=\"p20_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214.892439px;top:256.328086px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p20_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319.596714px;top:256.328086px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B1</font></nobr>");
write("</p>");
write("<p id=\"p20_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214.892439px;top:271.050625px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p20_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319.596714px;top:271.050625px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B4</font></nobr>");
write("</p>");
write("<p id=\"p20_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214.892439px;top:285.265490px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p20_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:157.149812px;top:287.296185px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">8</font></nobr>");
write("</p>");
write("<p id=\"p20_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319.596714px;top:285.265490px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B5</font></nobr>");
write("</p>");
write("<p id=\"p20_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214.892439px;top:298.803457px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p20_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319.596714px;top:298.803457px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B6</font></nobr>");
write("</p>");
write("<p id=\"p20_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214.892439px;top:324.864720px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">11</font></nobr>");
write("</p>");
write("<p id=\"p20_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319.596714px;top:324.864720px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p20_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214.892439px;top:348.049165px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">10</font></nobr>");
write("</p>");
write("<p id=\"p20_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319.596714px;top:348.049165px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p20_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:353.997370px;top:332.987500px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*2</font></nobr>");
write("</p>");
write("<p id=\"p20_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:146.934397px;top:327.346906px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*4</font></nobr>");
write("</p>");
write("<p id=\"p20_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:353.997370px;top:356.171945px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*3</font></nobr>");
write("</p>");
write("<p id=\"p20_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319.596714px;top:370.725260px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p20_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:174.704720px;top:153.834169px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A1</font></nobr>");
write("</p>");
write("<p id=\"p20_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216.784886px;top:148.119117px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*4</font></nobr>");
write("</p>");
write("<p id=\"p20_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116.305764px;top:84.330924px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(L.パワー スライド ドア装備およびイージ ドア クローザ装備車)</font></nobr>");
write("</p>");
write("<p id=\"p20_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607.629140px;top:343.660833px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.フロント<br>スピーカ</font></nobr>");
write("</p>");
write("<p id=\"p20_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:777.359317px;top:222.997611px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">フィーダ線</font></nobr>");
write("</p>");
write("<p id=\"p20_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:777.359995px;top:242.536959px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">サブ<br>フィーダ線</font></nobr>");
write("</p>");
write("<p id=\"p20_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:672.844017px;top:271.545437px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">オーディオ ユニット</font></nobr>");
write("</p>");
write("<p id=\"p20_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:802.232721px;top:199.428688px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ルーフ アンテナ<br>(AM/FM)</font></nobr>");
write("</p>");
write("<p id=\"p20_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674.899698px;top:343.863903px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.フロント<br>スピーカ</font></nobr>");
write("</p>");
write("<p id=\"p20_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:744.188006px;top:344.063588px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.リヤ<br>スピーカ</font></nobr>");
write("</p>");
write("<p id=\"p20_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:812.280836px;top:344.063588px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.リヤ<br>スピーカ</font></nobr>");
write("</p>");
write("<p id=\"p20_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605.624936px;top:276.580884px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FR<br>L＋</font></nobr>");
write("</p>");
write("<p id=\"p20_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:569.642726px;top:287.860718px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A12</font></nobr>");
write("</p>");
write("<p id=\"p20_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:828.002902px;top:287.860718px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A6</font></nobr>");
write("</p>");
write("<p id=\"p20_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:811.875118px;top:287.860718px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A7</font></nobr>");
write("</p>");
write("<p id=\"p20_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745.182319px;top:287.860718px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A11</font></nobr>");
write("</p>");
write("<p id=\"p20_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761.572228px;top:287.860718px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A10</font></nobr>");
write("</p>");
write("<p id=\"p20_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693.555258px;top:287.860718px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A18</font></nobr>");
write("</p>");
write("<p id=\"p20_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:677.431538px;top:287.860718px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A19</font></nobr>");
write("</p>");
write("<p id=\"p20_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609.856862px;top:287.860718px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A23</font></nobr>");
write("</p>");
write("<p id=\"p20_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:626.281992px;top:287.860718px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A22</font></nobr>");
write("</p>");
write("<p id=\"p20_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:818.848178px;top:255.428488px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">E1</font></nobr>");
write("</p>");
write("<p id=\"p20_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:553.835994px;top:262.680100px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">VSP</font></nobr>");
write("</p>");
write("<p id=\"p20_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:837.390626px;top:255.226772px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">E3</font></nobr>");
write("</p>");
write("<p id=\"p20_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:800.502156px;top:255.226772px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">E2</font></nobr>");
write("</p>");
write("<p id=\"p20_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630.446185px;top:261.982895px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">＋B<br>RADIO</font></nobr>");
write("</p>");
write("<p id=\"p20_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636.379552px;top:255.226772px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A24</font></nobr>");
write("</p>");
write("<p id=\"p20_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:598.580079px;top:255.226772px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A3</font></nobr>");
write("</p>");
write("<p id=\"p20_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:559.076457px;top:255.226772px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A15</font></nobr>");
write("</p>");
write("<p id=\"p20_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:522.776582px;top:280.608430px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ILL-</font></nobr>");
write("</p>");
write("<p id=\"p20_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:829.932601px;top:262.680100px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ANT＋B</font></nobr>");
write("</p>");
write("<p id=\"p20_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670.175356px;top:262.680100px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ACC<br>RADIO</font></nobr>");
write("</p>");
write("<p id=\"p20_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.749333px;top:276.579530px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FR<br>L-</font></nobr>");
write("</p>");
write("<p id=\"p20_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:672.997092px;top:276.579530px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FR<br>R＋</font></nobr>");
write("</p>");
write("<p id=\"p20_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689.321978px;top:276.579530px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FR<br>R-</font></nobr>");
write("</p>");
write("<p id=\"p20_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740.950393px;top:276.579530px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">RR<br>L＋</font></nobr>");
write("</p>");
write("<p id=\"p20_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:757.077500px;top:276.579530px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">RR<br>L-</font></nobr>");
write("</p>");
write("<p id=\"p20_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:793.448493px;top:262.680100px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">AM/FM<br>SH</font></nobr>");
write("</p>");
write("<p id=\"p20_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807.442027px;top:276.579530px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">RR<br>R＋</font></nobr>");
write("</p>");
write("<p id=\"p20_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:823.568456px;top:276.579530px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">RR<br>R-</font></nobr>");
write("</p>");
write("<p id=\"p20_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:517.450099px;top:255.226772px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A13</font></nobr>");
write("</p>");
write("<p id=\"p20_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512.209636px;top:263.283893px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ILL＋</font></nobr>");
write("</p>");
write("<p id=\"p20_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:676.624844px;top:255.226772px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A14</font></nobr>");
write("</p>");
write("<p id=\"p20_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:811.791808px;top:262.680100px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">AM/FM<br>SIG</font></nobr>");
write("</p>");
write("<p id=\"p20_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:561.675353px;top:276.579530px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">RADIO<br>GND</font></nobr>");
write("</p>");
write("<p id=\"p20_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:590.718369px;top:262.680100px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">K-LINE</font></nobr>");
write("</p>");
write("<p id=\"p20_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:819.250509px;top:212.117148px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A2</font></nobr>");
write("</p>");
write("<p id=\"p20_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:837.707614px;top:212.117148px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A3</font></nobr>");
write("</p>");
write("<p id=\"p20_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:800.704675px;top:212.117148px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A1</font></nobr>");
write("</p>");
write("<p id=\"p20_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528.017723px;top:287.860718px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A1</font></nobr>");
write("</p>");
write("<p id=\"p20_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:737.508905px;top:155.257010px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">マスト<br>アンテナ<br>(AM/FM)</font></nobr>");
write("</p>");
write("<p id=\"p20_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713.008030px;top:146.796457px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(マスト アンテナ装備車)</font></nobr>");
write("</p>");
write("<p id=\"p20_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:776.991530px;top:146.796457px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(ルーフ アンテナ装備車)</font></nobr>");
write("</p>");
write("<p id=\"p20_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724.030816px;top:216.527817px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">サブ<br>フィーダ線</font></nobr>");
write("</p>");
write("<p id=\"p20_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715.684141px;top:262.680100px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">AM/FM<br>SH</font></nobr>");
write("</p>");
write("<p id=\"p20_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:725.094894px;top:255.924654px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">E2</font></nobr>");
write("</p>");
write("<p id=\"p20_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:748.279726px;top:255.924654px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">E1</font></nobr>");
write("</p>");
write("<p id=\"p20_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:747.319957px;top:215.410935px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p20_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:741.079084px;top:208.540417px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p20_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738.436163px;top:262.680100px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">AM/FM<br>SIG</font></nobr>");
write("</p>");
write("<p id=\"p20_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838.481796px;top:32.374238px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*1：ヒューズ ボックス</font></nobr>");
write("</p>");
write("<p id=\"p20_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:868.000971px;top:52.000906px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">：その他の通信線</font></nobr>");
write("</p>");
write("<p id=\"p20_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:868.000971px;top:60.999592px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">：シールド線</font></nobr>");
write("</p>");
write("<p id=\"p20_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:868.000971px;top:56.499572px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">：工場出荷時は未装備</font></nobr>");
write("</p>");
write("<p id=\"p20_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838.481796px;top:36.987977px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*2：リモート コントロール スイッチ1</font></nobr>");
write("</p>");
write("<p id=\"p20_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838.481796px;top:41.602393px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*3：リモート コントロール スイッチ3</font></nobr>");
write("</p>");
write("<p id=\"p20_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838.481796px;top:46.217486px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*4：CESS Assy.</font></nobr>");
write("</p>");
write("<p id=\"p20_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1.191006px;top:16.000067px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.2pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">19</font></nobr>");
write("</p>");
write("<p id=\"p20_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:933.723841px;top:16.000067px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.2pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">19</font></nobr>");
write("</p>");
write("</v:group>");
}