with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475.00px; height:405.83px;\" coordsize=\"475.00,405.83\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:475.00px;height:405.83px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/4419_3.0_jpn_9503370_3.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475.00px;height:405.83px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112.104011px;top:281.713739px;font-weight:normal;font-size:23.2pt;color:black;\" prt_font_size=\"24.6pt\" disp_font_size=\"23.2pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:31.0px;\" src=\"../img/symbol/SymbolGaiji00007.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:80.937888px;top:337.820099px;font-weight:normal;font-size:15.7pt;color:black;\" prt_font_size=\"16.9pt\" disp_font_size=\"15.7pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:21.0px;\" src=\"../img/symbol/SymbolGaiji00014.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:3.589516px;top:280.862421px;font-weight:normal;font-size:23.2pt;color:black;\" prt_font_size=\"24.6pt\" disp_font_size=\"23.2pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:31.0px;\" src=\"../img/symbol/SymbolGaiji00007.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:8.875805px;top:338.151947px;font-weight:normal;font-size:15.7pt;color:black;\" prt_font_size=\"16.9pt\" disp_font_size=\"15.7pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:21.0px;\" src=\"../img/symbol/SymbolGaiji00014.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40.532250px;top:281.540583px;font-weight:normal;font-size:23.2pt;color:black;\" prt_font_size=\"24.6pt\" disp_font_size=\"23.2pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:31.0px;\" src=\"../img/symbol/SymbolGaiji00007.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:76.417727px;top:282.103327px;font-weight:normal;font-size:23.2pt;color:black;\" prt_font_size=\"24.6pt\" disp_font_size=\"23.2pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:31.0px;\" src=\"../img/symbol/SymbolGaiji00007.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:117.145139px;top:338.382812px;font-weight:normal;font-size:15.7pt;color:black;\" prt_font_size=\"16.9pt\" disp_font_size=\"15.7pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:21.0px;\" src=\"../img/symbol/SymbolGaiji00014.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:46.140314px;top:338.454956px;font-weight:normal;font-size:15.7pt;color:black;\" prt_font_size=\"16.9pt\" disp_font_size=\"15.7pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:21.0px;\" src=\"../img/symbol/SymbolGaiji00014.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:409.699114px;top:338.238525px;font-weight:normal;font-size:15.7pt;color:black;\" prt_font_size=\"16.9pt\" disp_font_size=\"15.7pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:21.0px;\" src=\"../img/symbol/SymbolGaiji00014.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:443.286204px;top:338.512665px;font-weight:normal;font-size:15.7pt;color:black;\" prt_font_size=\"16.9pt\" disp_font_size=\"15.7pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:21.0px;\" src=\"../img/symbol/SymbolGaiji00014.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404.366857px;top:282.983484px;font-weight:normal;font-size:23.2pt;color:black;\" prt_font_size=\"24.6pt\" disp_font_size=\"23.2pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:31.0px;\" src=\"../img/symbol/SymbolGaiji00007.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335.522516px;top:282.175470px;font-weight:normal;font-size:23.2pt;color:black;\" prt_font_size=\"24.6pt\" disp_font_size=\"23.2pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:31.0px;\" src=\"../img/symbol/SymbolGaiji00007.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:369.845090px;top:281.684870px;font-weight:normal;font-size:23.2pt;color:black;\" prt_font_size=\"24.6pt\" disp_font_size=\"23.2pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:31.0px;\" src=\"../img/symbol/SymbolGaiji00007.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:438.689431px;top:284.686090px;font-weight:normal;font-size:23.2pt;color:black;\" prt_font_size=\"24.6pt\" disp_font_size=\"23.2pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:31.0px;\" src=\"../img/symbol/SymbolGaiji00007.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341.283805px;top:338.325104px;font-weight:normal;font-size:15.7pt;color:black;\" prt_font_size=\"16.9pt\" disp_font_size=\"15.7pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:21.0px;\" src=\"../img/symbol/SymbolGaiji00014.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:375.207992px;top:338.238525px;font-weight:normal;font-size:15.7pt;color:black;\" prt_font_size=\"16.9pt\" disp_font_size=\"15.7pt\">");
write("<nobr><font style=\"font-weight:normal;\"><img id=\"gi1\" style=\"height:21.0px;\" src=\"../img/symbol/SymbolGaiji00014.png\"></img></font></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:119.183042px;top:92.104277px;font-weight:normal;font-size:11.2pt;color:black;\" prt_font_size=\"12.3pt\" disp_font_size=\"11.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FR-GND(桃)</font></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249.149145px;top:65.641616px;font-weight:normal;font-size:11.2pt;color:black;\" prt_font_size=\"12.3pt\" disp_font_size=\"11.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">RL-GND(赤)</font></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:136.053200px;top:215.442789px;font-weight:normal;font-size:11.2pt;color:black;\" prt_font_size=\"12.3pt\" disp_font_size=\"11.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FR ＋B(緑)</font></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253.224951px;top:238.211643px;font-weight:normal;font-size:11.2pt;color:black;\" prt_font_size=\"12.3pt\" disp_font_size=\"11.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">RL ＋B(黄)</font></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167.893516px;top:371.217539px;font-weight:normal;font-size:11.2pt;color:black;\" prt_font_size=\"12.3pt\" disp_font_size=\"11.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">メス端子のコード側</font></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37.559670px;top:25.514756px;font-weight:normal;font-size:11.2pt;color:black;\" prt_font_size=\"12.3pt\" disp_font_size=\"11.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">VSAモジュレータ コントロール ユニット38Pカプラ</font></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271.106399px;top:92.753579px;font-weight:normal;font-size:11.2pt;color:black;\" prt_font_size=\"12.3pt\" disp_font_size=\"11.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FL-GND(灰)</font></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:127.901588px;top:237.692202px;font-weight:normal;font-size:11.2pt;color:black;\" prt_font_size=\"12.3pt\" disp_font_size=\"11.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">RR-GND(灰)</font></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141.477392px;top:65.223177px;font-weight:normal;font-size:11.2pt;color:black;\" prt_font_size=\"12.3pt\" disp_font_size=\"11.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">RR ＋B(空)</font></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265.927368px;top:216.164235px;font-weight:normal;font-size:11.2pt;color:black;\" prt_font_size=\"12.3pt\" disp_font_size=\"11.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FL ＋B(橙)</font></nobr>");
write("</p>");
write("</v:group>");
}