with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:546.07px;\" coordsize=\"950.00,546.07\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:546.07px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/4714_2.0_jpn_9503148_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:546.07px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761.139921px;top:213.571948px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761.139921px;top:239.702064px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:798.058309px;top:204.185075px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">内気温センサ</font></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:788.267722px;top:192.642654px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">湿度/内気温センサ</font></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:795.169094px;top:225.986783px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">温度センサ</font></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:854.755299px;top:288.470714px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">エア<br>ミックス<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:859.972258px;top:351.360554px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">モード<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693.605485px;top:313.035871px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">駆動<br>回路</font></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:864.475581px;top:82.998316px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">パワー<br>トランジスタ</font></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:876.698886px;top:53.901798px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ブロア<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:801.027459px;top:148.050437px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">日射センサ</font></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649.786689px;top:36.106271px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:798.138244px;top:125.078134px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">外気温センサ</font></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:628.491249px;top:489.243423px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:628.491249px;top:512.511019px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761.139921px;top:135.942437px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761.139921px;top:315.717559px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761.139921px;top:358.546672px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761.139921px;top:350.018748px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761.139921px;top:332.867673px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761.139921px;top:324.341671px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761.139921px;top:281.322108px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761.139921px;top:290.041446px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761.139921px;top:298.663633px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815.270325px;top:112.966287px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815.270325px;top:98.862412px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761.139921px;top:161.620475px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761.139921px;top:512.894804px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:898.091597px;top:482.079427px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649.741425px;top:537.104069px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">オートA/Cコントロール ユニット</font></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:897.931727px;top:76.251772px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761.139921px;top:272.892294px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:796.451905px;top:272.892294px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:778.956746px;top:265.150216px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518.730938px;top:447.182843px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">リヤ デフロスタ<br>リレー</font></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834.035776px;top:2.924699px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">*1: ディスチャージ ヘッドライト装備車</font></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834.036739px;top:9.634692px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">*2: ディスチャージ ヘッドライト非装備車</font></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761.139921px;top:36.777656px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:628.491249px;top:252.927754px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:883.807318px;top:304.181872px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:860.332447px;top:385.819489px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">内外気<br>切換え<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:863.582814px;top:413.255822px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:628.491249px;top:421.717378px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761.139921px;top:341.491785px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761.139921px;top:378.039897px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761.139921px;top:395.478571px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:758.524218px;top:184.422527px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:860.693599px;top:213.668135px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:860.693599px;top:161.715700px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:860.693599px;top:135.942437px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625.440239px;top:389.938209px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:628.491249px;top:450.309877px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:898.091597px;top:36.394832px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:883.807318px;top:238.536280px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:883.807318px;top:173.330261px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:883.807318px;top:198.929426px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:845.679312px;top:209.725436px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783.081582px;top:209.725436px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783.081582px;top:235.374618px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783.081582px;top:251.887012px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:867.596896px;top:16.849667px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">: CANライン</font></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742.721176px;top:209.453228px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">20</font></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742.721176px;top:235.987328px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">24</font></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:792.680517px;top:152.902101px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">4*<sup>1</sup><br>1*<sup>2</sup></font></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570.386248px;top:535.955598px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">G502</font></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642.133159px;top:485.427691px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">18</font></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642.133159px;top:508.230704px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">36</font></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:644.060266px;top:445.935299px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:644.059303px;top:385.340478px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742.721176px;top:508.216276px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">14</font></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:697.818924px;top:40.420252px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">17</font></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742.721176px;top:319.935353px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">11</font></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742.721176px;top:311.408389px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">10</font></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742.721176px;top:294.257314px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">13</font></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742.721176px;top:285.730351px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">12</font></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742.721176px;top:157.501755px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">19</font></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742.721176px;top:180.442315px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742.721176px;top:131.823717px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">22</font></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742.721176px;top:108.005932px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">34</font></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742.721176px;top:93.662551px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">15</font></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:782.334238px;top:535.955598px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">G502</font></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:830.078515px;top:158.553077px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:826.226228px;top:131.823717px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:903.614812px;top:88.900341px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:904.191692px;top:125.654293px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:857.965217px;top:109.048598px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:858.447716px;top:333.157195px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">S-COM</font></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:828.432625px;top:324.535007px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">M-VENT</font></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:828.432625px;top:316.007082px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">M-DEF</font></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:828.432625px;top:358.834271px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">MODE 4</font></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:828.432625px;top:341.684158px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">MODE 2</font></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:828.432625px;top:350.210159px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">MODE 3</font></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:828.432625px;top:333.157195px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">MODE 1</font></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820.246516px;top:319.935353px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:903.714008px;top:68.396193px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:903.710157px;top:43.869511px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820.246516px;top:311.408389px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820.246516px;top:354.235578px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820.246516px;top:337.086428px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820.246516px;top:345.612429px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820.246516px;top:328.558502px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:801.187329px;top:131.823717px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:893.276238px;top:535.955598px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">G502</font></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:857.965217px;top:94.744653px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820.246516px;top:268.580238px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820.246516px;top:277.202427px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820.246516px;top:285.730351px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820.246516px;top:294.257314px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:828.432625px;top:273.179893px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">S5V</font></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:828.270830px;top:281.706856px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">AMD-P</font></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:828.432625px;top:290.234781px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">M-HOT</font></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:828.432625px;top:298.856969px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">M-COOL</font></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:858.447716px;top:273.179893px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">S-COM</font></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:882.041045px;top:268.580238px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:882.042008px;top:328.558502px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:653.529186px;top:390.419143px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B-CAN</font></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:653.529186px;top:516.903871px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ILL-</font></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:653.529186px;top:485.427691px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">SMALL</font></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726.188125px;top:508.216276px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">GND</font></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:669.901403px;top:497.673237px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">照明<br>(1.12W×4)</font></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:653.584081px;top:441.301980px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">RrDEF<br>RLY</font></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:744.647319px;top:277.202427px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:744.647319px;top:268.677387px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:733.090460px;top:213.665249px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">Tr</font></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726.538683px;top:239.315393px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">HUM</font></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726.469342px;top:162.004261px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">Tsun</font></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:727.191646px;top:136.327185px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">Tam</font></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:707.931176px;top:89.411093px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">12V</font></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726.823753px;top:103.833348px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">BLW<br>-G</font></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719.572786px;top:180.441354px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">S-COM</font></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726.823753px;top:89.490928px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">BLW<br>-V</font></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:696.735468px;top:48.946253px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">IG2</font></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:786.418625px;top:58.151333px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:653.529186px;top:248.127069px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ACS</font></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:653.531112px;top:417.437063px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">Teva</font></nobr>");
write("</p>");
write("<p id=\"p1_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:868.398172px;top:378.040859px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">IG2</font></nobr>");
write("</p>");
write("<p id=\"p1_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:828.592495px;top:377.945633px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">FRS</font></nobr>");
write("</p>");
write("<p id=\"p1_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:828.432625px;top:394.808148px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">REC</font></nobr>");
write("</p>");
write("<p id=\"p1_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:817.477685px;top:413.092304px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742.721176px;top:328.558502px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">27</font></nobr>");
write("</p>");
write("<p id=\"p1_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742.721176px;top:337.086428px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">28</font></nobr>");
write("</p>");
write("<p id=\"p1_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742.721176px;top:345.708615px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">29</font></nobr>");
write("</p>");
write("<p id=\"p1_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742.721176px;top:354.331765px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">30</font></nobr>");
write("</p>");
write("<p id=\"p1_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642.293992px;top:417.054240px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">23</font></nobr>");
write("</p>");
write("<p id=\"p1_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506.311167px;top:482.311237px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.29(10A)<br>ヒューズ<br>(ヒューズ ボックス)</font></nobr>");
write("</p>");
write("<p id=\"p1_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642.134123px;top:248.318481px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">26</font></nobr>");
write("</p>");
write("<p id=\"p1_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:744.647319px;top:374.209737px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">9</font></nobr>");
write("</p>");
write("<p id=\"p1_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:744.647319px;top:391.551262px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">8</font></nobr>");
write("</p>");
write("<p id=\"p1_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:882.132536px;top:374.402111px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820.246516px;top:373.923101px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p1_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820.246516px;top:391.072251px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p1_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254.864720px;top:399.597291px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">5V</font></nobr>");
write("</p>");
write("<p id=\"p1_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:338.293689px;top:472.045217px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ラジエータ<br>水温センサ</font></nobr>");
write("</p>");
write("<p id=\"p1_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324.089345px;top:362.194078px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">コンビネーション<br>メータ</font></nobr>");
write("</p>");
write("<p id=\"p1_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336.781667px;top:154.594027px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ブロア モータ<br>リレー</font></nobr>");
write("</p>");
write("<p id=\"p1_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:125.861274px;top:17.905799px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ヒューズ ボックス</font></nobr>");
write("</p>");
write("<p id=\"p1_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:379.878159px;top:490.065820px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p1_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380.150709px;top:405.954279px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p1_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:311.501999px;top:398.358404px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:311.501999px;top:381.606505px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p1_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:318.098077px;top:507.118785px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p1_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:272.434035px;top:36.206306px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p1_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212.478011px;top:36.206306px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271.896641px;top:230.623951px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p1_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:372.267004px;top:230.622989px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331.725541px;top:230.622989px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p1_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:213.579765px;top:20.397999px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">イグニッション スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p1_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380.758407px;top:291.396718px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ヒューズ<br>ボックス</font></nobr>");
write("</p>");
write("<p id=\"p1_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:75.365502px;top:154.594027px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">コンデンサ<br>ファン リレー</font></nobr>");
write("</p>");
write("<p id=\"p1_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:224.238078px;top:154.594027px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A/C コンプレッサ<br>クラッチ リレー</font></nobr>");
write("</p>");
write("<p id=\"p1_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:142.755477px;top:154.594027px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ラジエータ<br>ファン リレー</font></nobr>");
write("</p>");
write("<p id=\"p1_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79.956465px;top:247.213294px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">コンデンサ<br>ファン<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p1_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70.413388px;top:287.519426px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p1_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70.220774px;top:230.623951px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p1_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271.896641px;top:121.477861px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p1_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137.752320px;top:121.477861px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p1_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70.131208px;top:121.477861px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p1_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:147.530386px;top:247.213294px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ラジエータ<br>ファン<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p1_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137.757135px;top:287.519426px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p1_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177.569553px;top:230.623951px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p1_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:137.752320px;top:230.623951px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p1_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230.432556px;top:291.343815px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">コンプレッサ<br>クラッチ</font></nobr>");
write("</p>");
write("<p id=\"p1_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227.438366px;top:250.371108px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">サーマル<br>プロテクタ</font></nobr>");
write("</p>");
write("<p id=\"p1_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216.400602px;top:230.622027px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315.180933px;top:489.777260px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:410.884251px;top:478.379120px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p1_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:420.313685px;top:452.889608px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">エバポレータ<br>センサ</font></nobr>");
write("</p>");
write("<p id=\"p1_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34.292423px;top:10.358979px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">バッテリ ターミナル<br>ヒューズ ボックス</font></nobr>");
write("</p>");
write("<p id=\"p1_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:15.030991px;top:25.829670px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">バッテリ</font></nobr>");
write("</p>");
write("<p id=\"p1_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:94.672199px;top:36.015856px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316.756518px;top:421.219130px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p1_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:430.196726px;top:421.219130px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p1_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:411.320522px;top:434.471752px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p1_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402.859938px;top:362.395108px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378.514450px;top:390.668267px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:428.270583px;top:390.668267px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:430.196726px;top:252.440087px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p1_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:437.901299px;top:36.015856px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p1_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:213.659700px;top:121.477861px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:76.759067px;top:217.193382px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">サブ リレー ボックス 1</font></nobr>");
write("</p>");
write("<p id=\"p1_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:274.123264px;top:398.548854px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">CAN HI</font></nobr>");
write("</p>");
write("<p id=\"p1_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:272.485078px;top:381.872942px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">CAN LO</font></nobr>");
write("</p>");
write("<p id=\"p1_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:276.818900px;top:343.185634px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ACC L</font></nobr>");
write("</p>");
write("<p id=\"p1_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:277.622102px;top:334.560561px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A15</font></nobr>");
write("</p>");
write("<p id=\"p1_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300.093453px;top:377.198262px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A4</font></nobr>");
write("</p>");
write("<p id=\"p1_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300.313033px;top:393.949199px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A3</font></nobr>");
write("</p>");
write("<p id=\"p1_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298.328142px;top:502.807691px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A10</font></nobr>");
write("</p>");
write("<p id=\"p1_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298.328142px;top:485.657577px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A34</font></nobr>");
write("</p>");
write("<p id=\"p1_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363.589729px;top:485.657577px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:338.454522px;top:485.657577px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281.825910px;top:485.657577px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">TW2</font></nobr>");
write("</p>");
write("<p id=\"p1_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282.461538px;top:502.807691px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">SG6</font></nobr>");
write("</p>");
write("<p id=\"p1_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:76.786033px;top:83.380179px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.47<br>(30A)</font></nobr>");
write("</p>");
write("<p id=\"p1_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:241.347046px;top:42.234335px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">IG2</font></nobr>");
write("</p>");
write("<p id=\"p1_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238.056231px;top:30.799644px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">BAT</font></nobr>");
write("</p>");
write("<p id=\"p1_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:160.956568px;top:529.138837px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">PGM-FI ECU</font></nobr>");
write("</p>");
write("<p id=\"p1_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:277.220502px;top:191.611531px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p1_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212.455860px;top:191.611531px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:277.220502px;top:160.281555px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p1_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212.455860px;top:160.281555px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:152.987150px;top:30.265807px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.60(IG)(50A)</font></nobr>");
write("</p>");
write("<p id=\"p1_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378.760996px;top:160.281555px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327.780799px;top:160.281555px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p1_224\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378.760996px;top:191.611531px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_225\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327.780799px;top:191.611531px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p1_226\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327.138430px;top:264.716413px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">G501</font></nobr>");
write("</p>");
write("<p id=\"p1_227\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287.733392px;top:32.373261px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">S1</font></nobr>");
write("</p>");
write("<p id=\"p1_228\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199.615226px;top:32.373261px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">T1</font></nobr>");
write("</p>");
write("<p id=\"p1_229\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336.929980px;top:217.998466px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">K1</font></nobr>");
write("</p>");
write("<p id=\"p1_230\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:377.711248px;top:217.998466px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">S2</font></nobr>");
write("</p>");
write("<p id=\"p1_231\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:318.552647px;top:393.949199px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">30</font></nobr>");
write("</p>");
write("<p id=\"p1_232\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:318.332104px;top:377.197300px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">29</font></nobr>");
write("</p>");
write("<p id=\"p1_233\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:365.821166px;top:386.396609px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">18</font></nobr>");
write("</p>");
write("<p id=\"p1_234\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366.367227px;top:401.937517px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p1_235\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:329.947710px;top:381.796955px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">CAN LO</font></nobr>");
write("</p>");
write("<p id=\"p1_236\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:329.786878px;top:398.548854px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">CAN HI</font></nobr>");
write("</p>");
write("<p id=\"p1_237\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:417.491885px;top:405.788837px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ECONスイッチ</font></nobr>");
write("</p>");
write("<p id=\"p1_238\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344.876284px;top:390.420104px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B-CAN</font></nobr>");
write("</p>");
write("<p id=\"p1_239\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400.772962px;top:324.005979px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU</font></nobr>");
write("</p>");
write("<p id=\"p1_240\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:414.096094px;top:342.499822px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">Q3</font></nobr>");
write("</p>");
write("<p id=\"p1_241\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114.399759px;top:191.611531px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p1_242\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66.433976px;top:191.611531px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_243\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114.399759px;top:160.281555px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p1_244\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66.433976px;top:160.281555px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_245\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:182.962755px;top:191.611531px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p1_246\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133.778686px;top:191.611531px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_247\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:222.488177px;top:243.625525px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_248\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:182.962755px;top:160.281555px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p1_249\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133.778686px;top:160.281555px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_250\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:75.784439px;top:265.962033px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_251\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:75.784439px;top:240.282071px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_252\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66.313592px;top:535.955598px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">G202</font></nobr>");
write("</p>");
write("<p id=\"p1_253\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143.116629px;top:265.962033px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_254\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143.116629px;top:240.282071px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_255\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:181.558596px;top:343.185634px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">FAN C</font></nobr>");
write("</p>");
write("<p id=\"p1_256\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:183.484739px;top:334.560561px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A6</font></nobr>");
write("</p>");
write("<p id=\"p1_257\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298.328142px;top:415.996185px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A38</font></nobr>");
write("</p>");
write("<p id=\"p1_258\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282.467315px;top:415.998108px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">TAC</font></nobr>");
write("</p>");
write("<p id=\"p1_259\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:416.461399px;top:443.881710px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_260\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:416.461399px;top:468.122717px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_261\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:411.688415px;top:296.894758px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A21</font></nobr>");
write("</p>");
write("<p id=\"p1_262\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:399.409252px;top:333.301475px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B-CAN</font></nobr>");
write("</p>");
write("<p id=\"p1_263\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:44.724415px;top:30.074395px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.1(100A)</font></nobr>");
write("</p>");
write("<p id=\"p1_264\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:115.026718px;top:32.373261px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">T-9</font></nobr>");
write("</p>");
write("<p id=\"p1_265\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300.574989px;top:29.196209px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.10(7.5A)</font></nobr>");
write("</p>");
write("<p id=\"p1_266\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:144.440853px;top:83.380179px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.30<br>(30A)</font></nobr>");
write("</p>");
write("<p id=\"p1_267\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:223.410800px;top:83.380179px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.43<br>(7.5A)</font></nobr>");
write("</p>");
write("<p id=\"p1_268\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378.755218px;top:83.380179px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.57<br>(40A)</font></nobr>");
write("</p>");
write("<p id=\"p1_269\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:399.614386px;top:32.177040px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">Q14</font></nobr>");
write("</p>");
write("<p id=\"p1_270\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:75.582193px;top:108.924517px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A36</font></nobr>");
write("</p>");
write("<p id=\"p1_271\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221.966193px;top:108.924517px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A3</font></nobr>");
write("</p>");
write("<p id=\"p1_272\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143.237013px;top:108.924517px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A22</font></nobr>");
write("</p>");
write("<p id=\"p1_273\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278.183573px;top:108.924517px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A33</font></nobr>");
write("</p>");
write("<p id=\"p1_274\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578.280546px;top:248.519512px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_275\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:557.574507px;top:248.519512px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_276\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:522.823993px;top:229.361979px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A/Cプレッシャ スイッチ<br>（高圧側OFF：3,100kPa(32kgf/cm2)以上）<br>（低圧側OFF：200kPa(2.0kgf/cm2)以下）</font></nobr>");
write("</p>");
write("<p id=\"p1_277\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545.776879px;top:252.440087px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p1_278\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:842.987527px;top:487.112885px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">AVNユニット</font></nobr>");
write("</p>");
write("<p id=\"p1_279\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:743.268201px;top:473.003237px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">32</font></nobr>");
write("</p>");
write("<p id=\"p1_280\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:743.268201px;top:459.790052px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">33</font></nobr>");
write("</p>");
write("<p id=\"p1_281\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:743.268201px;top:429.925000px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">31</font></nobr>");
write("</p>");
write("<p id=\"p1_282\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:814.059744px;top:473.003237px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B18</font></nobr>");
write("</p>");
write("<p id=\"p1_283\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:814.059744px;top:459.790052px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B17</font></nobr>");
write("</p>");
write("<p id=\"p1_284\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:817.092457px;top:429.925000px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B8</font></nobr>");
write("</p>");
write("<p id=\"p1_285\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:717.008126px;top:429.925000px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">NAVI-SI</font></nobr>");
write("</p>");
write("<p id=\"p1_286\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714.600447px;top:462.854564px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">NAVI-SO</font></nobr>");
write("</p>");
write("<p id=\"p1_287\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711.924071px;top:476.325531px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">NAVI-CLK</font></nobr>");
write("</p>");
write("<p id=\"p1_288\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:828.519302px;top:433.741694px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">AC-SI</font></nobr>");
write("</p>");
write("<p id=\"p1_289\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:828.519302px;top:462.854564px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">AC-SO</font></nobr>");
write("</p>");
write("<p id=\"p1_290\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:850.123887px;top:497.790586px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">(NAV.装備車)</font></nobr>");
write("</p>");
write("<p id=\"p1_291\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:828.519302px;top:476.325531px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">AC-CLK</font></nobr>");
write("</p>");
write("<p id=\"p1_292\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761.138958px;top:433.665707px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_293\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761.138958px;top:463.190256px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p1_294\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761.138958px;top:476.433260px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("</v:group>");
}