with(document) {
write("<v:group id=\"group8\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:1092.14px;\" coordsize=\"950.00,1092.14\">");
write("<v:rect id=\"rect8\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:1092.14px;\">");
write("<img id=\"img8\" name=\"PrtImgId\" src=\"../img/4746_2.0_jpn_9504124_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:1092.14px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p8_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260.289048px;top:32.909104px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ヒューズ ボックス</font></nobr>");
write("</p>");
write("<p id=\"p8_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:55.793818px;top:129.012040px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">イグニッション<br>スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p8_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308.880737px;top:363.276675px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ブロア<br>モータ<br>リレー</font></nobr>");
write("</p>");
write("<p id=\"p8_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505.019252px;top:220.721095px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">(内部接続)</font></nobr>");
write("</p>");
write("<p id=\"p8_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358.492007px;top:363.276675px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">リヤ<br>デフロスタ<br>リレー</font></nobr>");
write("</p>");
write("<p id=\"p8_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:615.070508px;top:300.537194px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">オートA/Cコントロール ユニット</font></nobr>");
write("</p>");
write("<p id=\"p8_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:615.386001px;top:230.121423px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">オプション用カプラ</font></nobr>");
write("</p>");
write("<p id=\"p8_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:119.509930px;top:407.702853px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ヒューズ<br>ボックス</font></nobr>");
write("</p>");
write("<p id=\"p8_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66.208933px;top:407.702853px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ヒューズ<br>ボックス</font></nobr>");
write("</p>");
write("<p id=\"p8_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:615.386001px;top:637.265399px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ヘッドライト マニュアル レベリング スイッチ<br>(ディスチャージ ヘッドライト非装備車)</font></nobr>");
write("</p>");
write("<p id=\"p8_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.078066px;top:265.807994px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">サブ リレー ボックス1</font></nobr>");
write("</p>");
write("<p id=\"p8_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:615.386001px;top:586.399610px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ヘッドライト オート レベリング<br>コントロール ユニット<br>(ディスチャージ ヘッドライト装備車)</font></nobr>");
write("</p>");
write("<p id=\"p8_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:615.070508px;top:314.801421px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">内外気切替えモータ(オートA/C装備車)</font></nobr>");
write("</p>");
write("<p id=\"p8_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:108.054074px;top:216.342623px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">IG2</font></nobr>");
write("</p>");
write("<p id=\"p8_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:96.173070px;top:289.749934px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ST</font></nobr>");
write("</p>");
write("<p id=\"p8_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:108.054074px;top:243.434058px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">IG1</font></nobr>");
write("</p>");
write("<p id=\"p8_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:104.799110px;top:187.251692px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ACC</font></nobr>");
write("</p>");
write("<p id=\"p8_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:93.123946px;top:162.897524px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">OFF</font></nobr>");
write("</p>");
write("<p id=\"p8_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45.699967px;top:217.477212px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">BAT</font></nobr>");
write("</p>");
write("<p id=\"p8_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312.433881px;top:700.444075px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU</font></nobr>");
write("</p>");
write("<p id=\"p8_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:613.443026px;top:790.752711px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">SRSユニット(VB)</font></nobr>");
write("</p>");
write("<p id=\"p8_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:613.443026px;top:847.738344px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">PGM-FI ECU</font></nobr>");
write("</p>");
write("<p id=\"p8_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:615.070508px;top:329.319919px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">パワー ミラー スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p8_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37.535624px;top:20.879380px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.60(IGN)(50A)<br>ヒューズ(ヒューズ ボックス)</font></nobr>");
write("</p>");
write("<p id=\"p8_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:615.389848px;top:556.201058px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.ヘッドライト レベリング モータ<br>(ディスチャージ ヘッドライト非装備車)</font></nobr>");
write("</p>");
write("<p id=\"p8_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:615.389848px;top:508.157295px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.ヘッドライト レベリング モータ<br>(ディスチャージ ヘッドライト非装備車)</font></nobr>");
write("</p>");
write("<p id=\"p8_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:613.443026px;top:905.261413px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">SRSユニット(VA)</font></nobr>");
write("</p>");
write("<p id=\"p8_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:612.542718px;top:264.979686px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">8</font></nobr>");
write("</p>");
write("<p id=\"p8_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726.489543px;top:28.285991px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">*：指示ある配線はメーカーの任意の<br>配線色に変更を可能としている</font></nobr>");
write("</p>");
write("<p id=\"p8_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:81.360291px;top:379.890983px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">10</font></nobr>");
write("</p>");
write("<p id=\"p8_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134.401584px;top:379.419041px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">11</font></nobr>");
write("</p>");
write("<p id=\"p8_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324.066721px;top:333.690686px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">K</font></nobr>");
write("</p>");
write("<p id=\"p8_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322.847072px;top:670.632708px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p8_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204.137071px;top:969.877106px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">G</font></nobr>");
write("</p>");
write("<p id=\"p8_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:379.158719px;top:333.690686px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">L</font></nobr>");
write("</p>");
write("<p id=\"p8_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240.561119px;top:439.687082px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.15(未使用)</font></nobr>");
write("</p>");
write("<p id=\"p8_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:250.314469px;top:495.123972px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.5(10A)</font></nobr>");
write("</p>");
write("<p id=\"p8_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:250.314469px;top:777.172320px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.6(10A)</font></nobr>");
write("</p>");
write("<p id=\"p8_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:250.314469px;top:834.188773px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.7(10A)</font></nobr>");
write("</p>");
write("<p id=\"p8_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248.790869px;top:891.214858px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.8(7.5A)</font></nobr>");
write("</p>");
write("<p id=\"p8_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:245.126149px;top:216.240529px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.10(7.5A)</font></nobr>");
write("</p>");
write("<p id=\"p8_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:89.563108px;top:52.432119px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p8_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87.656685px;top:90.168269px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p8_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475.638008px;top:905.323054px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">白*</font></nobr>");
write("</p>");
write("<p id=\"p8_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:82.566474px;top:335.428206px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p8_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:469.385860px;top:509.228316px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p8_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:469.385860px;top:557.389583px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p8_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:469.385860px;top:637.525448px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p8_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:152.198081px;top:258.846358px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p8_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475.157073px;top:791.276664px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫*</font></nobr>");
write("</p>");
write("<p id=\"p8_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:152.198081px;top:230.260116px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p8_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:135.238409px;top:335.428206px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p8_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475.157073px;top:265.170390px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p8_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475.157073px;top:300.036357px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p8_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475.157073px;top:848.295044px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("</v:group>");
}