with(document) {
write("<v:group id=\"group6\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:1092.14px;\" coordsize=\"950.00,1092.14\">");
write("<v:rect id=\"rect6\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:1092.14px;\">");
write("<img id=\"img6\" name=\"PrtImgId\" src=\"../img/4748_2.0_jpn_9504134_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:1092.14px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p6_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530.749242px;top:874.993514px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">：アシスタント ドア ワイヤ ハーネス</font></nobr>");
write("</p>");
write("<p id=\"p6_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298.606054px;top:903.631766px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">：ETCサブ ハーネス</font></nobr>");
write("</p>");
write("<p id=\"p6_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298.606054px;top:875.737064px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">：ケーブル リール サブ ハーネス</font></nobr>");
write("</p>");
write("<p id=\"p6_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66.505189px;top:903.631766px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">：A/Cワイヤ ハーネス</font></nobr>");
write("</p>");
write("<p id=\"p6_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66.505189px;top:874.993514px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">：インストルメント ワイヤ ハーネス</font></nobr>");
write("</p>");
write("<p id=\"p6_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52.444591px;top:845.074275px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">G502</font></nobr>");
write("</p>");
write("<p id=\"p6_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:49.258882px;top:875.097534px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p6_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45.761527px;top:903.730006px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AF</font></nobr>");
write("</p>");
write("<p id=\"p6_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:277.862392px;top:903.730006px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AK</font></nobr>");
write("</p>");
write("<p id=\"p6_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509.692009px;top:875.097534px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AB</font></nobr>");
write("</p>");
write("<p id=\"p6_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.322656px;top:115.974864px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">スマートECU(LG1) </font></nobr>");
write("</p>");
write("<p id=\"p6_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.322656px;top:363.382621px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">アシスタント ドア アウタ ハンドル タッチ センサ/<br>ロック ボタン(Hondaスマート キー システム装備車)</font></nobr>");
write("</p>");
write("<p id=\"p6_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.322656px;top:83.811491px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">キーレス レシーバ ユニット<br>(Hondaスマート キー システム非装備車)</font></nobr>");
write("</p>");
write("<p id=\"p6_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.322656px;top:275.221805px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ハザード スイッチ照明</font></nobr>");
write("</p>");
write("<p id=\"p6_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.322656px;top:412.728561px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">オートA/Cコントロール ユニット</font></nobr>");
write("</p>");
write("<p id=\"p6_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.243783px;top:641.915478px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">パーキング ピン スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p6_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.322656px;top:243.264544px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">データ リンク カプラ(DLC) </font></nobr>");
write("</p>");
write("<p id=\"p6_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.322656px;top:52.697948px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">アクセサリ ソケット</font></nobr>");
write("</p>");
write("<p id=\"p6_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.322656px;top:444.724348px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">オートA/Cコントロール ユニット照明</font></nobr>");
write("</p>");
write("<p id=\"p6_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.322656px;top:480.956061px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">パワー トランジスタ</font></nobr>");
write("</p>");
write("<p id=\"p6_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.322656px;top:148.136313px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">スマートECU(LG2)</font></nobr>");
write("</p>");
write("<p id=\"p6_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.322656px;top:179.829671px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU(PG)</font></nobr>");
write("</p>");
write("<p id=\"p6_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.322656px;top:211.686764px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU(SG)</font></nobr>");
write("</p>");
write("<p id=\"p6_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.322656px;top:20.037590px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">センタ トレイ ライト</font></nobr>");
write("</p>");
write("<p id=\"p6_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.122587px;top:746.819665px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">舵角センサ</font></nobr>");
write("</p>");
write("<p id=\"p6_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.322656px;top:313.884504px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.パワー ミラー</font></nobr>");
write("</p>");
write("<p id=\"p6_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.243783px;top:672.953896px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">D3スイッチ(A/T車)</font></nobr>");
write("</p>");
write("<p id=\"p6_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.243783px;top:688.886295px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Sスイッチ(CVT車)</font></nobr>");
write("</p>");
write("<p id=\"p6_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.322656px;top:563.881202px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">オーディオ リモート スイッチ(NAV.装備車)</font></nobr>");
write("</p>");
write("<p id=\"p6_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.322656px;top:578.519130px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">NAV.ガイド/HFTスイッチ(NAV.装備車)</font></nobr>");
write("</p>");
write("<p id=\"p6_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.322656px;top:533.203003px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">オーディオ ユニット(NAV.非装備車)</font></nobr>");
write("</p>");
write("<p id=\"p6_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622.205651px;top:610.491801px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">TVチューナ(NAV.装備車)</font></nobr>");
write("</p>");
write("<p id=\"p6_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.322656px;top:519.196900px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AVNユニット(NAV.装備車)</font></nobr>");
write("</p>");
write("<p id=\"p6_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171.368126px;top:364.156993px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:187.085062px;top:363.702386px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p6_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171.368126px;top:313.724621px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:187.085062px;top:313.273869px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p6_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278.487606px;top:20.617404px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294.206466px;top:20.164725px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p6_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278.408733px;top:641.601492px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294.127593px;top:641.146886px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p6_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278.487606px;top:211.850499px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294.206466px;top:211.393967px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p6_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278.487606px;top:243.723002px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294.206466px;top:243.264544px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p6_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278.408733px;top:673.475921px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294.127593px;top:673.021315px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p6_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278.487606px;top:84.360485px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294.206466px;top:83.907805px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p6_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278.487606px;top:148.105493px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294.206466px;top:147.648959px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p6_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278.487606px;top:275.589727px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294.206466px;top:275.135121px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p6_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278.487606px;top:519.008124px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294.206466px;top:518.553518px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p6_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171.364279px;top:564.370482px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:187.081215px;top:563.913950px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p6_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278.487606px;top:52.489908px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294.206466px;top:52.035302px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p6_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278.487606px;top:413.366166px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294.206466px;top:412.913486px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p6_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279.370603px;top:609.728989px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.089462px;top:609.276309px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p6_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278.487606px;top:445.240595px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294.206466px;top:444.784063px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p6_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278.487606px;top:116.232989px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294.206466px;top:115.776456px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p6_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278.487606px;top:179.976070px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294.206466px;top:179.523390px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p6_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278.293309px;top:746.584656px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294.008321px;top:746.130050px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p6_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.122587px;top:714.941382px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">シフト ポジション インジケータ パネル ライト</font></nobr>");
write("</p>");
write("<p id=\"p6_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278.293309px;top:714.708301px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294.008321px;top:714.251769px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p6_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.122587px;top:778.696020px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ETCユニット(NAV.装備車)</font></nobr>");
write("</p>");
write("<p id=\"p6_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171.368126px;top:480.888640px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:187.085062px;top:480.432108px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p6_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382.511793px;top:363.498199px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398.230653px;top:363.043593px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AB</font></nobr>");
write("</p>");
write("<p id=\"p6_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382.511793px;top:313.724621px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398.230653px;top:313.273869px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AB</font></nobr>");
write("</p>");
write("<p id=\"p6_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382.477167px;top:480.983029px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398.517290px;top:480.526496px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AF</font></nobr>");
write("</p>");
write("<p id=\"p6_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171.368126px;top:778.474497px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:187.085062px;top:778.023744px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p6_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382.477167px;top:778.572737px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398.517290px;top:778.114279px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AK</font></nobr>");
write("</p>");
write("<p id=\"p6_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281.888775px;top:875.124503px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">R</font></nobr>");
write("</p>");
write("<p id=\"p6_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256.903271px;top:586.101034px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ケーブル リール</font></nobr>");
write("</p>");
write("<p id=\"p6_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382.479090px;top:564.366630px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p6_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398.744291px;top:563.906245px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">R</font></nobr>");
write("</p>");
write("</v:group>");
}