with(document) {
write("<v:group id=\"group3\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:1092.14px;\" coordsize=\"950.00,1092.14\">");
write("<v:rect id=\"rect3\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:1092.14px;\">");
write("<img id=\"img3\" name=\"PrtImgId\" src=\"../img/4765_2.0_jpn_9503803_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:1092.14px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p3_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642.310658px;top:346.732355px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">コンデンサ ファン モータ</font></nobr>");
write("</p>");
write("<p id=\"p3_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642.310658px;top:382.896715px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ラジエータ ファン モータ</font></nobr>");
write("</p>");
write("<p id=\"p3_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642.310658px;top:576.126627px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">VSAモジュレータ コントロール ユニット<br>(GND)</font></nobr>");
write("</p>");
write("<p id=\"p3_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642.310658px;top:540.291226px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">VSAモジュレータ コントロール ユニット<br>(MR-GND)</font></nobr>");
write("</p>");
write("<p id=\"p3_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:53.046475px;top:665.497744px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">G203</font></nobr>");
write("</p>");
write("<p id=\"p3_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642.310658px;top:296.876749px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.フロント ポジション ライト</font></nobr>");
write("</p>");
write("<p id=\"p3_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642.310658px;top:192.875600px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.フードCOMP<br>(ディスチャージ ヘッドライト装備車)</font></nobr>");
write("</p>");
write("<p id=\"p3_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52.886592px;top:132.543313px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">G201</font></nobr>");
write("</p>");
write("<p id=\"p3_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642.310658px;top:228.343565px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.ヘッドライト レベリング モータ<br>(ディスチャージ ヘッドライト非装備車)</font></nobr>");
write("</p>");
write("<p id=\"p3_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642.310658px;top:310.292901px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.フロント ターン シグナル ライト</font></nobr>");
write("</p>");
write("<p id=\"p3_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642.310658px;top:255.608710px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.ヘッドライト<br>(ディスチャージ ヘッドライト非装備車)</font></nobr>");
write("</p>");
write("<p id=\"p3_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52.886592px;top:482.069281px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">G202</font></nobr>");
write("</p>");
write("<p id=\"p3_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:90.277841px;top:724.943188px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.キャビン ワイヤ ハーネス</font></nobr>");
write("</p>");
write("<p id=\"p3_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83.177529px;top:723.602342px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">:</font></nobr>");
write("</p>");
write("<p id=\"p3_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298.178649px;top:63.508034px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p3_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317.449271px;top:63.055956px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">I</font></nobr>");
write("</p>");
write("<p id=\"p3_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298.178649px;top:191.990680px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p3_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317.449271px;top:191.540525px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">I</font></nobr>");
write("</p>");
write("<p id=\"p3_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298.178649px;top:345.908996px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p3_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317.449271px;top:345.453069px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">I</font></nobr>");
write("</p>");
write("<p id=\"p3_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298.178649px;top:296.113024px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p3_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317.449271px;top:295.660946px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">I</font></nobr>");
write("</p>");
write("<p id=\"p3_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298.178649px;top:227.695266px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p3_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317.449271px;top:227.241263px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">I</font></nobr>");
write("</p>");
write("<p id=\"p3_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298.178649px;top:381.469300px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p3_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317.449271px;top:381.015298px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">I</font></nobr>");
write("</p>");
write("<p id=\"p3_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298.178649px;top:539.864156px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p3_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317.449271px;top:539.414001px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">I</font></nobr>");
write("</p>");
write("<p id=\"p3_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298.178649px;top:575.568743px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p3_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317.449271px;top:575.112816px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">I</font></nobr>");
write("</p>");
write("<p id=\"p3_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67.410832px;top:724.548821px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">I</font></nobr>");
write("</p>");
write("</v:group>");
}