with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:1092.14px;\" coordsize=\"950.00,1092.14\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:1092.14px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/4782_2.0_jpn_9504140_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:1092.14px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262.895429px;top:157.954646px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">シフト ロック リレー </font></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:222.941366px;top:226.787003px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">シフト ロック<br>ソレノイド</font></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254.781112px;top:254.826176px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">PGM-FI ECU</font></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199.816142px;top:5.607701px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">イグニッション<br>スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:741.266892px;top:495.172129px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">回転<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:731.003763px;top:599.660237px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">前後<br>スライド<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:801.874179px;top:182.807725px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ロック<br>アクチュエータ</font></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:764.176658px;top:240.074598px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">昇降<br>スライド<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:819.662961px;top:314.348742px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">昇降<br>スライド<br>センサ</font></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:732.446565px;top:701.757809px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">外<br>スライド<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:702.370883px;top:819.751180px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">リクライニング<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:546.294374px;top:467.705067px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">回転出力(振出)</font></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536.289025px;top:157.197612px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ロック出力(解除)</font></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536.289025px;top:215.645304px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ロック出力(施錠)</font></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:498.264469px;top:240.590845px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">昇降スライド コントロール</font></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:507.431069px;top:319.802087px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">昇降スライド出力(上昇)</font></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:507.431069px;top:413.770688px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">昇降スライド出力(下降)</font></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578.414985px;top:398.225474px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">電流検出</font></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527.120502px;top:441.894618px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">昇降スライド パルス</font></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:546.294374px;top:525.493964px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">回転出力(格納)</font></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568.417332px;top:551.502821px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">回転パルス</font></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506.855871px;top:577.091745px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">前後スライド出力(前進)</font></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506.855871px;top:636.263723px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">前後スライド出力(後退)</font></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:526.093226px;top:660.471492px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">前後スライド パルス</font></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516.474549px;top:679.894342px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">外スライド出力(振出)</font></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:517.307528px;top:739.324444px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">外スライド出力(格納)</font></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536.996959px;top:765.329448px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">外スライド パルス</font></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:498.070171px;top:792.301454px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">リクライニング出力(前傾)</font></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:498.070171px;top:852.018574px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">リクライニング出力(後傾)</font></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:517.757681px;top:877.060430px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">リクライニング パルス</font></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:569.056012px;top:901.686206px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">センサ電源</font></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367.381199px;top:279.326743px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">VMP1</font></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367.381199px;top:145.998124px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">IG1</font></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367.381199px;top:298.720697px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">VMP2</font></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367.381199px;top:316.057367px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">VBU</font></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:426.055133px;top:133.488754px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">リフタ コントロール ユニット</font></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367.381199px;top:364.214781px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">振出</font></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367.381199px;top:389.260490px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">格納</font></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367.381199px;top:427.786421px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">前傾</font></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367.381199px;top:453.795279px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">後傾</font></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367.381199px;top:491.359988px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">前スライド</font></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367.381199px;top:513.512399px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">後スライド</font></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367.381199px;top:974.305661px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">SG</font></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367.381199px;top:1008.980926px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">PG1</font></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367.381199px;top:1044.621266px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">PG2</font></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:412.588984px;top:951.924021px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ブザー</font></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158.228827px;top:62.306316px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">60A</font></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158.586642px;top:149.089830px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">40A</font></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:98.964307px;top:62.323652px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">10A</font></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128.903402px;top:61.946098px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">30A</font></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:302.745610px;top:270.313602px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">30A</font></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22.182252px;top:4.548238px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ヒューズ ボックス</font></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:157.039959px;top:178.448517px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ヒューズ<br>ホルダ</font></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:54.225914px;top:162.747273px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">バッテリ</font></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177.822073px;top:345.562451px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">回転昇降スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176.923688px;top:409.968179px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">リクライニング スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177.885556px;top:471.613522px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">シート スライド スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128.410927px;top:543.635826px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">回転リミット スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128.410927px;top:577.787138px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">前後スライド リミット スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128.410927px;top:610.499507px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">外スライド リミット スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128.410927px;top:644.018994px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">リクライニング リミット スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258.280388px;top:840.416491px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ドア スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:236.420981px;top:891.954555px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">シフト ポジション センサ</font></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264.297832px;top:935.234587px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">SCSカプラ</font></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367.381199px;top:337.246629px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">スイッチ GND</font></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367.381199px;top:178.415769px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">シフト ロック リレー出力</font></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367.381199px;top:817.880746px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">リミット スイッチ GND</font></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:563.986970px;top:928.914408px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">センサGND</font></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:692.609849px;top:949.562382px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">リモコン レシーバ ユニット</font></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:874.189320px;top:995.797353px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">VBU</font></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:821.584773px;top:618.208546px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">前後<br>スライド<br>センサ</font></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:821.711739px;top:719.990206px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">外<br>スライド<br>センサ</font></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:560.035617px;top:963.597379px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">IG1信号出力</font></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510.761054px;top:996.473483px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">トランスミッタ通信信号</font></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:789.450694px;top:1036.561641px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.パワー スライド ドア<br>コントロール ユニット</font></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:485.385060px;top:1025.722370px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">パワー スライド ドア半開入力</font></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:549.503164px;top:1058.596547px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ロック状態出力</font></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128.410927px;top:676.265199px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">昇降スライド リミット スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128.410927px;top:710.416511px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">フック リミット スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128.410927px;top:743.128880px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ロックINNリミット スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128.410927px;top:776.648368px;font-weight:normal;font-size:6.0pt;color:black;\" prt_font_size=\"7.3pt\" disp_font_size=\"6.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">ロックOFFリミット スイッチ</font></nobr>");
write("</p>");
write("</v:group>");
}