with(document) {
write("<v:group id=\"group21\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:493.10px;\" coordsize=\"950.00,493.10\">");
write("<v:rect id=\"rect21\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:493.10px;\">");
write("<img id=\"img21\" name=\"PrtImgId\" src=\"../img/4926_2.0_jpn_9502805_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:493.10px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p21_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:587.321584px;top:20.799953px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C</font></nobr>");
write("</p>");
write("<p id=\"p21_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131.331540px;top:20.799953px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A</font></nobr>");
write("</p>");
write("<p id=\"p21_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359.327240px;top:20.799953px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B</font></nobr>");
write("</p>");
write("<p id=\"p21_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815.316606px;top:20.799953px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">D</font></nobr>");
write("</p>");
write("<p id=\"p21_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:33.118748px;top:325.881421px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G202</font></nobr>");
write("</p>");
write("<p id=\"p21_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66.821759px;top:325.881421px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G202</font></nobr>");
write("</p>");
write("<p id=\"p21_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:188.621715px;top:209.869845px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">171</font></nobr>");
write("</p>");
write("<p id=\"p21_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256.898777px;top:209.677606px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">64</font></nobr>");
write("</p>");
write("<p id=\"p21_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:161.529395px;top:209.869845px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">181</font></nobr>");
write("</p>");
write("<p id=\"p21_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:159.521126px;top:372.238804px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G502</font></nobr>");
write("</p>");
write("<p id=\"p21_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341.850225px;top:372.238804px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G502</font></nobr>");
write("</p>");
write("<p id=\"p21_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378.311303px;top:372.238804px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G502</font></nobr>");
write("</p>");
write("<p id=\"p21_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:543.254147px;top:227.072539px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G502</font></nobr>");
write("</p>");
write("<p id=\"p21_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:575.172407px;top:227.072539px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G502</font></nobr>");
write("</p>");
write("<p id=\"p21_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:829.635255px;top:227.072539px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G502</font></nobr>");
write("</p>");
write("<p id=\"p21_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537.273368px;top:231.742461px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">14</font></nobr>");
write("</p>");
write("<p id=\"p21_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:569.191628px;top:231.742461px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">36</font></nobr>");
write("</p>");
write("<p id=\"p21_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:887.155043px;top:338.834548px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p21_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:887.155043px;top:318.327912px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p21_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:159.779865px;top:199.438841px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(13-C)</font></nobr>");
write("</p>");
write("<p id=\"p21_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380.522768px;top:209.869845px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">181</font></nobr>");
write("</p>");
write("<p id=\"p21_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378.570041px;top:199.438841px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(13-C)</font></nobr>");
write("</p>");
write("<p id=\"p21_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331.489862px;top:107.491678px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">32</font></nobr>");
write("</p>");
write("<p id=\"p21_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:320.696012px;top:97.252914px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ブロア モータ<br>リレー(1-C)</font></nobr>");
write("</p>");
write("<p id=\"p21_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:708.239663px;top:238.579134px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">Teva</font></nobr>");
write("</p>");
write("<p id=\"p21_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715.107738px;top:231.742461px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">23</font></nobr>");
write("</p>");
write("<p id=\"p21_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:639.147102px;top:238.579134px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ACS</font></nobr>");
write("</p>");
write("<p id=\"p21_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645.866842px;top:231.742461px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">26</font></nobr>");
write("</p>");
write("<p id=\"p21_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510.281292px;top:147.738023px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p21_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505.210838px;top:154.874562px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">IG2</font></nobr>");
write("</p>");
write("<p id=\"p21_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:501.891268px;top:166.429217px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">内外気<br>切換え<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p21_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519.333740px;top:193.723112px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p21_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:502.653259px;top:193.723112px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p21_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512.643124px;top:187.247902px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FRS</font></nobr>");
write("</p>");
write("<p id=\"p21_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:496.332462px;top:187.247902px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">REC</font></nobr>");
write("</p>");
write("<p id=\"p21_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:495.789248px;top:238.531751px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">REC</font></nobr>");
write("</p>");
write("<p id=\"p21_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512.901862px;top:238.531751px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FRS</font></nobr>");
write("</p>");
write("<p id=\"p21_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734.362053px;top:238.579134px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">Rr DEF<br>RLY</font></nobr>");
write("</p>");
write("<p id=\"p21_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:771.868244px;top:231.742461px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p21_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679.344981px;top:255.895548px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">オートA/Cコントロール ユニット</font></nobr>");
write("</p>");
write("<p id=\"p21_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:790.379535px;top:231.743138px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">15</font></nobr>");
write("</p>");
write("<p id=\"p21_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:806.747091px;top:231.743138px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">34</font></nobr>");
write("</p>");
write("<p id=\"p21_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:808.743845px;top:166.120551px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">パワー<br>トランジスタ</font></nobr>");
write("</p>");
write("<p id=\"p21_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:836.875859px;top:170.222555px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p21_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:837.333053px;top:197.564510px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p21_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805.814415px;top:184.570092px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p21_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805.814415px;top:175.456333px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p21_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607.358888px;top:360.018759px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p21_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:612.817449px;top:362.988989px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">S-COM</font></nobr>");
write("</p>");
write("<p id=\"p21_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714.789395px;top:346.348120px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p21_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720.247956px;top:349.317673px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">S-COM</font></nobr>");
write("</p>");
write("<p id=\"p21_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:890.666973px;top:326.676100px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">外気温<br>センサ</font></nobr>");
write("</p>");
write("<p id=\"p21_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:825.122239px;top:326.531920px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">内気温<br>センサ</font></nobr>");
write("</p>");
write("<p id=\"p21_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:770.754722px;top:361.614208px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">湿度/内気温<br>センサ</font></nobr>");
write("</p>");
write("<p id=\"p21_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:799.706976px;top:326.602318px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">湿度<br>センサ</font></nobr>");
write("</p>");
write("<p id=\"p21_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820.848997px;top:279.593082px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">20</font></nobr>");
write("</p>");
write("<p id=\"p21_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:887.155043px;top:279.593082px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">22</font></nobr>");
write("</p>");
write("<p id=\"p21_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820.833418px;top:361.599993px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p21_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820.664087px;top:311.389705px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p21_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:792.216439px;top:311.389705px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p21_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:778.669941px;top:311.389705px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p21_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:863.890286px;top:279.593082px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">19</font></nobr>");
write("</p>");
write("<p id=\"p21_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:848.853673px;top:341.113665px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">日射<br>センサ</font></nobr>");
write("</p>");
write("<p id=\"p21_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:712.053680px;top:279.593082px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p21_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:697.943647px;top:279.593082px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p21_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:683.834968px;top:279.593082px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">12</font></nobr>");
write("</p>");
write("<p id=\"p21_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:669.726967px;top:279.593082px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">13</font></nobr>");
write("</p>");
write("<p id=\"p21_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720.247956px;top:328.811037px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">AMD-P</font></nobr>");
write("</p>");
write("<p id=\"p21_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720.247956px;top:321.973687px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">S5V</font></nobr>");
write("</p>");
write("<p id=\"p21_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720.247956px;top:342.480999px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">M-COOL</font></nobr>");
write("</p>");
write("<p id=\"p21_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720.247956px;top:335.645003px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">M-HOT</font></nobr>");
write("</p>");
write("<p id=\"p21_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714.789395px;top:325.829300px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p21_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714.789395px;top:319.005488px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p21_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714.789395px;top:339.512123px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p21_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714.789395px;top:332.678158px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p21_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738.669163px;top:332.911010px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">エア<br>ミックス<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p21_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506.289139px;top:279.593082px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p21_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:604.623850px;top:279.593082px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">11</font></nobr>");
write("</p>");
write("<p id=\"p21_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588.234618px;top:279.593082px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">10</font></nobr>");
write("</p>");
write("<p id=\"p21_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571.843355px;top:279.593082px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">27</font></nobr>");
write("</p>");
write("<p id=\"p21_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:555.456156px;top:279.593082px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">28</font></nobr>");
write("</p>");
write("<p id=\"p21_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:522.677693px;top:279.593082px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">30</font></nobr>");
write("</p>");
write("<p id=\"p21_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:539.068279px;top:279.593082px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">29</font></nobr>");
write("</p>");
write("<p id=\"p21_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632.077184px;top:339.749037px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">モード<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p21_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:612.817449px;top:328.811037px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">M-DEF</font></nobr>");
write("</p>");
write("<p id=\"p21_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:612.817449px;top:321.973687px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">M-VENT</font></nobr>");
write("</p>");
write("<p id=\"p21_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:612.817449px;top:356.151638px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MODE 4</font></nobr>");
write("</p>");
write("<p id=\"p21_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:612.817449px;top:342.480999px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MODE 2</font></nobr>");
write("</p>");
write("<p id=\"p21_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:612.817449px;top:349.317673px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MODE 3</font></nobr>");
write("</p>");
write("<p id=\"p21_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:612.817449px;top:335.645003px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MODE 1</font></nobr>");
write("</p>");
write("<p id=\"p21_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607.358888px;top:325.829300px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p21_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607.358888px;top:319.005488px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p21_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607.358888px;top:353.184793px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p21_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607.358888px;top:339.512123px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p21_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607.358888px;top:346.348120px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p21_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:607.358888px;top:332.678158px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p21_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622.797832px;top:231.742461px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">17</font></nobr>");
write("</p>");
write("<p id=\"p21_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:599.075881px;top:231.742461px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">18</font></nobr>");
write("</p>");
write("<p id=\"p21_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:743.421275px;top:231.742461px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p21_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:863.185191px;top:311.824273px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4*<sup>2</sup></font></nobr>");
write("</p>");
write("<p id=\"p21_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:863.185191px;top:316.380476px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1*<sup>3</sup></font></nobr>");
write("</p>");
write("<p id=\"p21_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:863.471022px;top:341.113665px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p21_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530.247476px;top:238.579134px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">GND</font></nobr>");
write("</p>");
write("<p id=\"p21_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:498.487033px;top:268.707880px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">S-<br>COM </font></nobr>");
write("</p>");
write("<p id=\"p21_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:661.049758px;top:268.690957px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">M-<br>COOL </font></nobr>");
write("</p>");
write("<p id=\"p21_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:676.557789px;top:268.690957px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">M-<br>HOT </font></nobr>");
write("</p>");
write("<p id=\"p21_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:529.722549px;top:273.095535px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">MODE3</font></nobr>");
write("</p>");
write("<p id=\"p21_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:546.109749px;top:273.095535px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">MODE2</font></nobr>");
write("</p>");
write("<p id=\"p21_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:562.881669px;top:273.095535px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">MODE1</font></nobr>");
write("</p>");
write("<p id=\"p21_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:579.373854px;top:273.095535px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M-DEF</font></nobr>");
write("</p>");
write("<p id=\"p21_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:594.408435px;top:273.095535px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M-VENT</font></nobr>");
write("</p>");
write("<p id=\"p21_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512.800941px;top:273.095535px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">MODE4</font></nobr>");
write("</p>");
write("<p id=\"p21_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689.082204px;top:272.757086px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">AMD-P</font></nobr>");
write("</p>");
write("<p id=\"p21_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705.900860px;top:272.757086px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">S5V</font></nobr>");
write("</p>");
write("<p id=\"p21_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:816.724765px;top:272.757086px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">Tr</font></nobr>");
write("</p>");
write("<p id=\"p21_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:857.397449px;top:272.757086px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">Tsun</font></nobr>");
write("</p>");
write("<p id=\"p21_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:880.998159px;top:272.757086px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">Tam</font></nobr>");
write("</p>");
write("<p id=\"p21_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:590.018692px;top:238.579134px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">SMALL</font></nobr>");
write("</p>");
write("<p id=\"p21_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:617.125236px;top:238.579134px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">IG2</font></nobr>");
write("</p>");
write("<p id=\"p21_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:762.809023px;top:238.579134px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B-CAN</font></nobr>");
write("</p>");
write("<p id=\"p21_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:781.502514px;top:238.579134px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">BLW-V</font></nobr>");
write("</p>");
write("<p id=\"p21_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:798.093588px;top:238.579134px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">BLW-G</font></nobr>");
write("</p>");
write("<p id=\"p21_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:563.317866px;top:238.579134px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ILL-</font></nobr>");
write("</p>");
write("<p id=\"p21_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645.866164px;top:205.148479px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p21_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645.866164px;top:218.820471px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p21_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:170.255372px;top:291.840880px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">照明<br>(1.12W)</font></nobr>");
write("</p>");
write("<p id=\"p21_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264.420470px;top:278.393618px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">インジケータ<br>ライト<br>(1.12W)</font></nobr>");
write("</p>");
write("<p id=\"p21_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431.228668px;top:290.658339px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ヒータ<br>コントロール<br>ユニット</font></nobr>");
write("</p>");
write("<p id=\"p21_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408.156271px;top:289.548226px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">照明<br>(3W×3)</font></nobr>");
write("</p>");
write("<p id=\"p21_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340.512508px;top:140.209559px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ブロア<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p21_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317.619603px;top:313.339172px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ヒータ ファン<br>スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p21_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167.367936px;top:262.717329px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p21_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167.367936px;top:326.844648px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p21_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194.510378px;top:326.844648px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p21_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265.691809px;top:326.844648px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A/Cスイッチ</font></nobr>");
write("</p>");
write("<p id=\"p21_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262.184621px;top:262.717329px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p21_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194.510378px;top:262.717329px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p21_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335.972399px;top:152.240074px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p21_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335.972399px;top:131.727346px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p21_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367.743679px;top:313.336464px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A7</font></nobr>");
write("</p>");
write("<p id=\"p21_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386.003682px;top:313.336464px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A4</font></nobr>");
write("</p>");
write("<p id=\"p21_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393.115594px;top:277.801332px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B1</font></nobr>");
write("</p>");
write("<p id=\"p21_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393.115594px;top:306.147127px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B2</font></nobr>");
write("</p>");
write("<p id=\"p21_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349.588662px;top:313.336464px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A1</font></nobr>");
write("</p>");
write("<p id=\"p21_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:371.664713px;top:270.146965px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A2</font></nobr>");
write("</p>");
write("<p id=\"p21_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385.330421px;top:270.146965px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A3</font></nobr>");
write("</p>");
write("<p id=\"p21_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362.578399px;top:270.146965px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A8</font></nobr>");
write("</p>");
write("<p id=\"p21_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349.362435px;top:270.146965px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A6</font></nobr>");
write("</p>");
write("<p id=\"p21_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335.320135px;top:270.146965px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A5</font></nobr>");
write("</p>");
write("<p id=\"p21_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363.205602px;top:240.563800px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p21_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349.588662px;top:240.563800px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p21_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335.970367px;top:240.563800px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p21_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335.970367px;top:179.043217px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p21_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321.367241px;top:289.671421px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">OFF</font></nobr>");
write("</p>");
write("<p id=\"p21_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350.840358px;top:174.919552px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ブロア<br>レジスタ</font></nobr>");
write("</p>");
write("<p id=\"p21_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335.230051px;top:281.644084px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p21_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349.585275px;top:279.398135px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p21_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:372.262791px;top:291.237087px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p21_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363.412863px;top:282.110467px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p21_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:186.656118px;top:199.438841px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(12-C)</font></nobr>");
write("</p>");
write("<p id=\"p21_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194.313276px;top:232.027435px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p21_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194.313276px;top:245.699428px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p21_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:198.871673px;top:236.214728px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A/Cプレッシャ スイッチ<br>(高圧側OFF:<br>3,100kpa(32kgf/cm<sup>2</sup>)以上)<br>(低圧側OFF:<br>200kpa(2.0kgf/cm<sup>2</sup>)以下)</font></nobr>");
write("</p>");
write("<p id=\"p21_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483.000676px;top:88.772054px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(オートA/C装備車)</font></nobr>");
write("</p>");
write("<p id=\"p21_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141.483964px;top:88.772054px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(オートA/C非装備車)</font></nobr>");
write("</p>");
write("<p id=\"p21_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112.784352px;top:273.588994px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">コンプレッサ<br>クラッチ</font></nobr>");
write("</p>");
write("<p id=\"p21_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112.784352px;top:239.411042px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">サーマル<br>プロテクタ</font></nobr>");
write("</p>");
write("<p id=\"p21_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79.081341px;top:237.131249px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ラジエータ<br>ファン<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p21_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74.520235px;top:230.296606px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p21_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:107.940124px;top:233.258036px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p21_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74.617769px;top:250.803241px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p21_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40.817223px;top:250.803241px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p21_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40.817223px;top:230.296606px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p21_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45.376975px;top:237.131249px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">コンデンサ<br>ファン<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p21_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649.814969px;top:207.873672px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A/Cプレッシャ スイッチ<br>(高圧側OFF:<br>3,100kpa(32kgf/cm<sup>2</sup>)以上)<br>(低圧側OFF:<br>200kpa(2.0kgf/cm<sup>2</sup>)以下)</font></nobr>");
write("</p>");
write("<p id=\"p21_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36.390227px;top:188.073041px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">95</font></nobr>");
write("</p>");
write("<p id=\"p21_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:25.309869px;top:173.802670px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">コンデンサ<br>ファン リレー<br>(3-A )</font></nobr>");
write("</p>");
write("<p id=\"p21_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70.285599px;top:188.073041px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">96</font></nobr>");
write("</p>");
write("<p id=\"p21_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:59.690205px;top:173.802670px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ラジエータ<br>ファン リレー<br>(3-A )</font></nobr>");
write("</p>");
write("<p id=\"p21_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:103.988610px;top:188.073041px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">93</font></nobr>");
write("</p>");
write("<p id=\"p21_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:90.007269px;top:173.802670px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A/Cコンプレッサ<br>クラッチ リレー<br>(3-A )</font></nobr>");
write("</p>");
write("<p id=\"p21_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:247.758955px;top:195.407912px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.10(7.5A)*<sup>1</sup><br>ヒューズ<br>(2-C)</font></nobr>");
write("</p>");
write("<p id=\"p21_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:640.445533px;top:182.980058px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">171</font></nobr>");
write("</p>");
write("<p id=\"p21_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.574353px;top:172.741294px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(12-C)</font></nobr>");
write("</p>");
write("<p id=\"p21_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:709.414821px;top:182.980058px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">109</font></nobr>");
write("</p>");
write("<p id=\"p21_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:700.888655px;top:172.741294px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">PGM-FI ECU<br>(TAC)(4-C)</font></nobr>");
write("</p>");
write("<p id=\"p21_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766.175328px;top:182.980058px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">116</font></nobr>");
write("</p>");
write("<p id=\"p21_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:752.907887px;top:172.741294px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">コンビネーション<br>メータ(6-B)</font></nobr>");
write("</p>");
write("<p id=\"p21_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593.385675px;top:182.980058px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">181</font></nobr>");
write("</p>");
write("<p id=\"p21_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:590.784747px;top:172.741294px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(13-C)</font></nobr>");
write("</p>");
write("<p id=\"p21_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609.316357px;top:168.710364px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.10(7.5A)*<sup>1</sup><br>ヒューズ<br>(2-C)</font></nobr>");
write("</p>");
write("<p id=\"p21_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506.165866px;top:118.077014px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">64</font></nobr>");
write("</p>");
write("<p id=\"p21_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:497.021979px;top:103.806644px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.10(7.5A)*<sup>1</sup><br>ヒューズ<br>(2-C)</font></nobr>");
write("</p>");
write("<p id=\"p21_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:739.083008px;top:182.980058px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">47</font></nobr>");
write("</p>");
write("<p id=\"p21_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:618.460243px;top:182.980058px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">64</font></nobr>");
write("</p>");
write("<p id=\"p21_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:730.447115px;top:164.648974px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">リヤ<br>デフロスタ<br>リレー<br>(2-B)</font></nobr>");
write("</p>");
write("<p id=\"p21_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36.505373px;top:211.325853px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p21_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:190.000071px;top:225.573209px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p21_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:190.000071px;top:254.235793px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p21_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256.922484px;top:254.235793px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p21_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:162.907751px;top:254.235793px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p21_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:162.907751px;top:332.701849px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p21_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345.236849px;top:332.701849px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p21_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299.234972px;top:339.797774px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p21_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381.697928px;top:332.701849px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p21_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331.513569px;top:254.235793px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p21_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331.513569px;top:171.952707px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p21_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331.513569px;top:157.551018px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p21_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331.513569px;top:123.468510px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p21_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345.236849px;top:254.235793px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p21_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358.903234px;top:254.235793px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p21_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:368.031542px;top:254.235793px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p21_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381.697928px;top:254.235793px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p21_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:532.960840px;top:205.239183px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p21_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506.189572px;top:136.135985px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p21_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518.369907px;top:291.206627px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p21_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:534.758460px;top:291.206627px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p21_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551.148369px;top:291.206627px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p21_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567.536923px;top:291.206627px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p21_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:583.925477px;top:291.206627px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p21_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:600.314709px;top:291.206627px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p21_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:665.417826px;top:291.206627px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p21_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679.527859px;top:291.206627px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p21_224\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693.635860px;top:291.206627px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p21_225\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:707.744538px;top:291.206627px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p21_226\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:707.744538px;top:313.155732px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p21_227\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:741.421811px;top:301.883344px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p21_228\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:816.806721px;top:291.206627px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p21_229\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:792.642477px;top:279.593082px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">24</font></nobr>");
write("</p>");
write("<p id=\"p21_230\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:785.829943px;top:272.757086px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">HUM</font></nobr>");
write("</p>");
write("<p id=\"p21_231\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:788.599524px;top:291.206627px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p21_232\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:859.577758px;top:291.206627px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p21_233\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:882.842515px;top:291.206627px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p21_234\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564.879100px;top:205.239183px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p21_235\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:594.764031px;top:205.239183px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p21_236\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519.077034px;top:231.742461px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">9</font></nobr>");
write("</p>");
write("<p id=\"p21_237\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:514.765860px;top:205.239183px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p21_238\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:502.292244px;top:231.742461px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">8</font></nobr>");
write("</p>");
write("<p id=\"p21_239\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:497.981071px;top:205.239183px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p21_240\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:618.483949px;top:205.239183px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p21_241\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710.793855px;top:205.239183px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p21_242\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:739.107392px;top:205.239183px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p21_243\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:786.066329px;top:205.239183px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p21_244\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:802.433886px;top:205.239183px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p21_245\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:833.020525px;top:205.239183px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p21_246\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:641.552959px;top:199.015103px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p21_247\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:641.552959px;top:224.990400px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p21_248\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70.208384px;top:211.325853px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p21_249\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36.505373px;top:274.885254px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p21_250\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70.208384px;top:274.885254px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p21_251\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:103.911395px;top:211.325853px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p21_252\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:832.996142px;top:106.901423px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">32</font></nobr>");
write("</p>");
write("<p id=\"p21_253\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:822.198228px;top:96.662658px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ブロア モータ<br>リレー(1-C)</font></nobr>");
write("</p>");
write("<p id=\"p21_254\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:842.014046px;top:139.619304px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ブロア<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p21_255\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:837.474614px;top:151.649819px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p21_256\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:837.474614px;top:131.136414px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p21_257\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:833.020525px;top:156.960763px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p21_258\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:833.020525px;top:122.878254px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p21_259\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705.747107px;top:371.419757px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p21_260\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765.523064px;top:205.239183px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p21_261\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:499.950732px;top:291.206627px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p21_262\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:814.775424px;top:371.419757px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p21_263\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:857.585746px;top:371.419757px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p21_264\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:880.848470px;top:371.419757px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p21_265\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:586.884032px;top:371.419757px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p21_266\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19.142148px;top:10.934837px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">マニュアル エア コンディショナ、オート エア コンディショナ</font></nobr>");
write("</p>");
write("<p id=\"p21_267\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:833.935591px;top:36.435628px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*1：ヒューズ ボックス</font></nobr>");
write("</p>");
write("<p id=\"p21_268\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:833.935591px;top:41.049367px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*2：ディスチャージ ヘッドライト装備車</font></nobr>");
write("</p>");
write("<p id=\"p21_269\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:833.935591px;top:45.685444px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*3：ディスチャージ ヘッドライト非装備車</font></nobr>");
write("</p>");
write("<p id=\"p21_270\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:863.989853px;top:51.022788px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">：CANライン</font></nobr>");
write("</p>");
write("<p id=\"p21_271\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1.191006px;top:16.000067px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.2pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">17</font></nobr>");
write("</p>");
write("<p id=\"p21_272\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:933.723841px;top:16.000067px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.2pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">17</font></nobr>");
write("</p>");
write("<p id=\"p21_273\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:855.284196px;top:188.666681px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">188</font></nobr>");
write("</p>");
write("<p id=\"p21_274\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:853.898389px;top:239.145021px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">NAVI<br>-SI</font></nobr>");
write("</p>");
write("<p id=\"p21_275\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:893.042351px;top:239.145021px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">NAVI<br>-CLK</font></nobr>");
write("</p>");
write("<p id=\"p21_276\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:860.987272px;top:231.510285px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">31</font></nobr>");
write("</p>");
write("<p id=\"p21_277\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:900.477347px;top:231.510285px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">32</font></nobr>");
write("</p>");
write("<p id=\"p21_278\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:894.661158px;top:182.789850px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">198</font></nobr>");
write("</p>");
write("<p id=\"p21_279\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:846.428172px;top:158.967089px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(NAV.装備車)</font></nobr>");
write("</p>");
write("<p id=\"p21_280\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:896.170238px;top:205.239183px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p21_281\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:873.296975px;top:239.145021px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">NAVI<br>-SO</font></nobr>");
write("</p>");
write("<p id=\"p21_282\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:880.732648px;top:231.510285px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">33</font></nobr>");
write("</p>");
write("<p id=\"p21_283\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:874.916459px;top:182.789850px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">199</font></nobr>");
write("</p>");
write("<p id=\"p21_284\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:876.425539px;top:205.239183px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p21_285\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:856.681517px;top:205.239183px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p21_286\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:865.342471px;top:170.491284px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">AVN ユニット<br>(21-B)</font></nobr>");
write("</p>");
write("</v:group>");
}