with(document) {
write("<v:group id=\"group24\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:493.10px;\" coordsize=\"950.00,493.10\">");
write("<v:rect id=\"rect24\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:493.10px;\">");
write("<img id=\"img24\" name=\"PrtImgId\" src=\"../img/4926_2.0_jpn_9502808_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:493.10px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p24_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:587.162413px;top:20.800631px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C</font></nobr>");
write("</p>");
write("<p id=\"p24_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19.140116px;top:10.934160px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">イージ ドア クローザ、スカイルーフ、オーディオ ユニット</font></nobr>");
write("</p>");
write("<p id=\"p24_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131.328831px;top:20.800631px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A</font></nobr>");
write("</p>");
write("<p id=\"p24_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359.246638px;top:20.800631px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B</font></nobr>");
write("</p>");
write("<p id=\"p24_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815.078865px;top:20.800631px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">D</font></nobr>");
write("</p>");
write("<p id=\"p24_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:99.526393px;top:117.926066px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">14</font></nobr>");
write("</p>");
write("<p id=\"p24_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128.619532px;top:117.926066px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">26</font></nobr>");
write("</p>");
write("<p id=\"p24_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:696.217145px;top:218.236985px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">174</font></nobr>");
write("</p>");
write("<p id=\"p24_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545.267157px;top:140.601483px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p24_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128.731290px;top:133.494051px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p24_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:99.746524px;top:133.494051px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p24_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:99.746524px;top:174.956105px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p24_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128.731290px;top:174.956105px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p24_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194.995342px;top:237.064913px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p24_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194.995342px;top:251.449679px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p24_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194.995342px;top:265.834446px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p24_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194.995342px;top:280.358654px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p24_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:224.474556px;top:379.457925px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p24_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167.225698px;top:294.603980px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p24_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:224.474556px;top:294.603980px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p24_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167.225698px;top:307.689778px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p24_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167.225698px;top:333.866791px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p24_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167.225698px;top:356.662019px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p24_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:58.544172px;top:382.605503px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p24_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503.755944px;top:370.420655px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p24_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447.567777px;top:370.420655px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p24_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:476.425205px;top:384.185383px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p24_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503.755944px;top:400.543986px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p24_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:648.935124px;top:312.656182px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p24_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625.551835px;top:238.193302px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p24_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:661.548946px;top:238.193302px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p24_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:697.481711px;top:238.193302px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p24_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:733.474080px;top:238.193302px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p24_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769.467804px;top:238.193302px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p24_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:684.929525px;top:312.656182px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p24_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719.613303px;top:312.656182px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p24_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:770.218280px;top:312.656182px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p24_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:786.317617px;top:312.656182px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p24_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820.645799px;top:312.656182px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p24_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:836.743103px;top:312.656182px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p24_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:871.252131px;top:312.656182px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p24_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:887.349435px;top:312.656182px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p24_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447.567777px;top:297.311573px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p24_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:390.185486px;top:297.311573px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p24_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:478.988203px;top:297.311573px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p24_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511.195004px;top:297.311573px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p24_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:569.652209px;top:297.311573px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p24_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:58.544172px;top:309.157971px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p24_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192.851609px;top:205.700151px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p24_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494.286942px;top:297.311573px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p24_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:733.680665px;top:312.656182px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p24_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:55.157547px;top:427.270640px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G602</font></nobr>");
write("</p>");
write("<p id=\"p24_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500.284654px;top:427.270640px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G501</font></nobr>");
write("</p>");
write("<p id=\"p24_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645.548499px;top:349.084820px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G502</font></nobr>");
write("</p>");
write("<p id=\"p24_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:681.542901px;top:349.454406px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G503</font></nobr>");
write("</p>");
write("<p id=\"p24_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130.113033px;top:356.991669px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R/C3</font></nobr>");
write("</p>");
write("<p id=\"p24_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130.113033px;top:333.862729px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R/C1</font></nobr>");
write("</p>");
write("<p id=\"p24_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128.909427px;top:307.869833px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">CLMP</font></nobr>");
write("</p>");
write("<p id=\"p24_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130.868250px;top:294.600595px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">COM</font></nobr>");
write("</p>");
write("<p id=\"p24_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92.509985px;top:296.405206px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">GND</font></nobr>");
write("</p>");
write("<p id=\"p24_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133.497625px;top:280.487265px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L/P</font></nobr>");
write("</p>");
write("<p id=\"p24_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133.721143px;top:266.011793px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">F/L</font></nobr>");
write("</p>");
write("<p id=\"p24_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133.196893px;top:251.435465px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">H/L</font></nobr>");
write("</p>");
write("<p id=\"p24_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130.413088px;top:237.060851px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">CLM-</font></nobr>");
write("</p>");
write("<p id=\"p24_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:127.629960px;top:205.471360px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">CLM＋</font></nobr>");
write("</p>");
write("<p id=\"p24_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:126.248894px;top:190.744082px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">VMP</font></nobr>");
write("</p>");
write("<p id=\"p24_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95.261279px;top:190.744082px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">＋B<br>BACK UP</font></nobr>");
write("</p>");
write("<p id=\"p24_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132.483670px;top:149.060005px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">D7</font></nobr>");
write("</p>");
write("<p id=\"p24_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:103.584925px;top:149.060005px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">D4</font></nobr>");
write("</p>");
write("<p id=\"p24_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132.483670px;top:183.357091px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p24_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143.772644px;top:202.310921px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p24_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:103.584925px;top:183.357091px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">9</font></nobr>");
write("</p>");
write("<p id=\"p24_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132.483670px;top:159.213480px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A8</font></nobr>");
write("</p>");
write("<p id=\"p24_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:62.608121px;top:327.543884px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A10</font></nobr>");
write("</p>");
write("<p id=\"p24_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:62.608121px;top:337.698035px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">D5</font></nobr>");
write("</p>");
write("<p id=\"p24_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248.476919px;top:202.310921px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A1</font></nobr>");
write("</p>");
write("<p id=\"p24_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281.974701px;top:218.896285px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.クローザ<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p24_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258.593444px;top:241.066059px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(ラッチ ラチェット スイッチ)</font></nobr>");
write("</p>");
write("<p id=\"p24_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256.631234px;top:179.464925px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.スライド ドア<br>クローザ アッセンブリ</font></nobr>");
write("</p>");
write("<p id=\"p24_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:100.536962px;top:268.425613px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.スライド<br>ドア クローザ<br>コントロール<br>ユニット</font></nobr>");
write("</p>");
write("<p id=\"p24_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:119.502060px;top:103.365983px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.40(20A)*<sup>1</sup><br>ヒューズ<br>(1-C)</font></nobr>");
write("</p>");
write("<p id=\"p24_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545.254288px;top:117.926066px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">30</font></nobr>");
write("</p>");
write("<p id=\"p24_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536.037250px;top:103.365983px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.46(20A)*<sup>1</sup><br>ヒューズ<br>(1-C)</font></nobr>");
write("</p>");
write("<p id=\"p24_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:762.916718px;top:199.264879px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.14(7.5A)*<sup>1</sup><br>ヒューズ<br>(2-D)</font></nobr>");
write("</p>");
write("<p id=\"p24_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726.341171px;top:199.264879px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.1(10A)*<sup>1</sup><br>ヒューズ<br>(1-C)</font></nobr>");
write("</p>");
write("<p id=\"p24_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:691.120953px;top:199.264879px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">データ リンク<br>カプラ(DLC)<br>(4-B)</font></nobr>");
write("</p>");
write("<p id=\"p24_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:655.562748px;top:203.034525px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">PGM-FI ECU<br>(4-D)</font></nobr>");
write("</p>");
write("<p id=\"p24_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621.527170px;top:202.649370px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(13-C)</font></nobr>");
write("</p>");
write("<p id=\"p24_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446.119656px;top:280.638890px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">180</font></nobr>");
write("</p>");
write("<p id=\"p24_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568.168190px;top:317.454714px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">195</font></nobr>");
write("</p>");
write("<p id=\"p24_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624.068494px;top:212.989669px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">183</font></nobr>");
write("</p>");
write("<p id=\"p24_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660.064927px;top:212.989669px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">110</font></nobr>");
write("</p>");
write("<p id=\"p24_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:733.378577px;top:212.989669px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">16</font></nobr>");
write("</p>");
write("<p id=\"p24_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769.467127px;top:212.989669px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">85</font></nobr>");
write("</p>");
write("<p id=\"p24_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:443.629810px;top:271.079731px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(13-C)</font></nobr>");
write("</p>");
write("<p id=\"p24_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:566.283195px;top:327.995375px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(12-C)</font></nobr>");
write("</p>");
write("<p id=\"p24_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91.054413px;top:103.365983px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.1(10A)*<sup>1</sup><br>ヒューズ<br>(1-C)</font></nobr>");
write("</p>");
write("<p id=\"p24_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260.462183px;top:255.326953px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.ハーフ ラッチ スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p24_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260.462183px;top:270.512491px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.フル ラッチ スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p24_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262.575437px;top:284.220359px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.ラチェット スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p24_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255.309096px;top:393.658576px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.リモート コントロール スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p24_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:267.299101px;top:311.974545px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.元位置スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p24_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143.772644px;top:233.167332px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p24_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248.476919px;top:233.167332px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A2</font></nobr>");
write("</p>");
write("<p id=\"p24_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143.772644px;top:248.004944px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">12</font></nobr>");
write("</p>");
write("<p id=\"p24_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248.476919px;top:248.004944px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B3</font></nobr>");
write("</p>");
write("<p id=\"p24_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143.772644px;top:261.712812px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p24_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248.476919px;top:261.712812px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B1</font></nobr>");
write("</p>");
write("<p id=\"p24_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143.772644px;top:276.436028px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p24_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248.476919px;top:276.436028px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B4</font></nobr>");
write("</p>");
write("<p id=\"p24_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143.772644px;top:290.651570px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p24_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:86.030017px;top:292.682265px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">8</font></nobr>");
write("</p>");
write("<p id=\"p24_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248.476919px;top:290.651570px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B5</font></nobr>");
write("</p>");
write("<p id=\"p24_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143.772644px;top:304.190214px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p24_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248.476919px;top:304.190214px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B6</font></nobr>");
write("</p>");
write("<p id=\"p24_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143.772644px;top:330.252154px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">11</font></nobr>");
write("</p>");
write("<p id=\"p24_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248.476919px;top:330.252154px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p24_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143.772644px;top:353.437276px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">10</font></nobr>");
write("</p>");
write("<p id=\"p24_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248.476919px;top:353.437276px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p24_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282.877575px;top:338.374934px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*2</font></nobr>");
write("</p>");
write("<p id=\"p24_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:75.814602px;top:332.734340px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*4</font></nobr>");
write("</p>");
write("<p id=\"p24_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282.877575px;top:361.560733px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*3</font></nobr>");
write("</p>");
write("<p id=\"p24_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248.476919px;top:376.114724px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p24_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:103.584925px;top:159.213480px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A1</font></nobr>");
write("</p>");
write("<p id=\"p24_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145.665091px;top:153.499105px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*4</font></nobr>");
write("</p>");
write("<p id=\"p24_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455.220194px;top:332.977347px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">照明<br>(0.84W)</font></nobr>");
write("</p>");
write("<p id=\"p24_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513.340091px;top:323.674732px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">クローズ</font></nobr>");
write("</p>");
write("<p id=\"p24_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481.608096px;top:323.674732px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">オープン</font></nobr>");
write("</p>");
write("<p id=\"p24_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:520.955256px;top:360.483111px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">サンシェード スイッチ<br>(サンシェード/マップ<br> ライト スイッチに内蔵)</font></nobr>");
write("</p>");
write("<p id=\"p24_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402.932064px;top:208.707610px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ホール センサ</font></nobr>");
write("</p>");
write("<p id=\"p24_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:477.918707px;top:191.096070px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">オープン<br>リレー</font></nobr>");
write("</p>");
write("<p id=\"p24_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500.804839px;top:191.096070px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">クローズ<br>リレー</font></nobr>");
write("</p>");
write("<p id=\"p24_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382.762682px;top:160.819083px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">スカイルーフ モータ ユニット</font></nobr>");
write("</p>");
write("<p id=\"p24_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:373.456915px;top:89.706851px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(スカイルーフ装備車)</font></nobr>");
write("</p>");
write("<p id=\"p24_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45.185969px;top:89.706851px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(L.パワー スライド ドア装備およびイージ ドア クローザ装備車)</font></nobr>");
write("</p>");
write("<p id=\"p24_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490.350329px;top:205.937066px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">モータ</font></nobr>");
write("</p>");
write("<p id=\"p24_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475.808840px;top:342.078921px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">AUTO<br>(オープン)</font></nobr>");
write("</p>");
write("<p id=\"p24_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:526.100893px;top:342.078921px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">AUTO<br>(クローズ)</font></nobr>");
write("</p>");
write("<p id=\"p24_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513.825734px;top:256.394422px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">10</font></nobr>");
write("</p>");
write("<p id=\"p24_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:484.521270px;top:256.394422px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p24_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393.652713px;top:256.394422px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p24_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:572.843087px;top:256.394422px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p24_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500.164090px;top:256.394422px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p24_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:560.295642px;top:236.408321px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">P/W TIMER</font></nobr>");
write("</p>");
write("<p id=\"p24_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506.337229px;top:236.408321px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">CLOSE</font></nobr>");
write("</p>");
write("<p id=\"p24_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:540.201444px;top:228.097364px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">CLOSE</font></nobr>");
write("</p>");
write("<p id=\"p24_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475.293396px;top:236.408321px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">AUTO</font></nobr>");
write("</p>");
write("<p id=\"p24_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407.786452px;top:236.408321px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">GND</font></nobr>");
write("</p>");
write("<p id=\"p24_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564.810690px;top:228.097364px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">VBU</font></nobr>");
write("</p>");
write("<p id=\"p24_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441.569387px;top:228.097364px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">OPEN</font></nobr>");
write("</p>");
write("<p id=\"p24_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492.452068px;top:236.408321px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">OPEN</font></nobr>");
write("</p>");
write("<p id=\"p24_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:489.742768px;top:230.867909px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">CPU</font></nobr>");
write("</p>");
write("<p id=\"p24_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548.886781px;top:160.817053px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p24_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:507.093801px;top:360.480403px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p24_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450.862285px;top:360.480403px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p24_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515.484502px;top:311.206265px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p24_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500.164090px;top:311.206265px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p24_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483.129368px;top:311.121653px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p24_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:451.060742px;top:311.206265px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">8</font></nobr>");
write("</p>");
write("<p id=\"p24_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721.414310px;top:343.677079px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.フロント<br>スピーカ</font></nobr>");
write("</p>");
write("<p id=\"p24_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:814.721238px;top:223.007765px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">フィーダ線</font></nobr>");
write("</p>");
write("<p id=\"p24_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:814.721238px;top:242.547789px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">サブ<br>フィーダ線</font></nobr>");
write("</p>");
write("<p id=\"p24_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:752.089001px;top:271.557621px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">オーディオ ユニット</font></nobr>");
write("</p>");
write("<p id=\"p24_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:839.593287px;top:199.437488px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ルーフ アンテナ<br>(AM/FM)</font></nobr>");
write("</p>");
write("<p id=\"p24_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:771.504520px;top:343.880148px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.フロント<br>スピーカ</font></nobr>");
write("</p>");
write("<p id=\"p24_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:823.432991px;top:344.079156px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.リヤ<br>スピーカ</font></nobr>");
write("</p>");
write("<p id=\"p24_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:875.427839px;top:344.079156px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.リヤ<br>スピーカ</font></nobr>");
write("</p>");
write("<p id=\"p24_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719.410106px;top:276.593068px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FR<br>L＋</font></nobr>");
write("</p>");
write("<p id=\"p24_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:688.971123px;top:287.873579px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A12</font></nobr>");
write("</p>");
write("<p id=\"p24_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:891.149906px;top:287.873579px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A6</font></nobr>");
write("</p>");
write("<p id=\"p24_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:875.023476px;top:287.873579px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A7</font></nobr>");
write("</p>");
write("<p id=\"p24_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824.427304px;top:287.873579px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A11</font></nobr>");
write("</p>");
write("<p id=\"p24_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:840.817213px;top:287.873579px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A10</font></nobr>");
write("</p>");
write("<p id=\"p24_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:790.160081px;top:287.873579px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A18</font></nobr>");
write("</p>");
write("<p id=\"p24_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:774.035684px;top:287.873579px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A19</font></nobr>");
write("</p>");
write("<p id=\"p24_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723.642031px;top:287.873579px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A23</font></nobr>");
write("</p>");
write("<p id=\"p24_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740.067161px;top:287.873579px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A22</font></nobr>");
write("</p>");
write("<p id=\"p24_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:891.149906px;top:327.810582px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p24_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:875.023476px;top:327.810582px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p24_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824.427304px;top:327.810582px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p24_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:840.817213px;top:327.810582px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p24_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:790.160081px;top:327.810582px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p24_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:774.035684px;top:327.810582px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p24_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723.642031px;top:327.810582px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p24_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740.067161px;top:327.810582px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p24_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:856.209421px;top:255.439995px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">E1</font></nobr>");
write("</p>");
write("<p id=\"p24_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660.349404px;top:262.691607px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">VSP</font></nobr>");
write("</p>");
write("<p id=\"p24_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:874.751869px;top:255.238280px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">E3</font></nobr>");
write("</p>");
write("<p id=\"p24_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:837.863399px;top:255.238280px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">E2</font></nobr>");
write("</p>");
write("<p id=\"p24_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:731.415690px;top:261.995079px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">＋B<br>BACK UP</font></nobr>");
write("</p>");
write("<p id=\"p24_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:737.349056px;top:255.238280px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A24</font></nobr>");
write("</p>");
write("<p id=\"p24_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:701.469800px;top:255.238280px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A3</font></nobr>");
write("</p>");
write("<p id=\"p24_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:665.590544px;top:255.238280px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A15</font></nobr>");
write("</p>");
write("<p id=\"p24_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647.648207px;top:280.620614px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ILL-</font></nobr>");
write("</p>");
write("<p id=\"p24_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:867.294521px;top:262.691607px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ANT＋B</font></nobr>");
write("</p>");
write("<p id=\"p24_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766.779502px;top:262.691607px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ACC</font></nobr>");
write("</p>");
write("<p id=\"p24_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:735.533826px;top:276.591715px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FR<br>L-</font></nobr>");
write("</p>");
write("<p id=\"p24_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769.601237px;top:276.591715px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FR<br>R＋</font></nobr>");
write("</p>");
write("<p id=\"p24_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:785.926800px;top:276.591715px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FR<br>R-</font></nobr>");
write("</p>");
write("<p id=\"p24_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820.195378px;top:276.591715px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">RR<br>L＋</font></nobr>");
write("</p>");
write("<p id=\"p24_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:836.322484px;top:276.591715px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">RR<br>L-</font></nobr>");
write("</p>");
write("<p id=\"p24_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:830.809737px;top:262.691607px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">AM/FM<br>SH</font></nobr>");
write("</p>");
write("<p id=\"p24_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:870.590384px;top:276.591715px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">RR<br>R＋</font></nobr>");
write("</p>");
write("<p id=\"p24_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:886.715459px;top:276.591715px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">RR<br>R-</font></nobr>");
write("</p>");
write("<p id=\"p24_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629.507413px;top:255.238280px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A13</font></nobr>");
write("</p>");
write("<p id=\"p24_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624.266950px;top:263.296077px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ILL＋</font></nobr>");
write("</p>");
write("<p id=\"p24_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:773.229667px;top:255.238280px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A14</font></nobr>");
write("</p>");
write("<p id=\"p24_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:849.153051px;top:262.691607px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">AM/FM<br>SIG</font></nobr>");
write("</p>");
write("<p id=\"p24_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:681.003750px;top:276.591715px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MAIN<br>GND</font></nobr>");
write("</p>");
write("<p id=\"p24_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693.608090px;top:262.691607px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">K-LINE</font></nobr>");
write("</p>");
write("<p id=\"p24_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:856.611075px;top:212.126624px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p24_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:875.068180px;top:212.126624px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p24_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838.065919px;top:212.126624px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p24_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652.889347px;top:287.873579px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A1</font></nobr>");
write("</p>");
write("<p id=\"p24_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838.479764px;top:32.374915px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*1：ヒューズ ボックス</font></nobr>");
write("</p>");
write("<p id=\"p24_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:867.998940px;top:52.002259px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">：その他の通信線</font></nobr>");
write("</p>");
write("<p id=\"p24_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:867.998940px;top:61.001623px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">：シールド線</font></nobr>");
write("</p>");
write("<p id=\"p24_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:867.998940px;top:56.501603px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">：工場出荷時は未装備</font></nobr>");
write("</p>");
write("<p id=\"p24_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838.479764px;top:36.989331px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*2：リモート コントロール スイッチ1</font></nobr>");
write("</p>");
write("<p id=\"p24_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838.479764px;top:41.603747px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*3：リモート コントロール スイッチ3</font></nobr>");
write("</p>");
write("<p id=\"p24_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838.479764px;top:46.218840px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*4：CESS Assy.</font></nobr>");
write("</p>");
write("<p id=\"p24_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1.191006px;top:16.000067px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.2pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">20</font></nobr>");
write("</p>");
write("<p id=\"p24_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:933.721132px;top:16.000067px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.2pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">20</font></nobr>");
write("</p>");
write("</v:group>");
}