with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:1092.14px;\" coordsize=\"950.00,1092.14\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:1092.14px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/5218_3.0_jpn_9677398_5.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:1092.14px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408.082113px;top:116.976535px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225.473246px;top:116.976535px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:495.429420px;top:434.405160px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:415.721276px;top:647.008580px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:589.863775px;top:434.405160px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207.840267px;top:434.391675px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:871.591298px;top:647.008580px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87.129580px;top:647.008580px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:379.685823px;top:647.008580px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:829.719226px;top:647.008580px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492.918941px;top:117.521677px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87.016079px;top:434.405160px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:675.618226px;top:647.008580px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:717.490298px;top:647.008580px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527.721279px;top:647.008580px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:569.497165px;top:647.008580px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378.974041px;top:750.676079px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">L. フロント<br>スピーカ</font></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:189.728277px;top:750.676079px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">パーキング<br>ブレーキ<br>スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:524.504790px;top:750.676079px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">Ｒ. フロント<br>スピーカ</font></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:680.610325px;top:750.676079px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">L. リヤ<br>スピーカ</font></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:836.213765px;top:750.676079px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">R. リヤ<br>スピーカ</font></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:272.533638px;top:78.754960px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ヒューズ ボックス</font></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:107.198010px;top:64.993497px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">バッテリ ターミナル<br>ヒューズ ボックス</font></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:419.857311px;top:69.693660px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">イグニッション<br>スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36.360220px;top:96.771610px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">バッテリ</font></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:882.604696px;top:586.948580px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A6</font></nobr>");
write("</p>");
write("<p id=\"p2_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:840.951930px;top:586.948580px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A7</font></nobr>");
write("</p>");
write("<p id=\"p2_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:580.179680px;top:586.948580px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A18</font></nobr>");
write("</p>");
write("<p id=\"p2_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:728.067007px;top:586.948580px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A10</font></nobr>");
write("</p>");
write("<p id=\"p2_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538.199878px;top:586.948580px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A19</font></nobr>");
write("</p>");
write("<p id=\"p2_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:686.410393px;top:586.948580px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A11</font></nobr>");
write("</p>");
write("<p id=\"p2_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:432.840617px;top:586.948580px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A22</font></nobr>");
write("</p>");
write("<p id=\"p2_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:390.968544px;top:586.948580px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A23</font></nobr>");
write("</p>");
write("<p id=\"p2_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:418.010524px;top:558.052206px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">FR<br>L-</font></nobr>");
write("</p>");
write("<p id=\"p2_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376.571291px;top:558.052206px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">FR<br>L＋</font></nobr>");
write("</p>");
write("<p id=\"p2_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:565.457316px;top:558.052206px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">FR<br>R-</font></nobr>");
write("</p>");
write("<p id=\"p2_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:523.038901px;top:558.052206px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">FR<br>R＋</font></nobr>");
write("</p>");
write("<p id=\"p2_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714.545056px;top:558.052206px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">RR<br>L-</font></nobr>");
write("</p>");
write("<p id=\"p2_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:672.124718px;top:558.052206px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">RR<br>L＋</font></nobr>");
write("</p>");
write("<p id=\"p2_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:869.732968px;top:558.052206px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">RR<br>R-</font></nobr>");
write("</p>");
write("<p id=\"p2_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:827.751242px;top:558.052206px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">RR<br>R＋</font></nobr>");
write("</p>");
write("<p id=\"p2_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:77.841775px;top:1040.435380px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">G503</font></nobr>");
write("</p>");
write("<p id=\"p2_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:80.486914px;top:558.052206px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">MAIN<br>GND</font></nobr>");
write("</p>");
write("<p id=\"p2_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:42.287256px;top:323.920496px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.29(10A)<br>ヒューズ<br>(ヒューズ ボックス)<br>(MICU経由)</font></nobr>");
write("</p>");
write("<p id=\"p2_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538.172946px;top:104.960298px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.14(7.5A)</font></nobr>");
write("</p>");
write("<p id=\"p2_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:485.179745px;top:504.360544px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">＋B<br>BACK UP</font></nobr>");
write("</p>");
write("<p id=\"p2_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:577.538388px;top:503.957948px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ACC</font></nobr>");
write("</p>");
write("<p id=\"p2_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:600.115373px;top:484.956958px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A14</font></nobr>");
write("</p>");
write("<p id=\"p2_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506.767930px;top:484.956958px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A24</font></nobr>");
write("</p>");
write("<p id=\"p2_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:600.115373px;top:300.307954px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">M18</font></nobr>");
write("</p>");
write("<p id=\"p2_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506.767930px;top:300.307954px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">N1</font></nobr>");
write("</p>");
write("<p id=\"p2_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:440.110421px;top:246.912940px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU</font></nobr>");
write("</p>");
write("<p id=\"p2_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446.574180px;top:127.998804px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ACC</font></nobr>");
write("</p>");
write("<p id=\"p2_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:439.814165px;top:106.487850px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">BAT</font></nobr>");
write("</p>");
write("<p id=\"p2_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:306.583794px;top:164.290230px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.1(10A)</font></nobr>");
write("</p>");
write("<p id=\"p2_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:293.438895px;top:104.083831px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.60(IG)(50A)</font></nobr>");
write("</p>");
write("<p id=\"p2_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:98.793201px;top:484.956958px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A13</font></nobr>");
write("</p>");
write("<p id=\"p2_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79.274960px;top:504.177545px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ILL＋</font></nobr>");
write("</p>");
write("<p id=\"p2_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389.214095px;top:108.997814px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">T1</font></nobr>");
write("</p>");
write("<p id=\"p2_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512.115919px;top:109.217413px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">S3</font></nobr>");
write("</p>");
write("<p id=\"p2_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218.201518px;top:382.096578px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A29</font></nobr>");
write("</p>");
write("<p id=\"p2_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201.626594px;top:504.177545px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">VSP</font></nobr>");
write("</p>");
write("<p id=\"p2_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218.201518px;top:484.956958px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A15</font></nobr>");
write("</p>");
write("<p id=\"p2_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:339.562427px;top:434.391675px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p2_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349.923678px;top:302.155271px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">C21</font></nobr>");
write("</p>");
write("<p id=\"p2_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333.348755px;top:504.177545px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">BACK<br>LT</font></nobr>");
write("</p>");
write("<p id=\"p2_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349.923678px;top:484.956958px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">F2</font></nobr>");
write("</p>");
write("<p id=\"p2_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:179.574790px;top:341.257164px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">PGM-FI ECU</font></nobr>");
write("</p>");
write("<p id=\"p2_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201.934392px;top:365.607478px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">VSP</font></nobr>");
write("</p>");
write("<p id=\"p2_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:120.831539px;top:104.889024px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.1(100A)</font></nobr>");
write("</p>");
write("<p id=\"p2_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252.469055px;top:108.997814px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">T-9</font></nobr>");
write("</p>");
write("<p id=\"p2_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:98.806667px;top:586.944728px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">A12</font></nobr>");
write("</p>");
write("<p id=\"p2_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207.863352px;top:647.008580px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p2_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201.220686px;top:546.494428px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">FOOT<br>PARK<br>SW</font></nobr>");
write("</p>");
write("<p id=\"p2_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219.540439px;top:586.944728px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">F3</font></nobr>");
write("</p>");
write("<p id=\"p2_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389.571910px;top:708.172347px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p2_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:430.630241px;top:708.172347px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p2_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537.645841px;top:708.172347px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p2_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578.704173px;top:708.172347px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p2_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:684.961819px;top:708.172347px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p2_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726.022075px;top:708.172347px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p2_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:839.445644px;top:708.172347px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p2_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:880.507822px;top:708.172347px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p2_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:816.405038px;top:13.553675px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">：工場出荷時は非装備</font></nobr>");
write("</p>");
write("<p id=\"p2_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:816.405038px;top:26.843194px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">：シールド線</font></nobr>");
write("</p>");
write("<p id=\"p2_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742.023724px;top:222.019410px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">テールゲート<br>サブ フィーダ線</font></nobr>");
write("</p>");
write("<p id=\"p2_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:755.089750px;top:331.105582px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">フィーダ線</font></nobr>");
write("</p>");
write("<p id=\"p2_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738.360928px;top:430.749048px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">サブ フィーダ線</font></nobr>");
write("</p>");
write("<p id=\"p2_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714.697032px;top:505.138767px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AM/FM<br>SH</font></nobr>");
write("</p>");
write("<p id=\"p2_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745.667283px;top:133.496454px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ルーフ アンテナ<br>(AM/FM)</font></nobr>");
write("</p>");
write("<p id=\"p2_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:741.302323px;top:486.819688px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">E2</font></nobr>");
write("</p>");
write("<p id=\"p2_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:790.030596px;top:486.819688px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">E1</font></nobr>");
write("</p>");
write("<p id=\"p2_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838.760792px;top:486.819688px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">E3</font></nobr>");
write("</p>");
write("<p id=\"p2_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:741.302323px;top:179.016766px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p2_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:790.492292px;top:179.016766px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p2_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:835.375015px;top:179.016766px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p2_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:763.329118px;top:505.138767px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">AM/FM<br>SIG</font></nobr>");
write("</p>");
write("<p id=\"p2_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824.321218px;top:505.138767px;font-weight:normal;font-size:7.5pt;color:black;\" prt_font_size=\"8.7pt\" disp_font_size=\"7.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ANT<br>＋B</font></nobr>");
write("</p>");
write("</v:group>");
}