with(document) {
write("<v:group id=\"group20\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:493.10px;\" coordsize=\"950.00,493.10\">");
write("<v:rect id=\"rect20\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:493.10px;\">");
write("<img id=\"img20\" name=\"PrtImgId\" src=\"../img/5222_3.0_jpn_9695562_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:493.10px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p20_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:587.162413px;top:20.800631px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C</font></nobr>");
write("</p>");
write("<p id=\"p20_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19.140116px;top:10.934160px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">イージ ドア クローザ、スカイルーフ、オーディオ ユニット</font></nobr>");
write("</p>");
write("<p id=\"p20_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131.328831px;top:20.800631px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A</font></nobr>");
write("</p>");
write("<p id=\"p20_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359.246638px;top:20.800631px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B</font></nobr>");
write("</p>");
write("<p id=\"p20_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815.078865px;top:20.800631px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">D</font></nobr>");
write("</p>");
write("<p id=\"p20_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:99.526393px;top:117.926066px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">14</font></nobr>");
write("</p>");
write("<p id=\"p20_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128.619532px;top:117.926066px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">26</font></nobr>");
write("</p>");
write("<p id=\"p20_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545.267157px;top:140.601483px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p20_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128.731290px;top:133.494051px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p20_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:99.746524px;top:133.494051px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p20_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:99.746524px;top:174.956105px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p20_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128.731290px;top:174.956105px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p20_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194.995342px;top:237.064913px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p20_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194.995342px;top:251.449679px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p20_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194.995342px;top:265.834446px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p20_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194.995342px;top:280.358654px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p20_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:224.474556px;top:379.457925px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p20_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167.225698px;top:294.603980px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p20_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:224.474556px;top:294.603980px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p20_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167.225698px;top:307.689778px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p20_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167.225698px;top:333.866791px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p20_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167.225698px;top:356.662019px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p20_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:58.544172px;top:382.605503px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p20_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503.755944px;top:370.420655px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p20_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447.567777px;top:370.420655px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p20_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:476.425205px;top:384.185383px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p20_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503.755944px;top:400.543986px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p20_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.522199px;top:238.193302px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p20_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673.518632px;top:238.193302px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p20_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710.610978px;top:238.193302px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p20_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:746.604702px;top:238.193302px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p20_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710.629942px;top:312.656182px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p20_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:749.992681px;top:312.656182px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p20_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:793.002814px;top:312.656182px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p20_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809.102150px;top:312.656182px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p20_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:835.834810px;top:312.656182px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p20_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:851.932792px;top:312.656182px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p20_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:878.846975px;top:312.656182px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p20_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:894.944280px;top:312.656182px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p20_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447.567777px;top:297.311573px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p20_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:390.185486px;top:297.311573px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p20_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:478.988203px;top:297.311573px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p20_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511.195004px;top:297.311573px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">茶</font></nobr>");
write("</p>");
write("<p id=\"p20_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:569.652209px;top:297.311573px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p20_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:58.544172px;top:309.157971px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p20_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192.851609px;top:205.700151px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p20_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494.286942px;top:297.311573px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p20_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:764.060042px;top:312.656182px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p20_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:55.157547px;top:427.270640px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G602</font></nobr>");
write("</p>");
write("<p id=\"p20_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500.284654px;top:427.270640px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G501</font></nobr>");
write("</p>");
write("<p id=\"p20_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:707.243318px;top:359.490778px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G503</font></nobr>");
write("</p>");
write("<p id=\"p20_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130.113033px;top:356.991669px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R/C3</font></nobr>");
write("</p>");
write("<p id=\"p20_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130.113033px;top:333.862729px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R/C1</font></nobr>");
write("</p>");
write("<p id=\"p20_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128.909427px;top:307.869833px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">CLMP</font></nobr>");
write("</p>");
write("<p id=\"p20_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130.868250px;top:294.600595px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">COM</font></nobr>");
write("</p>");
write("<p id=\"p20_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92.509985px;top:296.405206px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">GND</font></nobr>");
write("</p>");
write("<p id=\"p20_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133.497625px;top:280.487265px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L/P</font></nobr>");
write("</p>");
write("<p id=\"p20_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133.721143px;top:266.011793px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">F/L</font></nobr>");
write("</p>");
write("<p id=\"p20_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133.196893px;top:251.435465px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">H/L</font></nobr>");
write("</p>");
write("<p id=\"p20_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130.413088px;top:237.060851px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">CLM-</font></nobr>");
write("</p>");
write("<p id=\"p20_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:127.629960px;top:205.471360px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">CLM＋</font></nobr>");
write("</p>");
write("<p id=\"p20_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:126.248894px;top:190.744082px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">VMP</font></nobr>");
write("</p>");
write("<p id=\"p20_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95.261279px;top:190.744082px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">＋B<br>BACK UP</font></nobr>");
write("</p>");
write("<p id=\"p20_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132.483670px;top:149.060005px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">D7</font></nobr>");
write("</p>");
write("<p id=\"p20_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:103.584925px;top:149.060005px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">D4</font></nobr>");
write("</p>");
write("<p id=\"p20_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132.483670px;top:183.357091px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p20_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143.772644px;top:202.310921px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p20_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:103.584925px;top:183.357091px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">9</font></nobr>");
write("</p>");
write("<p id=\"p20_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132.483670px;top:159.213480px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A8</font></nobr>");
write("</p>");
write("<p id=\"p20_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:62.608121px;top:327.543884px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A10</font></nobr>");
write("</p>");
write("<p id=\"p20_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:62.608121px;top:337.698035px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">D5</font></nobr>");
write("</p>");
write("<p id=\"p20_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248.476919px;top:202.310921px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A1</font></nobr>");
write("</p>");
write("<p id=\"p20_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281.974701px;top:218.896285px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.クローザ<br>モータ</font></nobr>");
write("</p>");
write("<p id=\"p20_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258.593444px;top:241.066059px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(ラッチ ラチェット スイッチ)</font></nobr>");
write("</p>");
write("<p id=\"p20_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256.631234px;top:179.464925px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.スライド ドア<br>クローザ アッセンブリ</font></nobr>");
write("</p>");
write("<p id=\"p20_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:100.536962px;top:268.425613px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.スライド<br>ドア クローザ<br>コントロール<br>ユニット</font></nobr>");
write("</p>");
write("<p id=\"p20_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:119.502060px;top:103.365983px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.40(20A)*<sup>1</sup><br>ヒューズ<br>(1-C)</font></nobr>");
write("</p>");
write("<p id=\"p20_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545.254288px;top:117.926066px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">30</font></nobr>");
write("</p>");
write("<p id=\"p20_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536.037250px;top:103.365983px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.46(20A)*<sup>1</sup><br>ヒューズ<br>(1-C)</font></nobr>");
write("</p>");
write("<p id=\"p20_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740.053615px;top:199.264879px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.14(7.5A)*<sup>1</sup><br>ヒューズ<br>(2-D)</font></nobr>");
write("</p>");
write("<p id=\"p20_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:703.478069px;top:199.264879px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.1(10A)*<sup>1</sup><br>ヒューズ<br>(1-C)</font></nobr>");
write("</p>");
write("<p id=\"p20_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:667.532435px;top:203.034525px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">PGM-FI ECU<br>(4-D)</font></nobr>");
write("</p>");
write("<p id=\"p20_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:633.496857px;top:202.649370px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(13-C)</font></nobr>");
write("</p>");
write("<p id=\"p20_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446.119656px;top:280.638890px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">175</font></nobr>");
write("</p>");
write("<p id=\"p20_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568.263693px;top:317.454714px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">189</font></nobr>");
write("</p>");
write("<p id=\"p20_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636.039535px;top:212.989669px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">178</font></nobr>");
write("</p>");
write("<p id=\"p20_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:672.130794px;top:212.989669px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">109</font></nobr>");
write("</p>");
write("<p id=\"p20_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710.515475px;top:212.989669px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">16</font></nobr>");
write("</p>");
write("<p id=\"p20_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:746.604702px;top:212.989669px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">84</font></nobr>");
write("</p>");
write("<p id=\"p20_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:443.629810px;top:271.079731px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(13-C)</font></nobr>");
write("</p>");
write("<p id=\"p20_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:566.283195px;top:327.995375px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(12-C)</font></nobr>");
write("</p>");
write("<p id=\"p20_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91.054413px;top:103.365983px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.1(10A)*<sup>1</sup><br>ヒューズ<br>(1-C)</font></nobr>");
write("</p>");
write("<p id=\"p20_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260.462183px;top:255.326953px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.ハーフ ラッチ スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p20_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260.462183px;top:270.512491px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.フル ラッチ スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p20_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262.575437px;top:284.220359px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.ラチェット スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p20_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255.309096px;top:393.658576px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.リモート コントロール スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p20_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:267.299101px;top:311.974545px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.元位置スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p20_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143.772644px;top:233.167332px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p20_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248.476919px;top:233.167332px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A2</font></nobr>");
write("</p>");
write("<p id=\"p20_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143.772644px;top:248.004944px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">12</font></nobr>");
write("</p>");
write("<p id=\"p20_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248.476919px;top:248.004944px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B3</font></nobr>");
write("</p>");
write("<p id=\"p20_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143.772644px;top:261.712812px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p20_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248.476919px;top:261.712812px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B1</font></nobr>");
write("</p>");
write("<p id=\"p20_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143.772644px;top:276.436028px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p20_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248.476919px;top:276.436028px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B4</font></nobr>");
write("</p>");
write("<p id=\"p20_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143.772644px;top:290.651570px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p20_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:86.030017px;top:292.682265px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">8</font></nobr>");
write("</p>");
write("<p id=\"p20_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248.476919px;top:290.651570px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B5</font></nobr>");
write("</p>");
write("<p id=\"p20_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143.772644px;top:304.190214px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p20_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248.476919px;top:304.190214px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">B6</font></nobr>");
write("</p>");
write("<p id=\"p20_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143.772644px;top:330.252154px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">11</font></nobr>");
write("</p>");
write("<p id=\"p20_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248.476919px;top:330.252154px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p20_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143.772644px;top:353.437276px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">10</font></nobr>");
write("</p>");
write("<p id=\"p20_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248.476919px;top:353.437276px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p20_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282.877575px;top:338.374934px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*2</font></nobr>");
write("</p>");
write("<p id=\"p20_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:75.814602px;top:332.734340px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*4</font></nobr>");
write("</p>");
write("<p id=\"p20_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282.877575px;top:361.560733px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*3</font></nobr>");
write("</p>");
write("<p id=\"p20_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248.476919px;top:376.114724px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p20_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:103.584925px;top:159.213480px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A1</font></nobr>");
write("</p>");
write("<p id=\"p20_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145.665091px;top:153.499105px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*4</font></nobr>");
write("</p>");
write("<p id=\"p20_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455.220194px;top:332.977347px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">照明<br>(0.84W)</font></nobr>");
write("</p>");
write("<p id=\"p20_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513.340091px;top:323.674732px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">クローズ</font></nobr>");
write("</p>");
write("<p id=\"p20_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481.608096px;top:323.674732px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">オープン</font></nobr>");
write("</p>");
write("<p id=\"p20_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:520.955256px;top:360.483111px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">サンシェード スイッチ<br>(サンシェード/マップ<br> ライト スイッチに内蔵)</font></nobr>");
write("</p>");
write("<p id=\"p20_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402.932064px;top:208.707610px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ホール センサ</font></nobr>");
write("</p>");
write("<p id=\"p20_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:477.918707px;top:191.096070px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">オープン<br>リレー</font></nobr>");
write("</p>");
write("<p id=\"p20_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500.804839px;top:191.096070px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">クローズ<br>リレー</font></nobr>");
write("</p>");
write("<p id=\"p20_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382.762682px;top:160.819083px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">スカイルーフ モータ ユニット</font></nobr>");
write("</p>");
write("<p id=\"p20_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:373.456915px;top:89.706851px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(スカイルーフ装備車)</font></nobr>");
write("</p>");
write("<p id=\"p20_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45.185969px;top:89.706851px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(L.パワー スライド ドア装備およびイージ ドア クローザ装備車)</font></nobr>");
write("</p>");
write("<p id=\"p20_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490.350329px;top:205.937066px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">モータ</font></nobr>");
write("</p>");
write("<p id=\"p20_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475.808840px;top:342.078921px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">AUTO<br>(オープン)</font></nobr>");
write("</p>");
write("<p id=\"p20_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:526.100893px;top:342.078921px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">AUTO<br>(クローズ)</font></nobr>");
write("</p>");
write("<p id=\"p20_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513.825734px;top:256.394422px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">10</font></nobr>");
write("</p>");
write("<p id=\"p20_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:484.521270px;top:256.394422px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p20_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393.652713px;top:256.394422px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p20_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:572.843087px;top:256.394422px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p20_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500.164090px;top:256.394422px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p20_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:560.295642px;top:236.408321px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">P/W TIMER</font></nobr>");
write("</p>");
write("<p id=\"p20_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506.337229px;top:236.408321px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">CLOSE</font></nobr>");
write("</p>");
write("<p id=\"p20_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:540.201444px;top:228.097364px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">CLOSE</font></nobr>");
write("</p>");
write("<p id=\"p20_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475.293396px;top:236.408321px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">AUTO</font></nobr>");
write("</p>");
write("<p id=\"p20_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407.786452px;top:236.408321px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">GND</font></nobr>");
write("</p>");
write("<p id=\"p20_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564.810690px;top:228.097364px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">VBU</font></nobr>");
write("</p>");
write("<p id=\"p20_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441.569387px;top:228.097364px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">OPEN</font></nobr>");
write("</p>");
write("<p id=\"p20_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492.452068px;top:236.408321px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">OPEN</font></nobr>");
write("</p>");
write("<p id=\"p20_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:489.742768px;top:230.867909px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">CPU</font></nobr>");
write("</p>");
write("<p id=\"p20_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:548.886781px;top:160.817053px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p20_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:507.093801px;top:360.480403px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p20_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450.862285px;top:360.480403px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p20_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515.484502px;top:311.206265px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p20_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500.164090px;top:311.206265px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p20_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483.129368px;top:311.121653px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p20_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:451.060742px;top:311.206265px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">8</font></nobr>");
write("</p>");
write("<p id=\"p20_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:751.793011px;top:343.677079px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.フロント<br>スピーカ</font></nobr>");
write("</p>");
write("<p id=\"p20_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838.653159px;top:223.007765px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">フィーダ線</font></nobr>");
write("</p>");
write("<p id=\"p20_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838.653159px;top:242.547789px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">サブ<br>フィーダ線</font></nobr>");
write("</p>");
write("<p id=\"p20_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:732.446579px;top:271.077701px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">オーディオ ユニット</font></nobr>");
write("</p>");
write("<p id=\"p20_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:863.525208px;top:199.437488px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ルーフ アンテナ<br>(AM/FM)</font></nobr>");
write("</p>");
write("<p id=\"p20_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:794.288376px;top:343.880148px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.フロント<br>スピーカ</font></nobr>");
write("</p>");
write("<p id=\"p20_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838.622680px;top:344.079156px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.リヤ<br>スピーカ</font></nobr>");
write("</p>");
write("<p id=\"p20_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:883.022684px;top:344.079156px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.リヤ<br>スピーカ</font></nobr>");
write("</p>");
write("<p id=\"p20_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:749.788806px;top:276.593068px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FR<br>L＋</font></nobr>");
write("</p>");
write("<p id=\"p20_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714.671540px;top:287.873579px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A12</font></nobr>");
write("</p>");
write("<p id=\"p20_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:898.744750px;top:287.873579px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A6</font></nobr>");
write("</p>");
write("<p id=\"p20_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:882.618321px;top:287.873579px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A7</font></nobr>");
write("</p>");
write("<p id=\"p20_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:839.616316px;top:287.873579px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A11</font></nobr>");
write("</p>");
write("<p id=\"p20_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:856.006902px;top:287.873579px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A10</font></nobr>");
write("</p>");
write("<p id=\"p20_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:812.943937px;top:287.873579px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A18</font></nobr>");
write("</p>");
write("<p id=\"p20_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:796.820217px;top:287.873579px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A19</font></nobr>");
write("</p>");
write("<p id=\"p20_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754.020732px;top:287.873579px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A23</font></nobr>");
write("</p>");
write("<p id=\"p20_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:770.445862px;top:287.873579px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A22</font></nobr>");
write("</p>");
write("<p id=\"p20_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:898.744750px;top:327.810582px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p20_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:882.618321px;top:327.810582px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p20_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:839.616316px;top:327.810582px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p20_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:856.006902px;top:327.810582px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p20_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:812.943937px;top:327.810582px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p20_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:796.820217px;top:327.810582px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p20_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754.020732px;top:327.810582px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p20_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:770.445862px;top:327.810582px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p20_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:880.141344px;top:255.439995px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">E1</font></nobr>");
write("</p>");
write("<p id=\"p20_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:672.319767px;top:262.691607px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">VSP</font></nobr>");
write("</p>");
write("<p id=\"p20_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:898.683791px;top:255.238280px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">E3</font></nobr>");
write("</p>");
write("<p id=\"p20_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:861.795320px;top:255.238280px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">E2</font></nobr>");
write("</p>");
write("<p id=\"p20_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:708.552587px;top:261.995079px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">＋B<br>BACK UP</font></nobr>");
write("</p>");
write("<p id=\"p20_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714.485953px;top:255.238280px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A24</font></nobr>");
write("</p>");
write("<p id=\"p20_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:677.561585px;top:255.238280px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A15</font></nobr>");
write("</p>");
write("<p id=\"p20_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:891.225766px;top:262.691607px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ANT＋B</font></nobr>");
write("</p>");
write("<p id=\"p20_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:743.916399px;top:262.691607px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ACC</font></nobr>");
write("</p>");
write("<p id=\"p20_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765.913203px;top:276.591715px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FR<br>L-</font></nobr>");
write("</p>");
write("<p id=\"p20_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:792.385771px;top:276.591715px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FR<br>R＋</font></nobr>");
write("</p>");
write("<p id=\"p20_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:808.710657px;top:276.591715px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">FR<br>R-</font></nobr>");
write("</p>");
write("<p id=\"p20_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:835.384389px;top:276.591715px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">RR<br>L＋</font></nobr>");
write("</p>");
write("<p id=\"p20_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:851.512173px;top:276.591715px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">RR<br>L-</font></nobr>");
write("</p>");
write("<p id=\"p20_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:854.741659px;top:262.691607px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">AM/FM<br>SH</font></nobr>");
write("</p>");
write("<p id=\"p20_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:878.185229px;top:276.591715px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">RR<br>R＋</font></nobr>");
write("</p>");
write("<p id=\"p20_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:894.310304px;top:276.591715px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">RR<br>R-</font></nobr>");
write("</p>");
write("<p id=\"p20_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:641.477776px;top:255.238280px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A13</font></nobr>");
write("</p>");
write("<p id=\"p20_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636.236636px;top:263.296077px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ILL＋</font></nobr>");
write("</p>");
write("<p id=\"p20_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:750.367242px;top:255.238280px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A14</font></nobr>");
write("</p>");
write("<p id=\"p20_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:873.084972px;top:262.691607px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">AM/FM<br>SIG</font></nobr>");
write("</p>");
write("<p id=\"p20_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706.703490px;top:276.591715px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MAIN<br>GND</font></nobr>");
write("</p>");
write("<p id=\"p20_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:880.542997px;top:212.126624px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p20_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:899.000102px;top:212.126624px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p20_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:861.997841px;top:212.126624px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p20_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:778.290639px;top:237.922543px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">サブ<br>フィーダ線</font></nobr>");
write("</p>");
write("<p id=\"p20_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:795.434410px;top:158.854724px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">マスト アンテナ<br>(AM/FM)</font></nobr>");
write("</p>");
write("<p id=\"p20_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:773.552751px;top:149.623861px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(マスト アンテナ装備車)</font></nobr>");
write("</p>");
write("<p id=\"p20_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:836.116578px;top:149.623861px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(ルーフ アンテナ装備車)</font></nobr>");
write("</p>");
write("<p id=\"p20_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:811.966557px;top:255.439995px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">E1</font></nobr>");
write("</p>");
write("<p id=\"p20_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:793.620534px;top:255.238280px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">E2</font></nobr>");
write("</p>");
write("<p id=\"p20_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:786.566872px;top:262.691607px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">AM/FM<br>SH</font></nobr>");
write("</p>");
write("<p id=\"p20_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:804.910186px;top:262.691607px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">AM/FM<br>SIG</font></nobr>");
write("</p>");
write("<p id=\"p20_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:812.368211px;top:222.274684px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p20_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805.058520px;top:214.654839px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p20_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838.479764px;top:32.374915px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*1：ヒューズ ボックス</font></nobr>");
write("</p>");
write("<p id=\"p20_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:867.998940px;top:55.904579px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">：シールド線</font></nobr>");
write("</p>");
write("<p id=\"p20_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:867.998940px;top:51.403881px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">：工場出荷時は未装備</font></nobr>");
write("</p>");
write("<p id=\"p20_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838.479764px;top:36.989331px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*2：リモート コントロール スイッチ1</font></nobr>");
write("</p>");
write("<p id=\"p20_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838.479764px;top:41.603747px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*3：リモート コントロール スイッチ3</font></nobr>");
write("</p>");
write("<p id=\"p20_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838.479764px;top:46.218840px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*4：CESS Assy.</font></nobr>");
write("</p>");
write("<p id=\"p20_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1.191006px;top:16.000067px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.2pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">20</font></nobr>");
write("</p>");
write("<p id=\"p20_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:933.721132px;top:16.000067px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.2pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">20</font></nobr>");
write("</p>");
write("<p id=\"p20_224\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:643.884989px;top:287.874933px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A16</font></nobr>");
write("</p>");
write("<p id=\"p20_225\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:677.102359px;top:287.874933px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">A5</font></nobr>");
write("</p>");
write("<p id=\"p20_226\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632.907584px;top:280.811499px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">REMOTE</font></nobr>");
write("</p>");
write("<p id=\"p20_227\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666.317314px;top:276.750109px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">REMOTE<br>GND</font></nobr>");
write("</p>");
write("<p id=\"p20_228\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637.456498px;top:346.802319px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ケーブル リール(22-B)</font></nobr>");
write("</p>");
write("<p id=\"p20_229\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:639.887418px;top:312.657535px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p20_230\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673.105464px;top:312.657535px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p20_231\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638.546992px;top:332.847382px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">190</font></nobr>");
write("</p>");
write("<p id=\"p20_232\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:672.052901px;top:338.597634px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">191</font></nobr>");
write("</p>");
write("</v:group>");
}