with(document) {
write("<v:group id=\"group9\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:493.10px;\" coordsize=\"950.00,493.10\">");
write("<v:rect id=\"rect9\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:493.10px;\">");
write("<img id=\"img9\" name=\"PrtImgId\" src=\"../img/5222_3.0_jpn_9695551_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:493.10px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p9_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:587.312994px;top:20.799953px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">C</font></nobr>");
write("</p>");
write("<p id=\"p9_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131.328879px;top:20.799953px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">A</font></nobr>");
write("</p>");
write("<p id=\"p9_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359.320598px;top:20.799953px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">B</font></nobr>");
write("</p>");
write("<p id=\"p9_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815.304712px;top:20.799953px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">D</font></nobr>");
write("</p>");
write("<p id=\"p9_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:8.680868px;top:15.966899px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.2pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">9</font></nobr>");
write("</p>");
write("<p id=\"p9_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:934.108903px;top:16.014282px;font-weight:normal;font-size:8.2pt;color:black;\" prt_font_size=\"9.2pt\" disp_font_size=\"8.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">9</font></nobr>");
write("</p>");
write("<p id=\"p9_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19.136736px;top:10.934837px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.1pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">インテリア ライト、フロント ポジション ライト、テールライト、ライセンス プレート ライト、バック ライト、ブレーキ ライト</font></nobr>");
write("</p>");
write("<p id=\"p9_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:861.579568px;top:31.407627px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*1：ヒューズ ボックス</font></nobr>");
write("</p>");
write("<p id=\"p9_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:861.579568px;top:36.548670px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*2：12LED</font></nobr>");
write("</p>");
write("<p id=\"p9_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:601.591008px;top:132.806999px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">OFF</font></nobr>");
write("</p>");
write("<p id=\"p9_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:582.964566px;top:132.161915px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ON</font></nobr>");
write("</p>");
write("<p id=\"p9_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:601.904610px;top:116.179668px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(8W)</font></nobr>");
write("</p>");
write("<p id=\"p9_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:597.344179px;top:98.826025px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p9_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602.998490px;top:156.273034px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">インテリア<br>ライト</font></nobr>");
write("</p>");
write("<p id=\"p9_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:597.357726px;top:155.801913px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:654.024105px;top:132.806999px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">OFF</font></nobr>");
write("</p>");
write("<p id=\"p9_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:498.404581px;top:27.714470px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(スカイ ルーフ非装備車)</font></nobr>");
write("</p>");
write("<p id=\"p9_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251.822319px;top:27.714470px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(スカイ ルーフ装備車)</font></nobr>");
write("</p>");
write("<p id=\"p9_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:635.397662px;top:132.161915px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ON</font></nobr>");
write("</p>");
write("<p id=\"p9_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:654.337706px;top:116.179668px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(8W)</font></nobr>");
write("</p>");
write("<p id=\"p9_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649.777953px;top:98.826025px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p9_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:655.432941px;top:156.273034px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">カーゴ<br>エリア<br>ライト</font></nobr>");
write("</p>");
write("<p id=\"p9_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649.790823px;top:155.801913px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:445.710037px;top:132.161915px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">OFF</font></nobr>");
write("</p>");
write("<p id=\"p9_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427.471702px;top:132.161915px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ON</font></nobr>");
write("</p>");
write("<p id=\"p9_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:445.926781px;top:116.179668px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(8W)</font></nobr>");
write("</p>");
write("<p id=\"p9_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441.367028px;top:98.826025px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p9_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342.867691px;top:208.154585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">OFF</font></nobr>");
write("</p>");
write("<p id=\"p9_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324.630034px;top:208.154585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ON</font></nobr>");
write("</p>");
write("<p id=\"p9_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397.869882px;top:208.154585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">OFF</font></nobr>");
write("</p>");
write("<p id=\"p9_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:379.631547px;top:208.154585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ON</font></nobr>");
write("</p>");
write("<p id=\"p9_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447.087039px;top:155.934585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">カーゴ<br>エリア<br>ライト</font></nobr>");
write("</p>");
write("<p id=\"p9_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441.379897px;top:155.801913px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:379.426995px;top:132.161915px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ON</font></nobr>");
write("</p>");
write("<p id=\"p9_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397.881397px;top:116.179668px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(5W)</font></nobr>");
write("</p>");
write("<p id=\"p9_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393.321644px;top:98.826025px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p9_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:399.041655px;top:155.934585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.<br>インテリア<br>ライト</font></nobr>");
write("</p>");
write("<p id=\"p9_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393.334513px;top:155.801913px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331.380934px;top:132.161915px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ON</font></nobr>");
write("</p>");
write("<p id=\"p9_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393.917690px;top:136.642305px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ドア</font></nobr>");
write("</p>");
write("<p id=\"p9_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345.872983px;top:136.642305px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ドア</font></nobr>");
write("</p>");
write("<p id=\"p9_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:392.393708px;top:218.378457px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ドア</font></nobr>");
write("</p>");
write("<p id=\"p9_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349.836690px;top:116.179668px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(5W)</font></nobr>");
write("</p>");
write("<p id=\"p9_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345.276260px;top:98.826025px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p9_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350.996271px;top:155.934585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.<br>インテリア<br>ライト</font></nobr>");
write("</p>");
write("<p id=\"p9_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345.289129px;top:155.801913px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385.973343px;top:155.801913px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p9_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337.927282px;top:155.801913px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p9_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393.334513px;top:228.795923px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">11</font></nobr>");
write("</p>");
write("<p id=\"p9_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337.927282px;top:228.795923px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">9</font></nobr>");
write("</p>");
write("<p id=\"p9_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393.334513px;top:195.759222px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p9_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337.927282px;top:195.759222px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">12</font></nobr>");
write("</p>");
write("<p id=\"p9_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297.163143px;top:155.801913px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p9_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:303.271262px;top:132.161915px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ON</font></nobr>");
write("</p>");
write("<p id=\"p9_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265.841595px;top:132.161915px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ON</font></nobr>");
write("</p>");
write("<p id=\"p9_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:288.955994px;top:132.161915px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">OFF</font></nobr>");
write("</p>");
write("<p id=\"p9_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279.161872px;top:132.161915px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">OFF</font></nobr>");
write("</p>");
write("<p id=\"p9_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:290.391246px;top:98.826025px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278.991186px;top:123.029203px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(8W)</font></nobr>");
write("</p>");
write("<p id=\"p9_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301.790629px;top:123.029203px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(8W)</font></nobr>");
write("</p>");
write("<p id=\"p9_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301.803498px;top:155.934585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">マップ<br>ライト</font></nobr>");
write("</p>");
write("<p id=\"p9_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295.348589px;top:209.141502px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">インテリア<br>ライト<br>スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p9_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:276.470182px;top:35.758730px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.1(10A)*<sup>1</sup><br>ヒューズ<br>(1-C)</font></nobr>");
write("</p>");
write("<p id=\"p9_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:285.847749px;top:49.865968px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">15</font></nobr>");
write("</p>");
write("<p id=\"p9_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387.640241px;top:243.937462px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">117</font></nobr>");
write("</p>");
write("<p id=\"p9_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435.683593px;top:243.937462px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">118</font></nobr>");
write("</p>");
write("<p id=\"p9_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:591.662775px;top:243.937462px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">119</font></nobr>");
write("</p>");
write("<p id=\"p9_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292.834358px;top:166.012924px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p9_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340.891934px;top:166.012924px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p9_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388.937995px;top:166.012924px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p9_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363.270080px;top:180.981854px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p9_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:436.975252px;top:189.351025px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p9_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:334.019793px;top:234.122436px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388.937995px;top:234.347843px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p9_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:286.078717px;top:68.505041px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p9_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593.042487px;top:90.391872px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p9_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:437.064658px;top:90.391872px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p9_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389.019274px;top:90.391872px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p9_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340.973890px;top:90.391872px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p9_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364.792708px;top:79.665741px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p9_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312.866250px;top:79.665741px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p9_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:286.078717px;top:90.391872px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p9_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:550.956210px;top:132.161915px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ON</font></nobr>");
write("</p>");
write("<p id=\"p9_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513.525866px;top:132.161915px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ON</font></nobr>");
write("</p>");
write("<p id=\"p9_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536.640265px;top:132.161915px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">OFF</font></nobr>");
write("</p>");
write("<p id=\"p9_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:526.846820px;top:132.161915px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">OFF</font></nobr>");
write("</p>");
write("<p id=\"p9_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538.076194px;top:98.826025px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:526.676134px;top:123.029203px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(8W)</font></nobr>");
write("</p>");
write("<p id=\"p9_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:549.475577px;top:123.029203px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">(8W)</font></nobr>");
write("</p>");
write("<p id=\"p9_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:546.888872px;top:155.934585px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">マップ<br>ライト</font></nobr>");
write("</p>");
write("<p id=\"p9_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:524.923217px;top:35.758730px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.1(10A)*<sup>1</sup><br>ヒューズ<br>(1-C)</font></nobr>");
write("</p>");
write("<p id=\"p9_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:533.532697px;top:49.865968px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">17</font></nobr>");
write("</p>");
write("<p id=\"p9_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:533.762988px;top:68.505041px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p9_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:533.762988px;top:90.391872px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p9_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645.470165px;top:90.391872px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p9_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593.045196px;top:173.876452px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p9_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593.045196px;top:220.357031px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p9_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645.218877px;top:173.876452px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p9_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333.970348px;top:166.013601px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p9_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388.937995px;top:189.160817px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p9_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333.970348px;top:189.161494px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p9_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382.052985px;top:166.013601px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p9_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385.823654px;top:255.121853px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(12-B)</font></nobr>");
write("</p>");
write("<p id=\"p9_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:433.867006px;top:255.121853px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(12-B)</font></nobr>");
write("</p>");
write("<p id=\"p9_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:589.847544px;top:255.121853px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(12-B)</font></nobr>");
write("</p>");
write("<p id=\"p9_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330.631812px;top:251.400943px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G501</font></nobr>");
write("</p>");
write("<p id=\"p9_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690.112667px;top:371.272193px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.バック<br>ライト<br>(16W)</font></nobr>");
write("</p>");
write("<p id=\"p9_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685.552237px;top:369.445245px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p9_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685.552237px;top:383.144314px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p9_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:655.929421px;top:371.309423px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.バック<br>ライト<br>(16W)</font></nobr>");
write("</p>");
write("<p id=\"p9_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:651.369667px;top:369.483828px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p9_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:651.369667px;top:383.182897px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p9_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229.990096px;top:368.314825px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.<br>フロント<br>ポジション<br>ライト<br>(5W)</font></nobr>");
write("</p>");
write("<p id=\"p9_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:224.371683px;top:369.880491px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:224.371683px;top:383.579559px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p9_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:163.520790px;top:368.314825px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.<br>フロント<br>ポジション<br>ライト<br>(5W)</font></nobr>");
write("</p>");
write("<p id=\"p9_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:157.901700px;top:369.880491px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:157.901700px;top:383.579559px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p9_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642.426266px;top:272.761824px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(12-C)</font></nobr>");
write("</p>");
write("<p id=\"p9_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645.678104px;top:283.045263px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">165</font></nobr>");
write("</p>");
write("<p id=\"p9_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:215.671442px;top:273.182855px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(13-B)</font></nobr>");
write("</p>");
write("<p id=\"p9_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218.669283px;top:283.452756px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">173</font></nobr>");
write("</p>");
write("<p id=\"p9_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:149.202136px;top:273.182855px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(13-B)</font></nobr>");
write("</p>");
write("<p id=\"p9_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:152.199299px;top:283.452756px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">172</font></nobr>");
write("</p>");
write("<p id=\"p9_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:643.673899px;top:468.057149px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G701</font></nobr>");
write("</p>");
write("<p id=\"p9_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:677.872724px;top:468.057149px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G602</font></nobr>");
write("</p>");
write("<p id=\"p9_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216.664401px;top:468.057149px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G202</font></nobr>");
write("</p>");
write("<p id=\"p9_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150.194417px;top:468.057149px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G401</font></nobr>");
write("</p>");
write("<p id=\"p9_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:681.176039px;top:423.821842px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:646.970440px;top:423.821842px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219.968393px;top:423.821842px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153.498409px;top:423.821842px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:646.974504px;top:316.290449px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p9_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:646.885774px;top:354.101313px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p9_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:681.161815px;top:354.101313px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p9_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:664.209044px;top:335.142068px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p9_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715.341676px;top:354.101313px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p9_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153.494345px;top:316.291802px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p9_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219.964329px;top:316.291802px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p9_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:751.592796px;top:358.817941px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ブレーキ<br>スイッチ<br>(ON：<br>ブレーキ<br>ペダルを<br>踏む)</font></nobr>");
write("</p>");
write("<p id=\"p9_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:778.841589px;top:383.537591px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p9_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:778.841589px;top:353.853569px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:773.156121px;top:426.312828px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">120</font></nobr>");
write("</p>");
write("<p id=\"p9_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:764.921879px;top:268.938025px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.24(10A)*<sup>1</sup><br>ヒューズ<br>(2-D)</font></nobr>");
write("</p>");
write("<p id=\"p9_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:774.498579px;top:283.045263px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">89</font></nobr>");
write("</p>");
write("<p id=\"p9_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:762.258636px;top:437.651553px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">・PGM-FI ECU<br>(4-C)</font></nobr>");
write("</p>");
write("<p id=\"p9_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:762.258636px;top:446.153396px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">・MICU(12-C)</font></nobr>");
write("</p>");
write("<p id=\"p9_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714.035116px;top:390.651116px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">192</font></nobr>");
write("</p>");
write("<p id=\"p9_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:702.752910px;top:401.989840px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">AVNユニット*<sup>3</sup><br>(21-A)</font></nobr>");
write("</p>");
write("<p id=\"p9_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:774.619143px;top:316.290449px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p9_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:772.094075px;top:405.381778px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p9_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:753.895702px;top:132.251942px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ライセンス<br>プレート<br>ライト<br>(5W)</font></nobr>");
write("</p>");
write("<p id=\"p9_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:748.277967px;top:131.441695px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:748.277967px;top:145.140764px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p9_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:739.577725px;top:39.596067px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(13-B)</font></nobr>");
write("</p>");
write("<p id=\"p9_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742.574889px;top:49.865968px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">174</font></nobr>");
write("</p>");
write("<p id=\"p9_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740.570684px;top:229.618354px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G602</font></nobr>");
write("</p>");
write("<p id=\"p9_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:743.873999px;top:185.383047px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:743.869935px;top:90.392549px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p9_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:273.620674px;top:348.084364px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(13-B)</font></nobr>");
write("</p>");
write("<p id=\"p9_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:482.656771px;top:357.822223px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">179</font></nobr>");
write("</p>");
write("<p id=\"p9_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505.869382px;top:316.291125px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p9_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:433.560178px;top:316.291125px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p9_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:433.560178px;top:297.907243px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p9_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299.725465px;top:316.291125px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p9_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503.810314px;top:440.081618px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">R.テールライト/ブレーキ ライト<br>(LED)</font></nobr>");
write("</p>");
write("<p id=\"p9_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394.133079px;top:438.797541px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">ハイ マウント<br>ストップ ランプ<br>(LED)</font></nobr>");
write("</p>");
write("<p id=\"p9_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511.529111px;top:328.305394px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p9_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:499.600737px;top:422.887723px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p9_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:582.012924px;top:438.672992px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p9_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483.842767px;top:392.396160px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p9_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:458.751256px;top:344.339086px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*2</font></nobr>");
write("</p>");
write("<p id=\"p9_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:439.408203px;top:328.306071px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p9_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:433.820271px;top:438.739328px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p9_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434.196864px;top:283.044587px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">154</font></nobr>");
write("</p>");
write("<p id=\"p9_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431.736141px;top:273.034614px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(12-C)</font></nobr>");
write("</p>");
write("<p id=\"p9_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:480.164891px;top:348.068795px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">MICU<br>(13-B)</font></nobr>");
write("</p>");
write("<p id=\"p9_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:575.029702px;top:468.057149px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G602</font></nobr>");
write("</p>");
write("<p id=\"p9_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:276.511499px;top:358.013785px;font-weight:normal;font-size:1.5pt;color:black;\" prt_font_size=\"3.0pt\" disp_font_size=\"1.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">176</font></nobr>");
write("</p>");
write("<p id=\"p9_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297.667750px;top:440.081618px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">L.テールライト/ブレーキ ライト<br>(LED)</font></nobr>");
write("</p>");
write("<p id=\"p9_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:305.385194px;top:328.305394px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p9_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:293.648503px;top:422.887723px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p9_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:375.869006px;top:438.864554px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p9_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:277.700204px;top:392.396160px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p9_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:368.885783px;top:468.057149px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G701</font></nobr>");
write("</p>");
write("<p id=\"p9_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:426.048642px;top:468.057149px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">G602</font></nobr>");
write("</p>");
write("<p id=\"p9_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578.332339px;top:450.356258px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429.351279px;top:450.356258px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:372.188421px;top:450.356258px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p9_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:861.579568px;top:41.419631px;font-weight:normal;font-size:2.2pt;color:black;\" prt_font_size=\"3.1pt\" disp_font_size=\"2.2pt\">");
write("<nobr><font style=\"font-weight:normal;\">*3：YOPナビ用ハーネス装備車</font></nobr>");
write("</p>");
write("</v:group>");
}