with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:546.07px;\" coordsize=\"950.00,546.07\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:546.07px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/795_2.0_jpn_9510803_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:546.07px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:803.589126px;top:33.214115px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">ABSモジュレータ コントロール ユニット</font></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807.355326px;top:47.334027px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">コントロール ユニット</font></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:811.863489px;top:109.315146px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">フェイル セーフ リレー</font></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:799.201552px;top:127.727706px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">モータ リレー</font></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765.910776px;top:82.410442px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">20</font></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765.910776px;top:92.681219px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">IG1</font></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397.815409px;top:66.686566px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">IG1</font></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765.910776px;top:104.233436px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">24</font></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:749.405646px;top:114.503250px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">FSR +B</font></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765.910776px;top:123.408826px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">25</font></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:752.611291px;top:133.678640px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">MR +B</font></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765.910776px;top:222.330038px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">12</font></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:751.169039px;top:232.599852px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">CAN-H</font></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769.756781px;top:241.907864px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:753.092042px;top:252.177677px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">CAN-L</font></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769.756781px;top:280.901770px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">5</font></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:753.090118px;top:291.170622px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">K-LINE</font></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765.910776px;top:300.800196px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">22</font></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:755.734247px;top:311.070973px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">FL +B</font></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765.910776px;top:378.789935px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">10</font></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:755.190037px;top:389.058787px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">RL +B</font></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:770.076000px;top:417.302460px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">8</font></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:753.908356px;top:427.573236px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">RR +B</font></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769.756781px;top:339.634285px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:755.190037px;top:349.905061px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">FR +B</font></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765.910776px;top:320.217240px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">11</font></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602.055581px;top:300.800196px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602.055581px;top:320.217240px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602.055581px;top:339.715156px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528.820915px;top:354.523445px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">ホイール センサ</font></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602.055581px;top:359.132200px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602.055581px;top:379.109574px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602.055581px;top:398.528542px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602.055581px;top:418.024534px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602.055581px;top:437.443502px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:749.886396px;top:330.488017px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">FL-GND</font></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769.756781px;top:359.372892px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:748.603754px;top:369.643669px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">FR-GND</font></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765.910776px;top:398.206979px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">21</font></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:749.886396px;top:408.477756px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">RL-GND</font></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765.910776px;top:456.779674px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">26</font></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:746.040391px;top:467.048525px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">MR-GND</font></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765.910776px;top:476.516356px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">23</font></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:759.822551px;top:486.787133px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">GND</font></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:764.949275px;top:437.042992px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">19</font></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:747.321111px;top:447.311844px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">RR-GND</font></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:579.219926px;top:139.204911px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">A42</font></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:583.787057px;top:156.293989px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">A3</font></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:583.787057px;top:173.623759px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">A4</font></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:597.328841px;top:134.872469px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">PGM-FI ECU</font></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:890.963628px;top:283.303869px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">ソレノイド</font></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:894.809633px;top:291.968753px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">フロント左</font></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:918.046234px;top:306.409265px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">IN</font></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:912.757977px;top:321.171340px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">OUT</font></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:918.046234px;top:341.710968px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">IN</font></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:912.757977px;top:356.473043px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">OUT</font></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:918.046234px;top:376.692070px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">IN</font></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:912.757977px;top:391.454145px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">OUT</font></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:918.046234px;top:411.832992px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">IN</font></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:912.757977px;top:426.595067px;font-weight:normal;font-size:3.0pt;color:black;\" prt_font_size=\"4.4pt\" disp_font_size=\"3.0pt\">");
write("<nobr><font style=\"font-weight:normal;\">OUT</font></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:894.809633px;top:362.893723px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">リヤ左</font></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:894.809633px;top:397.872900px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">リヤ右</font></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:892.902781px;top:445.851799px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">ポンプ モータ</font></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:799.140260px;top:517.976867px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">: 12V</font></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:799.380634px;top:528.085899px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">: 5V</font></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:795.294255px;top:388.067138px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">GND</font></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:829.588120px;top:327.671929px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">IG1</font></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:804.028532px;top:261.882348px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">IG1</font></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:794.332753px;top:346.925303px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">+B</font></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:909.552332px;top:470.401835px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">M</font></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:894.809633px;top:327.591057px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">フロント右</font></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:718.355887px;top:86.800651px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:718.355887px;top:324.603598px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:718.355887px;top:441.579541px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:718.355887px;top:461.797606px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:718.355887px;top:481.052905px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:718.355887px;top:343.858897px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">緑</font></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:718.355887px;top:363.595579px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">桃</font></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:718.355887px;top:382.850878px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:718.355887px;top:127.396598px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:718.355887px;top:227.524155px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:718.355887px;top:246.779455px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:718.355887px;top:402.747379px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:718.355887px;top:285.771436px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:565.636798px;top:160.773734px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:562.031168px;top:143.925348px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:565.636798px;top:177.460376px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:718.355887px;top:305.348298px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:718.355887px;top:421.842859px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">空</font></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:499.577817px;top:226.561390px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:499.577817px;top:246.779455px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:148.514482px;top:53.585259px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348.667312px;top:69.630701px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">黄</font></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348.667312px;top:86.960470px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348.667312px;top:108.622682px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348.667312px;top:127.155907px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:152.039346px;top:227.007150px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:152.039346px;top:246.503141px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:152.038302px;top:263.110765px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">橙</font></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:152.039346px;top:279.718532px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">灰</font></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348.667312px;top:144.244985px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:443.615560px;top:69.630701px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:443.615560px;top:144.244985px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">若葉</font></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:148.514482px;top:144.406730px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355.797805px;top:347.514515px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355.797805px;top:364.362902px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">赤</font></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355.797805px;top:379.526451px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">青</font></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355.797805px;top:396.134146px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">紫</font></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355.797805px;top:412.981570px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:179.202717px;top:407.525581px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">黒</font></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:62.138018px;top:46.939293px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.1(100A)</font></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242.901214px;top:47.260857px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.60(50A)</font></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:411.644681px;top:62.424404px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">3</font></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389.049402px;top:62.424404px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:409.481304px;top:137.520072px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391.693531px;top:137.520072px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322.465441px;top:343.195552px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">6</font></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249.475128px;top:350.896632px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249.931218px;top:370.389299px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:173.673124px;top:350.897672px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">2</font></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:173.673124px;top:370.393662px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">1</font></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:173.192373px;top:479.185140px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">G301</font></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:394.337659px;top:458.968039px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">G502</font></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:681.826531px;top:511.437766px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">G203</font></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321.503940px;top:359.803248px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">14</font></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322.465441px;top:375.448178px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">7</font></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322.465441px;top:408.661644px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">4</font></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321.503940px;top:392.296565px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">16</font></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:428.392857px;top:396.043649px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">+B</font></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:545.391428px;top:372.076575px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">IC</font></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297.145268px;top:332.202701px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">データリンク カプラ</font></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118.786787px;top:222.367586px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">30</font></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118.786787px;top:241.943486px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">29</font></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118.786787px;top:258.791872px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">20</font></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118.786787px;top:275.640259px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">19</font></nobr>");
write("</p>");
write("<p id=\"p1_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242.901214px;top:80.235557px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.11(7.5A)</font></nobr>");
write("</p>");
write("<p id=\"p1_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242.901214px;top:101.897768px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.37(20A)</font></nobr>");
write("</p>");
write("<p id=\"p1_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242.901214px;top:120.430994px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.58(40A)</font></nobr>");
write("</p>");
write("<p id=\"p1_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242.901214px;top:137.279381px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.24(10A)</font></nobr>");
write("</p>");
write("<p id=\"p1_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201.806651px;top:48.223622px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">T9</font></nobr>");
write("</p>");
write("<p id=\"p1_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315.014768px;top:81.983938px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">A32</font></nobr>");
write("</p>");
write("<p id=\"p1_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315.014768px;top:103.176320px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">A2</font></nobr>");
write("</p>");
write("<p id=\"p1_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315.014768px;top:122.150492px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">A23</font></nobr>");
write("</p>");
write("<p id=\"p1_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315.014768px;top:139.647783px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">B28</font></nobr>");
write("</p>");
write("<p id=\"p1_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309.245761px;top:64.873679px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">W1</font></nobr>");
write("</p>");
write("<p id=\"p1_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309.245761px;top:48.506674px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">T1</font></nobr>");
write("</p>");
write("<p id=\"p1_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201.555698px;top:139.045092px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">B23</font></nobr>");
write("</p>");
write("<p id=\"p1_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68.387776px;top:136.957817px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">No.3(20A)</font></nobr>");
write("</p>");
write("<p id=\"p1_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:31.847635px;top:13.722064px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">バッテリ</font></nobr>");
write("</p>");
write("<p id=\"p1_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234.496541px;top:30.119391px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">ヒューズ ボックス</font></nobr>");
write("</p>");
write("<p id=\"p1_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367.892110px;top:52.236210px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">イグニッション スイッチ</font></nobr>");
write("</p>");
write("<p id=\"p1_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:46.210861px;top:203.675892px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">コンビネーション メータ</font></nobr>");
write("</p>");
write("<p id=\"p1_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:59.974641px;top:228.625558px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">ブレーキ警告灯</font></nobr>");
write("</p>");
write("<p id=\"p1_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:64.061020px;top:265.130717px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">ABS警告灯</font></nobr>");
write("</p>");
write("<p id=\"p1_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:718.355887px;top:108.462863px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">白</font></nobr>");
write("</p>");
write("<p id=\"p1_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:111.163919px;top:353.636769px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">ブレーキ フルード<br>レベル スイッチ<br>ON:低い</font></nobr>");
write("</p>");
write("<p id=\"p1_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:56.606825px;top:27.277768px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">バッテリ ターミナル<br>ヒューズ ボックス</font></nobr>");
write("</p>");
write("<p id=\"p1_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:190.798742px;top:352.679896px;font-weight:normal;font-size:4.9pt;color:black;\" prt_font_size=\"4.6pt\" disp_font_size=\"4.9pt\">");
write("<nobr><font style=\"font-weight:normal;\">パーキング<br>ブレーキ スイッチ<br>ON:パーキング</font></nobr>");
write("</p>");
write("<p id=\"p1_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:798.361767px;top:233.092493px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">CAN<br>コントローラ</font></nobr>");
write("</p>");
write("<p id=\"p1_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:893.185123px;top:47.045898px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">モジュレータ<br>ユニット</font></nobr>");
write("</p>");
write("<p id=\"p1_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:375.211274px;top:157.311036px;font-weight:normal;font-size:3.7pt;color:black;\" prt_font_size=\"5.1pt\" disp_font_size=\"3.7pt\">");
write("<nobr><font style=\"font-weight:normal;\">ブレーキ スイッチ<br>ON:踏む</font></nobr>");
write("</p>");
write("<p id=\"p1_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:201.839024px;top:372.940961px;font-weight:normal;font-size:4.9pt;color:black;\" prt_font_size=\"4.6pt\" disp_font_size=\"4.9pt\">");
write("<nobr><font style=\"font-weight:normal;\">ブレーキをかける</font></nobr>");
write("</p>");
write("</v:group>");
}