with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950.00px; height:545.34px;\" coordsize=\"950.00,545.34\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\" strokecolor=\"white\" style=\"width:950.00px;height:545.34px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/929_2.0_jpn_9509976_2.0.png\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950.00px;height:545.34px;border-color:#ffffff\">");
write("</v:rect>");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:46.048592px;top:124.182732px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">アッパ クリップ(2)<br>(接着タイプ、ガラス 側)</font></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:722.326134px;top:42.031748px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">フロント ウインド<br>ガラス モール</font></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446.403511px;top:518.402470px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ダム ラバーC</font></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:40.533027px;top:275.769816px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ダム ラバーB</font></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:209.407491px;top:200.355388px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ダム ラバーA</font></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726.484465px;top:335.071920px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\"><font style=\"font-weight:normal;\">フロント ウインド ガラス</font><br><font style=\"font-weight:normal;\"><a title=\"フロント ウインド ガラスの脱着\" href=\"javascript:CtsProc('0','000000000002998','')\">脱着</a></font></font></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85.624934px;top:432.751977px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ダム ラバーB</font></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:599.395458px;top:366.217554px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ダム ラバーB</font></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:595.136056px;top:420.795319px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">インストルメント <br>パネル シールA</font></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:587.425816px;top:481.584715px;font-weight:normal;font-size:10.5pt;color:black;\" prt_font_size=\"11.6pt\" disp_font_size=\"10.5pt\">");
write("<nobr><font style=\"font-weight:normal;\">ダム ラバーD<br>(装備車を設定)</font></nobr>");
write("</p>");
write("</v:group>");
}